package lib.minecraft.renderer.tooling.entity;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import dev.simplified.collection.ConcurrentList;
import dev.simplified.collection.ConcurrentMap;
import lib.minecraft.renderer.pipeline.loader.EntityFamilyFlattener;
import lib.minecraft.renderer.tooling.util.Diagnostics;
import lib.minecraft.renderer.tooling.util.ToolingJson;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Emits {@code entity_models.json} in the normalized family form.
 *
 * <p>Groups the flat entity tables {@link EntityRuntimeJsonWriter} builds in-memory into one entry
 * per base entity: the flat {@code <id>_<variant>} rows collapse into a single family carrying a
 * {@code variant} axis, and the cross-entity {@code families} table collapses into per-family
 * {@code family_of} links. No field value is ever reparsed - every carried value
 * ({@code texture_ref}, {@code overlays}, {@code base_tint}, {@code renderer_scale}, ...) is copied
 * as a verbatim {@code JsonElement} deep-copy, so only the grouping structure changes.
 *
 * <p>Its transform is the inverse of {@link EntityFamilyFlattener#flatten}, which expands the family
 * form back into per-entity rows at load. See {@code notes/entity-family-schema.md} for the schema
 * contract and {@code notes/sample_model.json} for the wolf worked example.
 */
@UtilityClass
public final class EntityFamilyJsonWriter {

    /**
     * The canonical runtime metadata path. Holds the normalized family form (one entry per base
     * entity with axes + layers); flattened back to per-entity rows at load by
     * {@code EntityFamilyFlattener}.
     */
    public static final @NotNull Path OUTPUT =
        Path.of("src/main/resources/lib/minecraft/renderer/entity_models.json");

    /**
     * Groups the flat entity tables that {@link EntityRuntimeJsonWriter} built in-memory into the
     * normalized family form and writes {@code entity_models.json}.
     *
     * @param sourceVersion the source client-jar version, stamped into entity_models.json under source_version
     * @param diagnostics the diagnostic sink for the summary line
     * @param flatEntities the flat {@code entities} object (id -&gt; row) from {@code WriteResult}
     * @param flatFamilies the cross-entity {@code families} table from {@code WriteResult}
     * @param variants variant stem -&gt; resolved variant list, used to enrich variant families with
     *     option axes (e.g. wolf {@code wild}/{@code tame}/{@code angry} state textures) + per-variant
     *     baby textures the flat rows discard
     * @param collarByEntity base entity id -&gt; dyed-collar texture, used to add the option-gated
     *     collar {@code layer} to matching families
     * @param babyGeometryByEntity base entity id -&gt; deduped baby geometry id, used to add the
     *     {@code age} axis to matching families
     * @param babyTextureByEntity base entity id -&gt; baby texture from the renderer's isBaby branch
     *     (non-variant entities like sheep/fox), added as {@code age.baby.texture_ref}
     * @throws IOException when the family output cannot be written
     */
    public static void writeAll(
        @NotNull String sourceVersion,
        @NotNull Diagnostics diagnostics,
        @NotNull JsonObject flatEntities,
        @NotNull JsonObject flatFamilies,
        @NotNull ConcurrentMap<String, ConcurrentList<EntityVariantResolver.Result>> variants,
        @NotNull Map<String, String> collarByEntity,
        @NotNull Map<String, String> babyGeometryByEntity,
        @NotNull Map<String, String> babyTextureByEntity,
        @NotNull Map<String, ConcurrentList<EntityEquipmentResolver.Result>> equipmentByEntity,
        @NotNull Map<String, String> equipmentGeometryByField,
        @NotNull Map<String, String> shapeGeometryByEntity,
        @NotNull Map<String, Map<String, String>> sizeGeometryByEntity,
        @NotNull Map<String, Map<String, Float>> sizeScaleByEntity
    ) throws IOException {
        JsonObject families = group(flatEntities, flatFamilies, variants, collarByEntity, babyGeometryByEntity, babyTextureByEntity,
            equipmentByEntity, equipmentGeometryByField, shapeGeometryByEntity, sizeGeometryByEntity, sizeScaleByEntity, diagnostics);

        ToolingJson.writeResource(OUTPUT,
            "Generated by ToolingEntityModels. Normalized family form: one entry per base entity with axes (id-encoded colour variants; option-encoded state/age) + layers (collar, equipment), cross-entity groupings as family_of. Flattened to per-entity rows at load by EntityFamilyFlattener.",
            sourceVersion, "families", families);
        diagnostics.info("entity_models.json: %d families", families.size());
    }

    /**
     * Groups a flat {@code entities} object into the family form. Package-private for testing.
     *
     * <p>Each flat row is either a variant child (has {@code variant_of} - consumed under its
     * base), a variant base (targeted by some {@code variant_of} - heads a {@code variant} axis),
     * or a plain entity (its own single-row family). Family order follows the flat head order.
     *
     * @param entities the flat {@code entities} object (id -&gt; row)
     * @param crossFamilies the flat {@code families} table (derivative id -&gt; family root)
     * @param variants variant stem -&gt; resolved variant list for option-axis enrichment (may be
     *     {@code null} to skip enrichment)
     * @param collarByEntity base entity id -&gt; dyed-collar texture (may be {@code null})
     * @param babyGeometryByEntity base entity id -&gt; baby geometry id (may be {@code null})
     * @param babyTextureByEntity base entity id -&gt; baby texture id (may be {@code null})
     * @param diagnostics the diagnostic sink for structural warnings
     * @return the {@code families} object of the family form (family id -&gt; family entry)
     */
    static @NotNull JsonObject group(
        @NotNull JsonObject entities,
        @NotNull JsonObject crossFamilies,
        @Nullable ConcurrentMap<String, ConcurrentList<EntityVariantResolver.Result>> variants,
        @Nullable Map<String, String> collarByEntity,
        @Nullable Map<String, String> babyGeometryByEntity,
        @Nullable Map<String, String> babyTextureByEntity,
        @Nullable Map<String, ConcurrentList<EntityEquipmentResolver.Result>> equipmentByEntity,
        @Nullable Map<String, String> equipmentGeometryByField,
        @Nullable Map<String, String> shapeGeometryByEntity,
        @Nullable Map<String, Map<String, String>> sizeGeometryByEntity,
        @Nullable Map<String, Map<String, Float>> sizeScaleByEntity,
        @NotNull Diagnostics diagnostics
    ) {
        Map<String, List<String>> childrenOf = new LinkedHashMap<>();
        for (Map.Entry<String, JsonElement> entry : entities.entrySet()) {
            if (!entry.getValue().isJsonObject()) continue;
            JsonObject row = entry.getValue().getAsJsonObject();
            if (row.has("variant_of"))
                childrenOf.computeIfAbsent(row.get("variant_of").getAsString(), k -> new ArrayList<>()).add(entry.getKey());
        }

        JsonObject families = new JsonObject();
        for (Map.Entry<String, JsonElement> entry : entities.entrySet()) {
            if (!entry.getValue().isJsonObject()) continue;
            String id = entry.getKey();
            JsonObject row = entry.getValue().getAsJsonObject();
            if (row.has("variant_of")) continue;

            String familyId;
            JsonObject family;
            if (childrenOf.containsKey(id)) {
                familyId = familyStem(id, childrenOf.get(id), diagnostics);
                family = variantFamily(id, childrenOf.get(id), entities, crossFamilies, variants, diagnostics);
            } else {
                familyId = id;
                family = plainFamily(id, row, crossFamilies);
            }
            attachCollarLayer(familyId, family, collarByEntity);
            attachEquipmentLayers(familyId, family, equipmentByEntity, equipmentGeometryByField, diagnostics);
            attachAgeAxis(familyId, family, babyGeometryByEntity, babyTextureByEntity);
            attachShapeAxis(familyId, family, shapeGeometryByEntity);
            attachSizeAxis(familyId, family, sizeGeometryByEntity, sizeScaleByEntity);
            families.add(familyId, family);
        }
        return families;
    }

    /**
     * Adds an {@code age} axis (default {@code adult}) to a family with a distinct baby geometry,
     * the {@code baby} option overriding {@code geometry_ref} to the baked baby mesh. Additive -
     * the flattener ignores option axes, so the round-trip is unchanged.
     */
    private static void attachAgeAxis(@NotNull String familyId, @NotNull JsonObject family, @Nullable Map<String, String> babyGeometryByEntity, @Nullable Map<String, String> babyTextureByEntity) {
        if (babyGeometryByEntity == null) return;
        String babyGeometry = babyGeometryByEntity.get(familyId);
        if (babyGeometry == null) return;

        // Non-variant entities (sheep/fox) carry a single baby texture here; variant families
        // (cow/pig) instead hold per-variant baby textures under each option's textures.baby.
        // Fallback to vanilla's <adult>_baby naming when the renderer's isBaby branch surfaced none
        // (enum-variant entities like axolotl/rabbit read their texture from the variant enum, not
        // an isBaby branch, but still ship <default>_baby textures).
        String babyTexture = babyTextureByEntity == null ? null : babyTextureByEntity.get(familyId);
        if (babyTexture == null && family.has("texture_ref"))
            babyTexture = family.get("texture_ref").getAsString() + "_baby";
        JsonObject baby = ToolingJson.object()
            .put("geometry_ref", babyGeometry)
            .putIfNotNull("texture_ref", babyTexture)
            .build();
        // Only the "baby" option carries a body (the baked baby mesh + texture); the default "adult"
        // inherits the family top-level geometry_ref/texture_ref, so it needs no option entry - but
        // the uniform axis contract still lists it in "values" (the full ordered domain).
        JsonObject options = new JsonObject();
        options.add("baby", baby);
        attachAxis(family, "age", axis("adult", values("adult", "baby"), options));
    }

    /**
     * Adds a {@code shape} axis (default {@code small}) to a family with a distinct large body mesh
     * (tropical fish), the {@code large} option overriding {@code geometry_ref} + {@code texture_ref}
     * (the {@code tropical_a} -&gt; {@code tropical_b} atlas) and cloning the family's pattern overlays
     * onto the large geometry. Only tropical fish carries this today; the renderer resolves the
     * selected shape from the pattern's {@code Shape}, so the axis is additive and the flattener
     * round-trip is unchanged.
     */
    private static void attachShapeAxis(@NotNull String familyId, @NotNull JsonObject family, @Nullable Map<String, String> shapeGeometryByEntity) {
        if (shapeGeometryByEntity == null) return;
        String largeGeometry = shapeGeometryByEntity.get(familyId);
        if (largeGeometry == null) return;

        JsonObject large = new JsonObject();
        large.addProperty("geometry_ref", largeGeometry);
        if (family.has("texture_ref"))
            large.addProperty("texture_ref", family.get("texture_ref").getAsString().replace("tropical_a", "tropical_b"));
        // Clone the family's small pattern overlays onto the large body: swap the shared base
        // geometry_ref to the large mesh and the tropical_a atlas to tropical_b. The pattern axis
        // (texture_by: pattern) selects the concrete large pattern texture at render.
        if (family.has("overlays")) {
            JsonArray largeOverlays = new JsonArray();
            for (JsonElement element : family.getAsJsonArray("overlays")) {
                if (!element.isJsonObject()) continue;
                JsonObject clone = new JsonObject();
                for (Map.Entry<String, JsonElement> property : element.getAsJsonObject().entrySet())
                    clone.add(property.getKey(), property.getValue());
                clone.addProperty("geometry_ref", largeGeometry);
                if (clone.has("texture_ref"))
                    clone.addProperty("texture_ref", clone.get("texture_ref").getAsString().replace("tropical_a", "tropical_b"));
                largeOverlays.add(clone);
            }
            if (!largeOverlays.isEmpty()) large.add("overlays", largeOverlays);
        }

        JsonObject options = new JsonObject();
        options.add("large", large);
        attachAxis(family, "shape", axis("small", values("small", "large"), options));
    }

    /**
     * Adds a {@code size} axis to a family with per-size body variants. Two forms, one per entity:
     * <ul>
     *   <li><b>Mesh-select</b> (pufferfish small / medium / big) - each non-default size overrides
     *       {@code geometry_ref} to its distinct baked mesh.</li>
     *   <li><b>Scale</b> (salmon small / large; slime + magma_cube medium / large) - each non-default
     *       size carries a {@code scale} factor the renderer multiplies onto {@code renderer_scale}.</li>
     * </ul>
     * The default size (whichever of small/medium/large carries no option - pufferfish {@code large},
     * salmon {@code medium}, slime/magma {@code small}) inherits the family base geometry / scale and
     * carries no option, so the default (unset size) render is byte-identical. The renderer resolves the
     * selected size via {@code EntityAppearance.size}.
     */
    private static void attachSizeAxis(@NotNull String familyId, @NotNull JsonObject family,
            @Nullable Map<String, Map<String, String>> sizeGeometryByEntity,
            @Nullable Map<String, Map<String, Float>> sizeScaleByEntity) {
        Map<String, String> sizeGeometries = sizeGeometryByEntity == null ? null : sizeGeometryByEntity.get(familyId);
        Map<String, Float> sizeScales = sizeScaleByEntity == null ? null : sizeScaleByEntity.get(familyId);
        boolean hasGeometry = sizeGeometries != null && !sizeGeometries.isEmpty();
        boolean hasScale = sizeScales != null && !sizeScales.isEmpty();
        if (!hasGeometry && !hasScale) return;

        JsonObject options = new JsonObject();
        if (hasGeometry)
            for (Map.Entry<String, String> option : sizeGeometries.entrySet())
                options.add(option.getKey(), ToolingJson.object().put("geometry_ref", option.getValue()).build());
        if (hasScale)
            for (Map.Entry<String, Float> option : sizeScales.entrySet())
                options.add(option.getKey(), ToolingJson.object().put("scale", option.getValue()).build());

        // Default = the base size (the one of small/medium/large that carries no option).
        String defaultSize = "medium";
        for (String candidate : new String[]{"small", "medium", "large"})
            if (!options.has(candidate)) { defaultSize = candidate; break; }
        attachAxis(family, "size", axis(defaultSize, values("small", "medium", "large"), options));
    }

    /**
     * Adds an option-gated dyed-collar {@code layer} to a family that carries a {@code *CollarLayer}
     * (wolf, cat). The collar reuses the family's body geometry, references the collar texture, and
     * is tinted at render time from the {@code collar_color} option; the {@code when state=tame}
     * gate documents vanilla's condition (the renderer realises it as "shown when a collar colour
     * is supplied"). Additive - the flattener ignores {@code layers}, so the round-trip is unchanged.
     */
    private static void attachCollarLayer(@NotNull String familyId, @NotNull JsonObject family, @Nullable Map<String, String> collarByEntity) {
        if (collarByEntity == null) return;
        String collarTexture = collarByEntity.get(familyId);
        if (collarTexture == null) return;

        JsonObject overlay = ToolingJson.object()
            .put("geometry_ref", family.get("geometry_ref").getAsString())
            .put("texture_ref", collarTexture)
            .put("tint_by", "collar_color")
            .build();
        appendLayer(family, layer("collar", when("state", "tame"), overlay));
    }

    /**
     * Adds one option-gated equipment {@code layer} per {@code SimpleEquipmentLayer} the family's
     * base renderer attaches (pig/horse/camel/strider/happy_ghast/nautilus saddle; horse/nautilus
     * body armor). Each layer carries its own baked {@code geometry_ref} (the {@code _SADDLE}/
     * {@code _ARMOR} mesh) and a {@code texture_template} whose {@code <material>} is filled at render
     * from the equipment axis (defaulting to the slot's {@code default_material} - {@code saddle} or
     * {@code leather}). The layer is gated on the equipment {@code slot}; the default (unequipped)
     * render draws none. Additive - the flattener reads equipment layers only when the equipment axis
     * is set, so the round-trip and unequipped renders are unchanged.
     *
     * @param familyId the family id (equipment attaches to the base entity's family)
     * @param family the family entry to attach the equipment layers to
     * @param equipmentByEntity base entity id -&gt; resolved equipment overlays
     * @param equipmentGeometryByField equipment {@code ModelLayers} field -&gt; baked geometry id
     * @param diagnostics the diagnostic sink for unresolved-geometry warnings
     */
    private static void attachEquipmentLayers(
        @NotNull String familyId,
        @NotNull JsonObject family,
        @Nullable Map<String, ConcurrentList<EntityEquipmentResolver.Result>> equipmentByEntity,
        @Nullable Map<String, String> equipmentGeometryByField,
        @NotNull Diagnostics diagnostics
    ) {
        if (equipmentByEntity == null || equipmentGeometryByField == null) return;
        ConcurrentList<EntityEquipmentResolver.Result> equipment = equipmentByEntity.get(familyId);
        if (equipment == null || equipment.isEmpty()) return;

        for (EntityEquipmentResolver.Result desc : equipment) {
            String geometryId = equipmentGeometryByField.get(desc.modelLayerField());
            if (geometryId == null) {
                diagnostics.info("equipment layer '%s' geometry ModelLayers.%s unresolved - skipped", familyId, desc.modelLayerField());
                continue;
            }
            JsonObject overlay = ToolingJson.object()
                .put("geometry_ref", geometryId)
                .put("texture_template", "equipment/" + desc.layerSubdir() + "/<material>")
                .put("default_material", desc.defaultAsset())
                .build();
            appendLayer(family, layer(desc.slot(), when("equipment", desc.slot()), overlay));
        }
    }

    /**
     * Builds a variant-family entry: shared {@code geometry_ref} / {@code armor_type} / carried
     * base fields, plus an id-encoded {@code variant} axis whose options each carry their texture
     * (and a {@code geometry_ref} override only when it differs from the family default).
     */
    private static @NotNull JsonObject variantFamily(
        @NotNull String baseId,
        @NotNull List<String> children,
        @NotNull JsonObject entities,
        @NotNull JsonObject crossFamilies,
        @Nullable ConcurrentMap<String, ConcurrentList<EntityVariantResolver.Result>> variants,
        @NotNull Diagnostics diagnostics
    ) {
        List<String> members = new ArrayList<>();
        members.add(baseId);
        members.addAll(children);
        String familyId = familyStem(baseId, children, diagnostics);
        JsonObject baseRow = entities.getAsJsonObject(baseId);

        JsonObject family = new JsonObject();
        String familyGeometry = baseRow.get("geometry_ref").getAsString();
        family.addProperty("geometry_ref", familyGeometry);
        family.addProperty("armor_type", baseRow.get("armor_type").getAsString());
        copyBaseOptionalFields(baseRow, family);

        JsonObject options = new JsonObject();
        for (String member : members) {
            JsonObject memberRow = entities.getAsJsonObject(member);
            JsonObject option = new JsonObject();
            JsonObject textures = new JsonObject();
            if (memberRow.has("texture_ref")) textures.add("wild", memberRow.get("texture_ref").deepCopy());
            option.add("textures", textures);
            String memberGeometry = memberRow.get("geometry_ref").getAsString();
            if (!memberGeometry.equals(familyGeometry)) option.addProperty("geometry_ref", memberGeometry);
            options.add(optionOf(member, familyId, diagnostics), option);
        }

        JsonObject variantAxis = idEncodedAxis(optionOf(baseId, familyId, diagnostics), keysOf(options), options);
        JsonObject axes = new JsonObject();
        axes.add("variant", variantAxis);
        enrichStateAxis(familyId, options, axes, variants, diagnostics);
        enrichBabyTextures(familyId, options, variants);

        attachFamilyOf(familyId, crossFamilies, family);
        family.add("axes", axes);
        return family;
    }

    /**
     * Adds a {@code state} axis (default {@code wild}) to a variant family whose variants declare
     * per-state textures (wolf: {@code wild}/{@code tame}/{@code angry} from the multi-asset
     * variant table). Each variant option's {@code textures} map is enriched with its non-wild
     * states, leaving the flat-derived {@code wild} untouched so the round-trip stays exact.
     * Single-asset families (whose textures key on {@code primary}) get no state axis.
     */
    private static void enrichStateAxis(
        @NotNull String familyId,
        @NotNull JsonObject options,
        @NotNull JsonObject axes,
        @Nullable ConcurrentMap<String, ConcurrentList<EntityVariantResolver.Result>> variants,
        @NotNull Diagnostics diagnostics
    ) {
        if (variants == null) return;
        String stem = familyId.startsWith("minecraft:") ? familyId.substring("minecraft:".length()) : familyId;
        ConcurrentList<EntityVariantResolver.Result> variantList = variants.get(stem);
        if (variantList == null || variantList.isEmpty()) return;

        Set<String> stateKeys = new LinkedHashSet<>();
        for (EntityVariantResolver.Result variant : variantList)
            for (String key : variant.textures().keySet())
                if (!key.equals("primary")) stateKeys.add(key);
        boolean hasNonWildState = stateKeys.stream().anyMatch(key -> !key.equals("wild"));
        if (!hasNonWildState) return;

        for (EntityVariantResolver.Result variant : variantList) {
            if (!options.has(variant.variantId())) continue;
            JsonObject textures = options.getAsJsonObject(variant.variantId()).getAsJsonObject("textures");
            for (Map.Entry<String, String> texture : variant.textures().entrySet()) {
                String state = texture.getKey();
                if (state.equals("primary") || state.equals("wild")) continue;
                if (!textures.has(state)) textures.addProperty(state, EntityTextureResolver.stripPrefix(texture.getValue()));
            }
        }

        // The state axis is a pure selector enumeration - every option body is empty (the real
        // per-state textures live in each variant option's textures map, enriched above). Under the
        // uniform axis contract it still carries the full domain under "values" plus an empty
        // "options" map (no state has a standalone body).
        JsonArray stateValues = new JsonArray();
        stateValues.add("wild");
        for (String key : stateKeys) if (!key.equals("wild")) stateValues.add(key);
        axes.add("state", axis("wild", stateValues, new JsonObject()));
        diagnostics.info("state axis: '%s' -> %s", familyId, stateKeys);
    }

    /**
     * Adds each variant option's per-variant baby texture (from the variant table's
     * {@code baby_asset_id} / {@code baby_assets}) into the option's {@code textures} map under the
     * {@code baby} key, so the {@code age=baby} render binds the matching {@code <variant>_baby}
     * texture (the baby mesh has its own UV layout / resolution and does not map onto the adult
     * texture). Reuses the state-texture side-channel; the flattener still reads only
     * {@code textures.wild}, so the round-trip is unchanged.
     */
    private static void enrichBabyTextures(
        @NotNull String familyId,
        @NotNull JsonObject options,
        @Nullable ConcurrentMap<String, ConcurrentList<EntityVariantResolver.Result>> variants
    ) {
        if (variants == null) return;
        String stem = familyId.startsWith("minecraft:") ? familyId.substring("minecraft:".length()) : familyId;
        ConcurrentList<EntityVariantResolver.Result> variantList = variants.get(stem);
        if (variantList == null) return;
        for (EntityVariantResolver.Result variant : variantList) {
            if (!options.has(variant.variantId())) continue;
            String babyTexture = variant.primaryBabyTexturePath();
            if (babyTexture == null) continue;
            JsonObject textures = options.getAsJsonObject(variant.variantId()).getAsJsonObject("textures");
            if (!textures.has("baby")) textures.addProperty("baby", EntityTextureResolver.stripPrefix(babyTexture));
        }
    }

    /**
     * Builds a plain single-row family entry (no id-encoded axis), keeping {@code texture_ref} at
     * the family level and carrying the same optional base fields.
     */
    private static @NotNull JsonObject plainFamily(@NotNull String id, @NotNull JsonObject row, @NotNull JsonObject crossFamilies) {
        JsonObject family = new JsonObject();
        family.addProperty("geometry_ref", row.get("geometry_ref").getAsString());
        family.addProperty("armor_type", row.get("armor_type").getAsString());
        if (row.has("texture_ref")) family.add("texture_ref", row.get("texture_ref").deepCopy());
        copyBaseOptionalFields(row, family);
        attachFamilyOf(id, crossFamilies, family);
        return family;
    }

    /**
     * Copies the optional base fields ({@code renderer_scale}, {@code setup_yaw_addend},
     * {@code base_tint}, {@code hidden_bones}, {@code overlays}, {@code block_overlays}) verbatim
     * from a flat row onto a family entry, preserving their exact JSON representation.
     */
    private static void copyBaseOptionalFields(@NotNull JsonObject row, @NotNull JsonObject family) {
        for (String key : List.of("renderer_scale", "setup_yaw_addend", "base_tint", "hidden_bones", "bone_toggles", "overlays", "block_overlays"))
            if (row.has(key)) family.add(key, row.get(key).deepCopy());
    }

    /**
     * Copies a {@code family_of} link onto the family entry when the cross-entity table names this
     * family id as a derivative.
     */
    private static void attachFamilyOf(@NotNull String familyId, @NotNull JsonObject crossFamilies, @NotNull JsonObject family) {
        if (crossFamilies.has(familyId)) family.addProperty("family_of", crossFamilies.get(familyId).getAsString());
    }

    /**
     * Derives the family id (stem) shared by a variant base and its children as the longest common
     * prefix trimmed back to an underscore boundary (e.g. {@code minecraft:wolf_pale} +
     * {@code minecraft:wolf_ashen} -&gt; {@code minecraft:wolf}).
     */
    private static @NotNull String familyStem(@NotNull String baseId, @NotNull List<String> children, @NotNull Diagnostics diagnostics) {
        String prefix = baseId;
        for (String child : children) prefix = commonPrefix(prefix, child);
        int lastUnderscore = prefix.lastIndexOf('_');
        if (lastUnderscore < 0) {
            diagnostics.warn("variant family for '%s' has no underscore-delimited stem - using '%s'", baseId, prefix);
            return prefix;
        }
        return prefix.substring(0, lastUnderscore);
    }

    /**
     * Extracts the variant option name from a member id relative to its family stem
     * ({@code minecraft:wolf_ashen} rel {@code minecraft:wolf} -&gt; {@code ashen}).
     */
    private static @NotNull String optionOf(@NotNull String memberId, @NotNull String familyId, @NotNull Diagnostics diagnostics) {
        String expectedPrefix = familyId + "_";
        if (!memberId.startsWith(expectedPrefix)) {
            diagnostics.warn("variant member '%s' does not start with family stem '%s'", memberId, expectedPrefix);
            return memberId;
        }
        return memberId.substring(expectedPrefix.length());
    }

    /**
     * Builds an axis' {@code values} enumeration (the full ordered option domain) from an
     * {@code options} map's key order. Used by the variant axis, where every option carries a body
     * so the domain equals the option-key set.
     */
    private static @NotNull JsonArray keysOf(@NotNull JsonObject options) {
        JsonArray values = new JsonArray();
        for (String key : options.keySet()) values.add(key);
        return values;
    }

    /**
     * Returns the longest common character prefix of two strings.
     */
    private static @NotNull String commonPrefix(@NotNull String a, @NotNull String b) {
        int limit = Math.min(a.length(), b.length());
        int i = 0;
        while (i < limit && a.charAt(i) == b.charAt(i)) i++;
        return a.substring(0, i);
    }

    // ----------------------------------------------------------------------------------------
    // Shared family-shape factories - the axis / layer / gate vocabulary of entity_models.json.
    // Kept local (not in tooling.util) because the shapes are this schema's, not generic JSON.
    // ----------------------------------------------------------------------------------------

    /**
     * Builds an axis in the shared {@code {default, values, options}} shape (age / shape / state).
     *
     * @param defaultValue the axis default option
     * @param values the full ordered option domain
     * @param options the per-option bodies
     * @return the axis object
     */
    private static @NotNull JsonObject axis(@NotNull String defaultValue, @NotNull JsonArray values, @NotNull JsonObject options) {
        JsonObject result = new JsonObject();
        result.addProperty("default", defaultValue);
        result.add("values", values);
        result.add("options", options);
        return result;
    }

    /**
     * Builds the id-encoded variant axis - an {@code id_encoded} flag before the shared
     * {@code {default, values, options}} members.
     *
     * @param defaultValue the axis default option
     * @param values the full ordered option domain
     * @param options the per-option bodies
     * @return the id-encoded axis object
     */
    private static @NotNull JsonObject idEncodedAxis(@NotNull String defaultValue, @NotNull JsonArray values, @NotNull JsonObject options) {
        JsonObject result = new JsonObject();
        result.addProperty("id_encoded", true);
        result.addProperty("default", defaultValue);
        result.add("values", values);
        result.add("options", options);
        return result;
    }

    /**
     * Builds a JSON string array from the given values in order.
     *
     * @param vs the string values
     * @return the array
     */
    private static @NotNull JsonArray values(@NotNull String... vs) {
        JsonArray array = new JsonArray();
        for (String v : vs) array.add(v);
        return array;
    }

    /**
     * Builds a single-member {@code when} gate ({@code {<key>: <value>}}).
     *
     * @param key the gate key ({@code state} / {@code equipment})
     * @param value the gate value
     * @return the gate object
     */
    private static @NotNull JsonObject when(@NotNull String key, @NotNull String value) {
        JsonObject result = new JsonObject();
        result.addProperty(key, value);
        return result;
    }

    /**
     * Builds a conditional overlay {@code layer} in the shared {@code {id, when, overlay}} shape.
     *
     * @param id the layer id
     * @param when the option gate
     * @param overlay the overlay body
     * @return the layer object
     */
    private static @NotNull JsonObject layer(@NotNull String id, @NotNull JsonObject when, @NotNull JsonObject overlay) {
        JsonObject result = new JsonObject();
        result.addProperty("id", id);
        result.add("when", when);
        result.add("overlay", overlay);
        return result;
    }

    /**
     * Attaches an axis to a family under {@code name}, creating the family's {@code axes} object on
     * first use and reusing it thereafter (the age / shape merge dance).
     *
     * @param family the family entry
     * @param name the axis name
     * @param axis the axis object
     */
    private static void attachAxis(@NotNull JsonObject family, @NotNull String name, @NotNull JsonObject axis) {
        JsonObject axes = family.has("axes") ? family.getAsJsonObject("axes") : new JsonObject();
        axes.add(name, axis);
        if (!family.has("axes")) family.add("axes", axes);
    }

    /**
     * Appends a layer to a family's {@code layers} array, creating it on first use and reusing it
     * thereafter (collar attaches first, equipment appends after).
     *
     * @param family the family entry
     * @param layer the layer to append
     */
    private static void appendLayer(@NotNull JsonObject family, @NotNull JsonObject layer) {
        JsonArray layers = family.has("layers") ? family.getAsJsonArray("layers") : new JsonArray();
        layers.add(layer);
        if (!family.has("layers")) family.add("layers", layers);
    }
}
