package lib.minecraft.renderer.tooling.entity;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import dev.simplified.collection.ConcurrentList;
import dev.simplified.collection.ConcurrentMap;
import dev.simplified.gson.GsonSettings;
import lib.minecraft.renderer.tooling.util.Diagnostics;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Emits {@code entity_models2.json}, the normalized family form of {@code entity_models.json}.
 *
 * <p>Runs as a post-pass over the flat file {@link EntityRuntimeJsonWriter} has just written:
 * it reads that known-good output back and re-groups it into one entry per base entity. The
 * flat {@code <id>_<variant>} rows collapse into a single family carrying a {@code variant}
 * axis, and the cross-entity {@code families} table collapses into per-family {@code family_of}
 * links. No field value is ever reparsed - every carried value ({@code texture_ref},
 * {@code overlays}, {@code base_tint}, {@code renderer_scale}, ...) is copied as a verbatim
 * {@code JsonElement} deep-copy, so only the grouping structure changes.
 *
 * <p>The transform is the inverse of {@code EntityFamilyFlattener.flattenV2}; the pair is pinned
 * by {@code EntityModelsV2RoundTripTest} (flatten of this output equals the flat input). See
 * {@code notes/entity-family-schema.md} for the schema contract and {@code notes/sample_model.json}
 * for the wolf worked example.
 */
@UtilityClass
public final class EntityFamilyJsonWriter {

    /**
     * Normalized family-form output path, written alongside {@code entity_models.json} during
     * the {@code entityModels} tooling run. Not yet read at runtime (see Phase 4 of the plan).
     */
    public static final @NotNull Path OUTPUT =
        Path.of("src/main/resources/lib/minecraft/renderer/entity_models2.json");

    /**
     * Shared pretty-printing Gson, matching {@link EntityRuntimeJsonWriter}'s settings so both
     * files format identically.
     */
    private static final @NotNull Gson PRETTY_GSON =
        GsonSettings.defaults().mutate().isPrettyPrint().isHtmlEscaping(false).build().create();

    /**
     * Reads the flat {@code entity_models.json} that {@link EntityRuntimeJsonWriter} has already
     * written, groups it into the family form, and writes {@code entity_models2.json}.
     *
     * @param diagnostics the diagnostic sink for the summary line
     * @param variants variant stem -&gt; resolved variant list, used to enrich variant families with
     *     forward-looking option axes (e.g. wolf {@code wild}/{@code tame}/{@code angry} state
     *     textures) that the flat v1 file discards
     * @throws IOException when the flat input cannot be read or the family output cannot be written
     */
    public static void writeAll(
        @NotNull Diagnostics diagnostics,
        @NotNull ConcurrentMap<String, ConcurrentList<EntityVariantResolver.Result>> variants
    ) throws IOException {
        String text = Files.readString(EntityRuntimeJsonWriter.MODELS_OUTPUT);
        JsonObject root = JsonParser.parseString(text).getAsJsonObject();
        JsonObject entities = root.getAsJsonObject("entities");
        JsonObject crossFamilies = root.has("families") ? root.getAsJsonObject("families") : new JsonObject();

        JsonObject families = group(entities, crossFamilies, variants, diagnostics);

        JsonObject out = new JsonObject();
        out.addProperty("//", "Generated by ToolingEntityModels (EntityFamilyJsonWriter). Normalized family form of entity_models.json: one entry per base entity, id-encoded colour variants folded into a variant axis, cross-entity groupings as family_of. Flattened back to the runtime shape by EntityFamilyFlattener.");
        out.add("families", families);

        Files.createDirectories(OUTPUT.getParent());
        Files.writeString(OUTPUT, PRETTY_GSON.toJson(out) + System.lineSeparator());
        diagnostics.info("entity_models2.json: %d families", families.size());
    }

    /**
     * Groups a flat {@code entities} object into the family form. Package-private so
     * {@code EntityModelsV2RoundTripTest} can drive it on fixtures without touching the filesystem.
     *
     * <p>Each flat row is either a variant child (has {@code variant_of} - consumed under its
     * base), a variant base (targeted by some {@code variant_of} - heads a {@code variant} axis),
     * or a plain entity (its own single-row family). Family order follows the flat file's head
     * order.
     *
     * @param entities the flat {@code entities} object (id -&gt; row)
     * @param crossFamilies the flat {@code families} table (derivative id -&gt; family root)
     * @param variants variant stem -&gt; resolved variant list for option-axis enrichment (may be
     *     {@code null} to skip enrichment)
     * @param diagnostics the diagnostic sink for structural warnings
     * @return the {@code families} object of the family form (family id -&gt; family entry)
     */
    static @NotNull JsonObject group(
        @NotNull JsonObject entities,
        @NotNull JsonObject crossFamilies,
        @Nullable ConcurrentMap<String, ConcurrentList<EntityVariantResolver.Result>> variants,
        @NotNull Diagnostics diagnostics
    ) {
        Map<String, List<String>> childrenOf = new LinkedHashMap<>();
        for (Map.Entry<String, JsonElement> entry : entities.entrySet()) {
            if (!entry.getValue().isJsonObject()) continue;
            JsonObject row = entry.getValue().getAsJsonObject();
            if (row.has("variant_of"))
                childrenOf.computeIfAbsent(row.get("variant_of").getAsString(), k -> new ArrayList<>()).add(entry.getKey());
        }

        JsonObject families = new JsonObject();
        for (Map.Entry<String, JsonElement> entry : entities.entrySet()) {
            if (!entry.getValue().isJsonObject()) continue;
            String id = entry.getKey();
            JsonObject row = entry.getValue().getAsJsonObject();
            if (row.has("variant_of")) continue;

            if (childrenOf.containsKey(id))
                families.add(familyStem(id, childrenOf.get(id), diagnostics),
                    variantFamily(id, childrenOf.get(id), entities, crossFamilies, variants, diagnostics));
            else
                families.add(id, plainFamily(id, row, crossFamilies));
        }
        return families;
    }

    /**
     * Builds a variant-family entry: shared {@code geometry_ref} / {@code armor_type} / carried
     * base fields, plus an id-encoded {@code variant} axis whose options each carry their texture
     * (and a {@code geometry_ref} override only when it differs from the family default).
     */
    private static @NotNull JsonObject variantFamily(
        @NotNull String baseId,
        @NotNull List<String> children,
        @NotNull JsonObject entities,
        @NotNull JsonObject crossFamilies,
        @Nullable ConcurrentMap<String, ConcurrentList<EntityVariantResolver.Result>> variants,
        @NotNull Diagnostics diagnostics
    ) {
        List<String> members = new ArrayList<>();
        members.add(baseId);
        members.addAll(children);
        String familyId = familyStem(baseId, children, diagnostics);
        JsonObject baseRow = entities.getAsJsonObject(baseId);

        JsonObject family = new JsonObject();
        String familyGeometry = baseRow.get("geometry_ref").getAsString();
        family.addProperty("geometry_ref", familyGeometry);
        family.addProperty("armor_type", baseRow.get("armor_type").getAsString());
        copyBaseOptionalFields(baseRow, family);

        JsonObject options = new JsonObject();
        for (String member : members) {
            JsonObject memberRow = entities.getAsJsonObject(member);
            JsonObject option = new JsonObject();
            JsonObject textures = new JsonObject();
            if (memberRow.has("texture_ref")) textures.add("wild", memberRow.get("texture_ref").deepCopy());
            option.add("textures", textures);
            String memberGeometry = memberRow.get("geometry_ref").getAsString();
            if (!memberGeometry.equals(familyGeometry)) option.addProperty("geometry_ref", memberGeometry);
            options.add(optionOf(member, familyId, diagnostics), option);
        }

        JsonObject axis = new JsonObject();
        axis.addProperty("id_encoded", true);
        axis.addProperty("default", optionOf(baseId, familyId, diagnostics));
        axis.add("options", options);
        JsonObject axes = new JsonObject();
        axes.add("variant", axis);
        enrichStateAxis(familyId, options, axes, variants, diagnostics);

        attachFamilyOf(familyId, crossFamilies, family);
        family.add("axes", axes);
        return family;
    }

    /**
     * Adds a {@code state} axis (default {@code wild}) to a variant family whose variants declare
     * per-state textures (wolf: {@code wild}/{@code tame}/{@code angry} from the multi-asset
     * variant table). Each variant option's {@code textures} map is enriched with its non-wild
     * states, leaving the flat-derived {@code wild} untouched so the round-trip stays exact.
     * Single-asset families (whose textures key on {@code primary}) get no state axis.
     */
    private static void enrichStateAxis(
        @NotNull String familyId,
        @NotNull JsonObject options,
        @NotNull JsonObject axes,
        @Nullable ConcurrentMap<String, ConcurrentList<EntityVariantResolver.Result>> variants,
        @NotNull Diagnostics diagnostics
    ) {
        if (variants == null) return;
        String stem = familyId.startsWith("minecraft:") ? familyId.substring("minecraft:".length()) : familyId;
        ConcurrentList<EntityVariantResolver.Result> variantList = variants.get(stem);
        if (variantList == null || variantList.isEmpty()) return;

        Set<String> stateKeys = new LinkedHashSet<>();
        for (EntityVariantResolver.Result variant : variantList)
            for (String key : variant.textures().keySet())
                if (!key.equals("primary")) stateKeys.add(key);
        boolean hasNonWildState = stateKeys.stream().anyMatch(key -> !key.equals("wild"));
        if (!hasNonWildState) return;

        for (EntityVariantResolver.Result variant : variantList) {
            if (!options.has(variant.variantId())) continue;
            JsonObject textures = options.getAsJsonObject(variant.variantId()).getAsJsonObject("textures");
            for (Map.Entry<String, String> texture : variant.textures().entrySet()) {
                String state = texture.getKey();
                if (state.equals("primary") || state.equals("wild")) continue;
                if (!textures.has(state)) textures.addProperty(state, EntityTextureResolver.stripPrefix(texture.getValue()));
            }
        }

        JsonObject stateOptions = new JsonObject();
        stateOptions.add("wild", new JsonObject());
        for (String key : stateKeys) if (!key.equals("wild")) stateOptions.add(key, new JsonObject());
        JsonObject stateAxis = new JsonObject();
        stateAxis.addProperty("default", "wild");
        stateAxis.add("options", stateOptions);
        axes.add("state", stateAxis);
        diagnostics.info("state axis: '%s' -> %s", familyId, stateKeys);
    }

    /**
     * Builds a plain single-row family entry (no id-encoded axis), keeping {@code texture_ref} at
     * the family level and carrying the same optional base fields.
     */
    private static @NotNull JsonObject plainFamily(@NotNull String id, @NotNull JsonObject row, @NotNull JsonObject crossFamilies) {
        JsonObject family = new JsonObject();
        family.addProperty("geometry_ref", row.get("geometry_ref").getAsString());
        family.addProperty("armor_type", row.get("armor_type").getAsString());
        if (row.has("texture_ref")) family.add("texture_ref", row.get("texture_ref").deepCopy());
        copyBaseOptionalFields(row, family);
        attachFamilyOf(id, crossFamilies, family);
        return family;
    }

    /**
     * Copies the optional base fields ({@code renderer_scale}, {@code setup_yaw_addend},
     * {@code base_tint}, {@code hidden_bones}, {@code overlays}, {@code block_overlays}) verbatim
     * from a flat row onto a family entry, preserving their exact JSON representation.
     */
    private static void copyBaseOptionalFields(@NotNull JsonObject row, @NotNull JsonObject family) {
        for (String key : List.of("renderer_scale", "setup_yaw_addend", "base_tint", "hidden_bones", "overlays", "block_overlays"))
            if (row.has(key)) family.add(key, row.get(key).deepCopy());
    }

    /**
     * Copies a {@code family_of} link onto the family entry when the cross-entity table names this
     * family id as a derivative.
     */
    private static void attachFamilyOf(@NotNull String familyId, @NotNull JsonObject crossFamilies, @NotNull JsonObject family) {
        if (crossFamilies.has(familyId)) family.addProperty("family_of", crossFamilies.get(familyId).getAsString());
    }

    /**
     * Derives the family id (stem) shared by a variant base and its children as the longest common
     * prefix trimmed back to an underscore boundary (e.g. {@code minecraft:wolf_pale} +
     * {@code minecraft:wolf_ashen} -&gt; {@code minecraft:wolf}).
     */
    private static @NotNull String familyStem(@NotNull String baseId, @NotNull List<String> children, @NotNull Diagnostics diagnostics) {
        String prefix = baseId;
        for (String child : children) prefix = commonPrefix(prefix, child);
        int lastUnderscore = prefix.lastIndexOf('_');
        if (lastUnderscore < 0) {
            diagnostics.warn("variant family for '%s' has no underscore-delimited stem - using '%s'", baseId, prefix);
            return prefix;
        }
        return prefix.substring(0, lastUnderscore);
    }

    /**
     * Extracts the variant option name from a member id relative to its family stem
     * ({@code minecraft:wolf_ashen} rel {@code minecraft:wolf} -&gt; {@code ashen}).
     */
    private static @NotNull String optionOf(@NotNull String memberId, @NotNull String familyId, @NotNull Diagnostics diagnostics) {
        String expectedPrefix = familyId + "_";
        if (!memberId.startsWith(expectedPrefix)) {
            diagnostics.warn("variant member '%s' does not start with family stem '%s'", memberId, expectedPrefix);
            return memberId;
        }
        return memberId.substring(expectedPrefix.length());
    }

    /**
     * Returns the longest common character prefix of two strings.
     */
    private static @NotNull String commonPrefix(@NotNull String a, @NotNull String b) {
        int limit = Math.min(a.length(), b.length());
        int i = 0;
        while (i < limit && a.charAt(i) == b.charAt(i)) i++;
        return a.substring(0, i);
    }
}
