package dev.sbs.renderer.tooling;

import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import dev.sbs.renderer.exception.AssetPipelineException;
import dev.sbs.renderer.pipeline.AssetPipelineOptions;
import dev.sbs.renderer.pipeline.client.ClientJarDownloader;
import dev.sbs.renderer.pipeline.client.HttpFetcher;
import dev.sbs.renderer.pipeline.loader.BlockEntityModelLoader;
import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentList;
import dev.simplified.collection.ConcurrentMap;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.FieldInsnNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.IntInsnNode;
import org.objectweb.asm.tree.LdcInsnNode;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

/**
 * Entry point invoked by the {@code generateBlockEntityModels} Gradle task.
 * <p>
 * Downloads the deobfuscated Minecraft client jar, parses block entity model classes via
 * {@link Parser}, and writes the result to
 * {@code src/main/resources/renderer/block_entity_models.json}. The runtime pipeline reads
 * the JSON via {@link dev.sbs.renderer.pipeline.loader.BlockEntityModelLoader}.
 */
@UtilityClass
public final class ToolingBlockEntityModels {

    private static final @NotNull Path OUTPUT_PATH = Path.of("src/main/resources/renderer/block_entity_models.json");
    private static final @NotNull Path BLOCK_MODEL_OUTPUT_PATH = Path.of("src/main/resources/renderer/block_entity_block_models.json");

    public static void main(String @NotNull [] args) throws IOException {
        AssetPipelineOptions options = AssetPipelineOptions.defaults();
        Path jarPath = ClientJarDownloader.download(options, new HttpFetcher());

        System.out.println("Parsing block entity models from client jar...");
        ConcurrentMap<String, JsonObject> models = Parser.parse(jarPath);
        System.out.printf("Extracted %d block entity models%n", models.size());

        Files.createDirectories(OUTPUT_PATH.getParent());
        Files.writeString(OUTPUT_PATH, buildJson(models, options.getVersion()));
        System.out.println("Wrote " + OUTPUT_PATH.toAbsolutePath());

        // NEW: also output block model elements format
        JsonObject blockModels = BlockModelConverter.convert(models);
        Files.writeString(BLOCK_MODEL_OUTPUT_PATH,
            new GsonBuilder().setPrettyPrinting().create().toJson(blockModels) + System.lineSeparator());
        System.out.println("Wrote block model conversion: " + BLOCK_MODEL_OUTPUT_PATH.toAbsolutePath());
    }

    private static @NotNull String buildJson(@NotNull ConcurrentMap<String, JsonObject> models, @NotNull String mcVersion) {
        JsonObject root = new JsonObject();
        root.addProperty("//", "Generated by ToolingBlockEntityModels. From net.minecraft.client.**.class$*Layer/Mesh(). Run the tooling/blockEntityModels Gradle task to refresh. Block-to-model wiring lives in block_entity_mappings.json (hand-edited).");
        root.addProperty("source_version", mcVersion);

        JsonObject modelsObj = new JsonObject();
        models.entrySet()
            .stream()
            .sorted(Map.Entry.comparingByKey())
            .forEach(entry -> modelsObj.add(entry.getKey(), entry.getValue()));
        root.add("models", modelsObj);

        return new GsonBuilder().setPrettyPrinting().create().toJson(root) + System.lineSeparator();
    }

    /**
     * An ASM bytecode walker that extracts block entity model geometry from the deobfuscated
     * Minecraft 26.1 client jar. Parses the {@code createSingleBodyLayer()} / {@code createBodyLayer()}
     * methods of model classes to extract cube definitions, UV offsets, pivot points, and texture
     * dimensions into {@code EntityModelData}-compatible JSON.
     * <p>
     * The parser tracks a numeric literal stack and recognises the builder-chain pattern used by
     * vanilla model classes:
     * <pre><code>
     * root.addOrReplaceChild("name",
     *     CubeListBuilder.create().texOffs(u, v).addBox(x, y, z, w, h, d),
     *     PartPose.offset(px, py, pz));
     * </code></pre>
     * Each {@code addOrReplaceChild} call emits a bone with its cubes. The texture dimensions are
     * extracted from the final {@code LayerDefinition.create(mesh, texW, texH)} call.
     *
     * @see BlockEntityModelLoader
     */
    @UtilityClass
    static class Parser {

        private static final @NotNull String CUBE_LIST_BUILDER = "net/minecraft/client/model/geom/builders/CubeListBuilder";
        private static final @NotNull String PART_POSE = "net/minecraft/client/model/geom/PartPose";
        private static final @NotNull String PART_DEFINITION = "net/minecraft/client/model/geom/builders/PartDefinition";
        private static final @NotNull String LAYER_DEFINITION = "net/minecraft/client/model/geom/builders/LayerDefinition";

        /**
         * Block entity model sources: class entry path, method name, output entity id, and the
         * source's Y axis convention. Methods that take parameters (like
         * {@code createFlagLayer(boolean)}) are parsed with default values - conditional branches
         * are ignored (first path taken).
         * <p>
         * Most Java {@code ModelPart}-derived block entities are Y-down (standard mob-style
         * convention - a vertex with the smallest Y points at the highest spot on the model).
         * A few block-native models, notably {@code ChestModel}, author their cubes in Y-up
         * block-space directly; those are marked {@link YAxis#UP} so the parser post-processes
         * them back into the canonical Y-down form before emission.
         */
        private static final @NotNull List<Source> SOURCES = List.of(
            // ChestModel is authored in Y-up block-space (positive Y is up) rather than the
            // Y-down ModelPart convention used elsewhere - the lid sits at y=9..14 and the body
            // at y=0..10 in the raw data, which is how the chest block looks when rendered.
            // {@code ChestRenderer} yaws the rendering by {@code -NORTH.toYRot() = 180} to face
            // the lock toward the camera; that pose is carried through as {@code inventoryYRotation}.
            new Source("net/minecraft/client/model/object/chest/ChestModel.class", "createSingleBodyLayer", "minecraft:chest", YAxis.UP, 180f),
            new Source("net/minecraft/client/model/object/banner/BannerFlagModel.class", "createFlagLayer", "minecraft:banner", YAxis.DOWN, 0f),
            new Source("net/minecraft/client/renderer/blockentity/BedRenderer.class", "createHeadLayer", "minecraft:bed_head", YAxis.DOWN, 0f),
            new Source("net/minecraft/client/renderer/blockentity/BedRenderer.class", "createFootLayer", "minecraft:bed_foot", YAxis.DOWN, 0f),
            new Source("net/minecraft/client/model/monster/shulker/ShulkerModel.class", "createShellMesh", "minecraft:shulker_box", YAxis.DOWN, 0f),
            new Source("net/minecraft/client/renderer/blockentity/StandingSignRenderer.class", "createSignLayer", "minecraft:sign", YAxis.DOWN, 0f),
            new Source("net/minecraft/client/renderer/blockentity/HangingSignRenderer.class", "createHangingSignLayer", "minecraft:hanging_sign", YAxis.DOWN, 0f),
            new Source("net/minecraft/client/renderer/blockentity/ConduitRenderer.class", "createShellLayer", "minecraft:conduit", YAxis.DOWN, 0f),

            // DecoratedPotRenderer.createBaseLayer is the main pot geometry (foot + belly + neck
            // + top rim). The createSidesLayer produces separate quads for the sherd decorations
            // - skipped for the atlas icon because it requires per-face pattern lookups we do
            // not model here; the base layer by itself shows a recognisable empty pot.
            new Source("net/minecraft/client/renderer/blockentity/DecoratedPotRenderer.class", "createBaseLayer", "minecraft:decorated_pot", YAxis.DOWN, 0f),

            // CopperGolemStatueBlockRenderer bakes four Copper Golem poses
            // (COPPER_GOLEM / _RUNNING / _SITTING / _STAR from ModelLayers); picks one per
            // blockstate pose at runtime. For the atlas we pick COPPER_GOLEM (the default
            // standing pose) via CopperGolemModel.createBodyLayer - same geometry as the
            // copper golem mob, just rendered as a static block.
            new Source("net/minecraft/client/model/animal/golem/CopperGolemModel.class", "createBodyLayer", "minecraft:copper_golem_statue", YAxis.DOWN, 0f)
        );

        /** The Y axis orientation used by a Java block entity model's source data. */
        private enum YAxis { UP, DOWN }

        private record Source(
            @NotNull String classEntry,
            @NotNull String methodName,
            @NotNull String entityId,
            @NotNull YAxis yAxis,
            float inventoryYRotation
        ) {}

        /**
         * Parses all known block entity model classes from the supplied client jar and returns
         * the extracted models as serialised JSON objects keyed by entity id.
         *
         * @param jarPath the deobfuscated client jar (MC 26.1+)
         * @return a map of entity id to model JSON
         */
        public static @NotNull ConcurrentMap<String, JsonObject> parse(@NotNull Path jarPath) {
            ConcurrentMap<String, JsonObject> results = Concurrent.newMap();

            try (ZipFile zip = new ZipFile(jarPath.toFile())) {
                for (Source source : SOURCES) {
                    ZipEntry entry = zip.getEntry(source.classEntry);
                    if (entry == null) {
                        System.err.printf("  skipped %s: class not found in jar%n", source.entityId);
                        continue;
                    }

                    try (InputStream stream = zip.getInputStream(entry)) {
                        byte[] classBytes = stream.readAllBytes();
                        ClassNode classNode = new ClassNode();
                        new ClassReader(classBytes).accept(classNode, ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);

                        MethodNode method = classNode.methods.stream()
                            .filter(m -> m.name.equals(source.methodName))
                            .findFirst()
                            .orElse(null);

                        if (method == null) {
                            System.err.printf("  skipped %s: method '%s' not found%n", source.entityId, source.methodName);
                            continue;
                        }

                        JsonObject model = parseLayerMethod(method.instructions);
                        if (model != null) {
                            if (source.yAxis == YAxis.UP)
                                flipToYDown(model);
                            model.addProperty("y_axis", source.yAxis.name());
                            if (source.inventoryYRotation != 0f)
                                model.addProperty("inventory_y_rotation", source.inventoryYRotation);
                            results.put(source.entityId, model);
                        }

                    } catch (Exception ex) {
                        System.err.printf("  skipped %s: %s%n", source.entityId, ex.getMessage());
                    }
                }
            } catch (IOException ex) {
                throw new AssetPipelineException(ex, "Failed to read client jar '%s'", jarPath);
            }

            return results;
        }

        /**
         * Post-processes a Y-up block entity model into the canonical Y-down form. For each
         * bone, negates the pivot's Y so the {@code PartPose} offset flips into the Y-down
         * frame; for each cube, mirrors the {@code origin.y} about the pivot's XZ plane. Because
         * {@code origin} is the <b>min</b> corner and {@code size} is an unsigned extent, the
         * new min Y is the negated former max: {@code origin.y = -origin.y - size.y}. X, Z, and
         * size are unaffected.
         */
        private static void flipToYDown(@NotNull JsonObject model) {
            JsonObject bones = model.getAsJsonObject("bones");
            if (bones == null) return;

            for (Map.Entry<String, JsonElement> entry : bones.entrySet()) {
                JsonObject bone = entry.getValue().getAsJsonObject();

                JsonArray pivot = bone.getAsJsonArray("pivot");
                if (pivot != null && pivot.size() == 3)
                    pivot.set(1, new JsonPrimitive(-pivot.get(1).getAsFloat()));

                JsonArray cubes = bone.getAsJsonArray("cubes");
                if (cubes == null) continue;

                for (JsonElement cubeElement : cubes) {
                    JsonObject cube = cubeElement.getAsJsonObject();
                    JsonArray origin = cube.getAsJsonArray("origin");
                    JsonArray size = cube.getAsJsonArray("size");
                    if (origin == null || size == null || origin.size() != 3 || size.size() != 3)
                        continue;

                    float oy = origin.get(1).getAsFloat();
                    float sy = size.get(1).getAsFloat();
                    origin.set(1, new JsonPrimitive(-oy - sy));
                }
            }
        }

        /**
         * Parses a single layer-creation method's bytecode and extracts the model geometry.
         */
        private static @Nullable JsonObject parseLayerMethod(@NotNull InsnList instructions) {
            ConcurrentList<Number> numStack = Concurrent.newList();
            @Nullable String pendingPartName = null;
            int pendingTexU = 0;
            int pendingTexV = 0;

            // Per-cube state (accumulated across texOffs + addBox chains)
            ConcurrentList<float[]> pendingCubes = Concurrent.newList();
            int[] pendingUv = {0, 0};

            // Per-part state
            float[] pendingPivot = {0, 0, 0};
            float[] pendingRotation = {0, 0, 0};

            // Accumulated parts
            JsonObject bones = new JsonObject();
            int texWidth = 64;
            int texHeight = 64;

            for (AbstractInsnNode node = instructions.getFirst(); node != null; node = node.getNext()) {
                // Track numeric literals
                Number literal = readNumericLiteral(node);
                if (literal != null) {
                    numStack.add(literal);
                    if (numStack.size() > 12)
                        numStack.removeFirst();
                    continue;
                }

                int opcode = node.getOpcode();

                switch (node) {
                    case FieldInsnNode fieldInsn when opcode == Opcodes.GETSTATIC -> {
                        if (fieldInsn.owner.equals(PART_POSE) && fieldInsn.name.equals("ZERO")) {
                            pendingPivot = new float[]{ 0, 0, 0 };
                            pendingRotation = new float[]{ 0, 0, 0 };
                        }
                    }
                    case MethodInsnNode methodInsn -> {
                        if (methodInsn.owner.equals(CUBE_LIST_BUILDER)) {
                            if (methodInsn.name.equals("texOffs") && methodInsn.desc.startsWith("(II")) {
                                pendingUv[1] = popInt(numStack);
                                pendingUv[0] = popInt(numStack);
                            } else if (methodInsn.name.equals("addBox") && methodInsn.desc.startsWith("(FFFFFF")) {
                                float d = popFloat(numStack);
                                float h = popFloat(numStack);
                                float w = popFloat(numStack);
                                float z = popFloat(numStack);
                                float y = popFloat(numStack);
                                float x = popFloat(numStack);
                                pendingCubes.add(new float[]{ x, y, z, w, h, d, pendingUv[0], pendingUv[1] });
                            }
                        } else if (methodInsn.owner.equals(PART_POSE)) {
                            if (methodInsn.name.equals("offset") && methodInsn.desc.startsWith("(FFF")) {
                                float pz = popFloat(numStack);
                                float py = popFloat(numStack);
                                float px = popFloat(numStack);
                                pendingPivot = new float[]{ px, py, pz };
                                pendingRotation = new float[]{ 0, 0, 0 };
                            } else if (methodInsn.name.equals("rotation") && methodInsn.desc.startsWith("(FFF")) {
                                // PartPose.rotation(rx, ry, rz) — rotation only, pivot stays at origin.
                                // Used by BedRenderer legs.
                                float rz = popFloat(numStack);
                                float ry = popFloat(numStack);
                                float rx = popFloat(numStack);
                                pendingPivot = new float[]{ 0, 0, 0 };
                                pendingRotation = new float[]{
                                    (float) Math.toDegrees(rx),
                                    (float) Math.toDegrees(ry),
                                    (float) Math.toDegrees(rz)
                                };
                            } else if (methodInsn.name.equals("offsetAndRotation") && methodInsn.desc.startsWith("(FFFFFF")) {
                                float rz = popFloat(numStack);
                                float ry = popFloat(numStack);
                                float rx = popFloat(numStack);
                                float pz = popFloat(numStack);
                                float py = popFloat(numStack);
                                float px = popFloat(numStack);
                                pendingPivot = new float[]{ px, py, pz };
                                pendingRotation = new float[]{
                                    (float) Math.toDegrees(rx),
                                    (float) Math.toDegrees(ry),
                                    (float) Math.toDegrees(rz)
                                };
                            }
                        } else if (methodInsn.owner.equals(PART_DEFINITION) && methodInsn.name.equals("addOrReplaceChild")) {
                            // The part name was pushed as an ldc String before the CubeListBuilder chain.
                            // Find it by scanning backward from numStack context.
                            if (pendingPartName != null && !pendingCubes.isEmpty()) {
                                bones.add(pendingPartName, buildBone(pendingPivot, pendingRotation, pendingCubes));
                            }
                            pendingPartName = null;
                            pendingCubes = Concurrent.newList();
                            pendingPivot = new float[]{ 0, 0, 0 };
                            pendingRotation = new float[]{ 0, 0, 0 };
                            pendingUv = new int[]{ 0, 0 };
                        } else if (methodInsn.owner.equals(LAYER_DEFINITION) && methodInsn.name.equals("create")) {
                            texHeight = popInt(numStack);
                            texWidth = popInt(numStack);
                        }
                    }
                    case LdcInsnNode ldc when ldc.cst instanceof String s ->
                        // Track the last string literal as potential part name
                        pendingPartName = s;
                    default -> { }
                }
            }

            if (bones.isEmpty()) return null;

            JsonObject model = new JsonObject();
            model.addProperty("textureWidth", texWidth);
            model.addProperty("textureHeight", texHeight);
            model.add("bones", bones);
            return model;
        }

        private static @NotNull JsonObject buildBone(float @NotNull [] pivot, float @NotNull [] rotation, @NotNull ConcurrentList<float[]> cubes) {
            JsonObject bone = new JsonObject();
            bone.add("pivot", floatArray(pivot));
            bone.add("rotation", floatArray(rotation));

            JsonArray cubeArray = new JsonArray();
            for (float[] c : cubes) {
                JsonObject cube = new JsonObject();
                cube.add("origin", floatArray(c[0], c[1], c[2]));
                cube.add("size", floatArray(c[3], c[4], c[5]));

                JsonArray uv = new JsonArray();
                uv.add((int) c[6]);
                uv.add((int) c[7]);
                cube.add("uv", uv);

                cube.addProperty("inflate", 0.0);
                cube.addProperty("mirror", false);
                cube.add("face_uv", new JsonObject());
                cubeArray.add(cube);
            }
            bone.add("cubes", cubeArray);
            return bone;
        }

        private static @NotNull JsonArray floatArray(float @NotNull ... values) {
            JsonArray arr = new JsonArray();
            for (float v : values) arr.add(v);
            return arr;
        }

        private static @Nullable Number readNumericLiteral(@NotNull AbstractInsnNode node) {
            int opcode = node.getOpcode();

            // iconst_m1 through iconst_5
            if (opcode >= Opcodes.ICONST_M1 && opcode <= Opcodes.ICONST_5)
                return opcode - Opcodes.ICONST_0;

            // fconst_0 through fconst_2
            if (opcode >= Opcodes.FCONST_0 && opcode <= Opcodes.FCONST_2)
                return (float) (opcode - Opcodes.FCONST_0);

            // bipush, sipush
            if ((opcode == Opcodes.BIPUSH || opcode == Opcodes.SIPUSH) && node instanceof IntInsnNode intInsn)
                return intInsn.operand;

            // ldc int or float
            if (opcode == Opcodes.LDC && node instanceof LdcInsnNode ldc) {
                if (ldc.cst instanceof Integer || ldc.cst instanceof Float)
                    return (Number) ldc.cst;
            }

            return null;
        }

        private static int popInt(@NotNull ConcurrentList<Number> stack) {
            if (stack.isEmpty()) return 0;
            return stack.remove(stack.size() - 1).intValue();
        }

        private static float popFloat(@NotNull ConcurrentList<Number> stack) {
            if (stack.isEmpty()) return 0f;
            return stack.remove(stack.size() - 1).floatValue();
        }

    }

    /**
     * Converts parsed entity model JSON (bones/cubes with box UV) into block model elements
     * JSON (from/to/faces with per-face UV).
     * <p>
     * The conversion is fully derived from the vanilla {@code ModelPart$Cube} polygon layout:
     * each cube produces eight corner positions in entity space, paired with the per-vertex UVs
     * vanilla assigns to each of the six entity faces (the per-vertex UV map is fixed by
     * {@code ModelPart$Polygon}'s vertex-to-UV order). The full transform chain
     * (bone rotation + pivot + inventory transform, or a Y-flip when no inventory transform is
     * present) is applied to the eight corners; the resulting axis-aligned block-space face is
     * resolved by snapping the transformed face normal to the closest cardinal direction. Each
     * surviving entity face emits a single block face whose UV rectangle and rotation tag are
     * derived from where {@code (uMin, vMin)} lands among the block face's TL/BL/BR/TR corners.
     * <p>
     * No per-face direction tables or hardcoded rotations are required - the algorithm handles
     * arbitrary axis-aligned rotations of bones and inventory transforms uniformly.
     */
    @UtilityClass
    static class BlockModelConverter {

        /**
         * Vanilla inventory transforms per model type. Each transform is applied to the
         * model-space cube corners (in Y-down model units) before converting to Y-up block
         * model format. Values extracted from vanilla BedRenderer.createModelTransform and
         * ChestRenderer bytecode.
         */
        private static final java.util.Map<String, float[]> INVENTORY_TRANSFORMS = java.util.Map.of(
            // BedRenderer: translate(0, 9, 0) * Rx(90°) in model units
            "minecraft:bed_head", new float[]{ 0, 9, 0, 90, 0, 0 },
            "minecraft:bed_foot", new float[]{ 0, 9, 0, 90, 0, 0 }
        );

        /** Names of the six block-model face directions, indexed by {@link Face#ordinal}. */
        private static final String[] BLOCK_FACE_NAMES = { "down", "up", "north", "south", "west", "east" };

        /** Outward unit normals for the six block-model face directions. */
        private static final int[][] BLOCK_FACE_NORMALS = {
            { 0, -1, 0 },  // down
            { 0,  1, 0 },  // up
            { 0, 0, -1 },  // north
            { 0, 0,  1 },  // south
            { -1, 0, 0 },  // west
            {  1, 0, 0 }   // east
        };

        /**
         * Converts all parsed entity models into a JSON object containing block model elements
         * keyed by entity model id.
         */
        static @NotNull JsonObject convert(@NotNull ConcurrentMap<String, JsonObject> entityModels) {
            JsonObject result = new JsonObject();
            result.addProperty("//", "Generated block model elements from entity model geometry. Run tooling/blockEntityModels to refresh.");

            for (Map.Entry<String, JsonObject> entry : entityModels.entrySet()) {
                String modelId = entry.getKey();
                JsonObject entityModel = entry.getValue();

                int texW = entityModel.has("textureWidth") ? entityModel.get("textureWidth").getAsInt() : 64;
                int texH = entityModel.has("textureHeight") ? entityModel.get("textureHeight").getAsInt() : 64;

                JsonObject bones = entityModel.getAsJsonObject("bones");
                if (bones == null) continue;

                float[] invTransform = INVENTORY_TRANSFORMS.get(modelId);
                boolean hasInvTransform = invTransform != null;

                JsonArray elements = new JsonArray();
                for (Map.Entry<String, JsonElement> boneEntry : bones.entrySet()) {
                    JsonObject bone = boneEntry.getValue().getAsJsonObject();
                    JsonArray pivotArr = bone.getAsJsonArray("pivot");
                    float px = pivotArr != null ? pivotArr.get(0).getAsFloat() : 0f;
                    float py = pivotArr != null ? pivotArr.get(1).getAsFloat() : 0f;
                    float pz = pivotArr != null ? pivotArr.get(2).getAsFloat() : 0f;

                    JsonArray cubes = bone.getAsJsonArray("cubes");
                    if (cubes == null) continue;

                    JsonArray rotArr = bone.getAsJsonArray("rotation");
                    float brx = 0, bry = 0, brz = 0;
                    if (rotArr != null && rotArr.size() == 3) {
                        brx = rotArr.get(0).getAsFloat();
                        bry = rotArr.get(1).getAsFloat();
                        brz = rotArr.get(2).getAsFloat();
                    }
                    boolean hasBoneRot = brx != 0 || bry != 0 || brz != 0;

                    // Bone rotation matrix: Rz * Ry * Rx (matches vanilla's Quaternionf.rotationZYX,
                    // which applies X first, then Y, then Z).
                    double rxR = Math.toRadians(brx), ryR = Math.toRadians(bry), rzR = Math.toRadians(brz);
                    double[][] mRx = {{ 1, 0, 0 }, { 0, Math.cos(rxR), -Math.sin(rxR) }, { 0, Math.sin(rxR), Math.cos(rxR) }};
                    double[][] mRy = {{ Math.cos(ryR), 0, Math.sin(ryR) }, { 0, 1, 0 }, { -Math.sin(ryR), 0, Math.cos(ryR) }};
                    double[][] mRz = {{ Math.cos(rzR), -Math.sin(rzR), 0 }, { Math.sin(rzR), Math.cos(rzR), 0 }, { 0, 0, 1 }};
                    double[][] boneRot = hasBoneRot ? matMul3(matMul3(mRz, mRy), mRx) : null;

                    for (JsonElement cubeEl : cubes) {
                        JsonObject cube = cubeEl.getAsJsonObject();
                        JsonArray originArr = cube.getAsJsonArray("origin");
                        JsonArray sizeArr = cube.getAsJsonArray("size");
                        int u = cube.getAsJsonArray("uv").get(0).getAsInt();
                        int v = cube.getAsJsonArray("uv").get(1).getAsInt();

                        float ox = originArr.get(0).getAsFloat();
                        float oy = originArr.get(1).getAsFloat();
                        float oz = originArr.get(2).getAsFloat();
                        float sw = sizeArr.get(0).getAsFloat();
                        float sh = sizeArr.get(1).getAsFloat();
                        float sd = sizeArr.get(2).getAsFloat();

                        elements.add(buildElement(
                            ox, oy, oz, sw, sh, sd, u, v,
                            boneRot, px, py, pz,
                            invTransform, hasInvTransform,
                            texW
                        ));
                    }
                }

                JsonObject modelOutput = new JsonObject();
                modelOutput.addProperty("textureWidth", texW);
                modelOutput.addProperty("textureHeight", texH);
                modelOutput.add("elements", elements);
                result.add(modelId, modelOutput);
            }

            return result;
        }

        /**
         * Builds the eight entity-space corners (matching vanilla {@code ModelPart$Cube}'s vertex
         * ordering v19..v26), pushes them through the bone + inventory transform chain, then emits
         * a block element by mapping each entity face to a block face via per-vertex UV tracking.
         */
        private static @NotNull JsonObject buildElement(
            float ox, float oy, float oz,
            float sw, float sh, float sd,
            int u, int v,
            double @org.jetbrains.annotations.Nullable [][] boneRot,
            float px, float py, float pz,
            float @org.jetbrains.annotations.Nullable [] invTransform,
            boolean hasInvTransform,
            int texW
        ) {
            // Vanilla v19..v26 layout: bit pattern (xMax?, yMax?, zMax?) selecting one of 8 corners.
            // The order below matches the offsets the vanilla bytecode assigns to v19..v26.
            float[][] entityCorners = {
                { ox,        oy,        oz        },  // 0 = v19 (-x,-y,-z)
                { ox + sw,   oy,        oz        },  // 1 = v20 (+x,-y,-z)
                { ox + sw,   oy + sh,   oz        },  // 2 = v21 (+x,+y,-z)
                { ox,        oy + sh,   oz        },  // 3 = v22 (-x,+y,-z)
                { ox,        oy,        oz + sd   },  // 4 = v23 (-x,-y,+z)
                { ox + sw,   oy,        oz + sd   },  // 5 = v24 (+x,-y,+z)
                { ox + sw,   oy + sh,   oz + sd   },  // 6 = v25 (+x,+y,+z)
                { ox,        oy + sh,   oz + sd   }   // 7 = v26 (-x,+y,+z)
            };

            float[][] blockCorners = new float[8][3];
            for (int i = 0; i < 8; i++)
                blockCorners[i] = applyTransform(entityCorners[i], boneRot, px, py, pz, invTransform, hasInvTransform);

            float minX = Float.MAX_VALUE, minY = Float.MAX_VALUE, minZ = Float.MAX_VALUE;
            float maxX = -Float.MAX_VALUE, maxY = -Float.MAX_VALUE, maxZ = -Float.MAX_VALUE;
            for (float[] c : blockCorners) {
                minX = Math.min(minX, c[0]); maxX = Math.max(maxX, c[0]);
                minY = Math.min(minY, c[1]); maxY = Math.max(maxY, c[1]);
                minZ = Math.min(minZ, c[2]); maxZ = Math.max(maxZ, c[2]);
            }

            // Vanilla per-face vertex order and UV rectangle. Per Polygon constructor:
            // vertex[0] gets (u1, v0), vertex[1] gets (u0, v0), vertex[2] gets (u0, v1),
            // vertex[3] gets (u1, v1).
            float scale = 16.0f / texW;
            EntityFace[] entityFaces = {
                // DOWN: vertices v24, v23, v19, v20; UV (u+d, v, u+d+w, v+d)
                new EntityFace(new int[]{ 5, 4, 0, 1 }, (u + sd) * scale, v * scale, (u + sd + sw) * scale, (v + sd) * scale),
                // UP: vertices v21, v22, v26, v25; UV (u+d+w, v+d, u+d+w+w, v) - note v0 > v1
                new EntityFace(new int[]{ 2, 3, 7, 6 }, (u + sd + sw) * scale, (v + sd) * scale, (u + sd + sw + sw) * scale, v * scale),
                // NORTH: vertices v20, v19, v22, v21; UV (u+d, v+d, u+d+w, v+d+h)
                new EntityFace(new int[]{ 1, 0, 3, 2 }, (u + sd) * scale, (v + sd) * scale, (u + sd + sw) * scale, (v + sd + sh) * scale),
                // SOUTH: vertices v23, v24, v25, v26; UV (u+d+w+d, v+d, u+d+w+d+w, v+d+h)
                new EntityFace(new int[]{ 4, 5, 6, 7 }, (u + sd + sw + sd) * scale, (v + sd) * scale, (u + sd + sw + sd + sw) * scale, (v + sd + sh) * scale),
                // WEST: vertices v19, v23, v26, v22; UV (u, v+d, u+d, v+d+h)
                new EntityFace(new int[]{ 0, 4, 7, 3 }, u * scale, (v + sd) * scale, (u + sd) * scale, (v + sd + sh) * scale),
                // EAST: vertices v24, v20, v21, v25; UV (u+d+w, v+d, u+d+w+d, v+d+h)
                new EntityFace(new int[]{ 5, 1, 2, 6 }, (u + sd + sw) * scale, (v + sd) * scale, (u + sd + sw + sd) * scale, (v + sd + sh) * scale)
            };

            JsonObject faces = new JsonObject();
            for (EntityFace face : entityFaces)
                emitBlockFace(face, blockCorners, minX, minY, minZ, maxX, maxY, maxZ, faces);

            JsonObject element = new JsonObject();
            JsonArray from = new JsonArray(); from.add(round2(minX)); from.add(round2(minY)); from.add(round2(minZ));
            JsonArray to = new JsonArray(); to.add(round2(maxX)); to.add(round2(maxY)); to.add(round2(maxZ));
            element.add("from", from);
            element.add("to", to);
            element.add("faces", faces);
            return element;
        }

        /**
         * Determines which block face the four transformed vertices of an entity face land on,
         * matches them to that block face's TL/BL/BR/TR corners (per
         * {@link dev.sbs.renderer.geometry.BlockFace}'s vertex-index conventions), and emits a
         * single block face entry whose UV rectangle and rotation tag reproduce the per-vertex UVs.
         */
        private static void emitBlockFace(
            @NotNull EntityFace face,
            float @NotNull [] @NotNull [] blockCorners,
            float minX, float minY, float minZ,
            float maxX, float maxY, float maxZ,
            @NotNull JsonObject facesOut
        ) {
            float[] p0 = blockCorners[face.vertexIndices[0]];
            float[] p1 = blockCorners[face.vertexIndices[1]];
            float[] p2 = blockCorners[face.vertexIndices[2]];
            float[] p3 = blockCorners[face.vertexIndices[3]];

            // Cross product of two edges gives the face normal.
            float[] e1 = { p1[0] - p0[0], p1[1] - p0[1], p1[2] - p0[2] };
            float[] e2 = { p3[0] - p0[0], p3[1] - p0[1], p3[2] - p0[2] };
            float[] normal = {
                e1[1] * e2[2] - e1[2] * e2[1],
                e1[2] * e2[0] - e1[0] * e2[2],
                e1[0] * e2[1] - e1[1] * e2[0]
            };

            int blockFaceIdx = snapToCardinal(normal);
            String blockFaceName = BLOCK_FACE_NAMES[blockFaceIdx];

            // Block-face TL/BL/BR/TR positions, matching BlockFace.corners(...) for this bbox.
            float[][] blockFaceCorners = blockFaceCornersOf(blockFaceIdx, minX, minY, minZ, maxX, maxY, maxZ);

            // For each transformed vertex of the entity face, look up the (uMin/uMax, vMin/vMax)
            // it carries (per the four-corner UV order: v[0]→(u1,v0), v[1]→(u0,v0), v[2]→(u0,v1), v[3]→(u1,v1)),
            // then attach that UV to whichever block-face corner the vertex landed at.
            float[][] entityFaceUv = {
                { face.u1, face.v0 },
                { face.u0, face.v0 },
                { face.u0, face.v1 },
                { face.u1, face.v1 }
            };
            float[][] blockCornerUv = new float[4][2];
            float[][] entityFacePos = { p0, p1, p2, p3 };
            for (int i = 0; i < 4; i++) {
                int blockCorner = matchCorner(entityFacePos[i], blockFaceCorners);
                blockCornerUv[blockCorner] = entityFaceUv[i];
            }

            // The four UVs at TL/BL/BR/TR form one of D4's eight orientations of a UV rectangle.
            // For each candidate rotation R in {0, 90, 180, 270}, undo R by cyclic-shifting back
            // (the "old" canonical corners). If the undone corners satisfy vanilla's uvCorners
            // shape (TL/BL share u, TR/BR share u, TL/TR share v, BL/BR share v), the rotation
            // is correct - emit (u0=TL_old.u, v0=TL_old.v, u1=BR_old.u, v1=BR_old.v) and tag.
            // Implicit u/v flips are handled by allowing u0 > u1 or v0 > v1 in the output.
            int rotation = 0;
            float u0 = 0, v0 = 0, u1 = 0, v1 = 0;
            for (int r = 0; r < 4; r++) {
                float[] tlOld = blockCornerUv[(0 - r + 4) % 4];
                float[] blOld = blockCornerUv[(1 - r + 4) % 4];
                float[] brOld = blockCornerUv[(2 - r + 4) % 4];
                float[] trOld = blockCornerUv[(3 - r + 4) % 4];
                if (approxEqual(tlOld[0], blOld[0]) && approxEqual(trOld[0], brOld[0])
                    && approxEqual(tlOld[1], trOld[1]) && approxEqual(blOld[1], brOld[1])) {
                    u0 = tlOld[0]; v0 = tlOld[1]; u1 = brOld[0]; v1 = brOld[1];
                    rotation = r * 90;
                    break;
                }
            }

            JsonObject blockFace = new JsonObject();
            blockFace.addProperty("texture", "#entity");
            JsonArray uvArr = new JsonArray();
            uvArr.add(round2(u0)); uvArr.add(round2(v0)); uvArr.add(round2(u1)); uvArr.add(round2(v1));
            blockFace.add("uv", uvArr);
            if (rotation != 0) blockFace.addProperty("rotation", rotation);
            facesOut.add(blockFaceName, blockFace);
        }

        /** Applies bone rotation, pivot, then either the inventory transform or a Y-flip. */
        private static float @NotNull [] applyTransform(
            float @NotNull [] entityCorner,
            double @org.jetbrains.annotations.Nullable [][] boneRot,
            float px, float py, float pz,
            float @org.jetbrains.annotations.Nullable [] invTransform,
            boolean hasInvTransform
        ) {
            float cx = entityCorner[0], cy = entityCorner[1], cz = entityCorner[2];

            if (boneRot != null) {
                double rx2 = boneRot[0][0]*cx + boneRot[0][1]*cy + boneRot[0][2]*cz;
                double ry2 = boneRot[1][0]*cx + boneRot[1][1]*cy + boneRot[1][2]*cz;
                double rz2 = boneRot[2][0]*cx + boneRot[2][1]*cy + boneRot[2][2]*cz;
                cx = (float) rx2; cy = (float) ry2; cz = (float) rz2;
            }

            cx += px; cy += py; cz += pz;

            if (hasInvTransform) {
                float pitch = (float) Math.toRadians(invTransform[3]);
                float cosP = (float) Math.cos(pitch), sinP = (float) Math.sin(pitch);
                float ry = cy * cosP - cz * sinP;
                float rz = cy * sinP + cz * cosP;
                cy = ry + invTransform[1];
                cz = rz + invTransform[2];
                cx += invTransform[0];
            } else {
                cy = -cy;
            }

            return new float[]{ cx, cy, cz };
        }

        /** Returns the index into {@link #BLOCK_FACE_NORMALS} closest to the given normal. */
        private static int snapToCardinal(float @NotNull [] normal) {
            float absX = Math.abs(normal[0]);
            float absY = Math.abs(normal[1]);
            float absZ = Math.abs(normal[2]);
            if (absY >= absX && absY >= absZ) return normal[1] > 0 ? 1 : 0;
            if (absZ >= absX) return normal[2] > 0 ? 3 : 2;
            return normal[0] > 0 ? 5 : 4;
        }

        /**
         * Returns the four TL, BL, BR, TR corner positions for a block face on the given bbox,
         * matching the vertex-index order used by {@link dev.sbs.renderer.geometry.BlockFace}.
         */
        private static float[][] blockFaceCornersOf(int faceIdx, float x0, float y0, float z0, float x1, float y1, float z1) {
            return switch (faceIdx) {
                case 0 -> new float[][]{                   // DOWN: indices 4, 0, 1, 5
                    { x0, y0, z1 }, { x0, y0, z0 }, { x1, y0, z0 }, { x1, y0, z1 }
                };
                case 1 -> new float[][]{                   // UP: indices 3, 7, 6, 2
                    { x0, y1, z0 }, { x0, y1, z1 }, { x1, y1, z1 }, { x1, y1, z0 }
                };
                case 2 -> new float[][]{                   // NORTH: indices 2, 1, 0, 3
                    { x1, y1, z0 }, { x1, y0, z0 }, { x0, y0, z0 }, { x0, y1, z0 }
                };
                case 3 -> new float[][]{                   // SOUTH: indices 7, 4, 5, 6
                    { x0, y1, z1 }, { x0, y0, z1 }, { x1, y0, z1 }, { x1, y1, z1 }
                };
                case 4 -> new float[][]{                   // WEST: indices 3, 0, 4, 7
                    { x0, y1, z0 }, { x0, y0, z0 }, { x0, y0, z1 }, { x0, y1, z1 }
                };
                default -> new float[][]{                  // EAST: indices 6, 5, 1, 2
                    { x1, y1, z1 }, { x1, y0, z1 }, { x1, y0, z0 }, { x1, y1, z0 }
                };
            };
        }

        /** Returns the index (0=TL, 1=BL, 2=BR, 3=TR) of {@code blockFaceCorners} closest to {@code position}. */
        private static int matchCorner(float @NotNull [] position, float @NotNull [] @NotNull [] blockFaceCorners) {
            int best = 0;
            float bestDist = Float.MAX_VALUE;
            for (int i = 0; i < 4; i++) {
                float dx = position[0] - blockFaceCorners[i][0];
                float dy = position[1] - blockFaceCorners[i][1];
                float dz = position[2] - blockFaceCorners[i][2];
                float dist = dx * dx + dy * dy + dz * dz;
                if (dist < bestDist) { bestDist = dist; best = i; }
            }
            return best;
        }

        private static boolean approxEqual(float a, float b) {
            return Math.abs(a - b) < 1e-4f;
        }

        private static double[][] matMul3(double[][] a, double[][] b) {
            double[][] r = new double[3][3];
            for (int i = 0; i < 3; i++)
                for (int j = 0; j < 3; j++)
                    r[i][j] = a[i][0] * b[0][j] + a[i][1] * b[1][j] + a[i][2] * b[2][j];
            return r;
        }

        private static float round2(double v) {
            return (float) (Math.round(v * 100.0) / 100.0);
        }

        /**
         * One of the six entity faces of a cube: the four vertex indices into the eight-corner
         * layout {@code v19..v26} (re-indexed 0..7), and the four UV-rectangle edges. The four
         * UVs assigned to {@code (u1, v0), (u0, v0), (u0, v1), (u1, v1)} are paired with the
         * four vertices in the order vanilla's {@code Polygon} constructor uses.
         */
        private record EntityFace(int @NotNull [] vertexIndices, float u0, float v0, float u1, float v1) {}

    }

}
