package dev.sbs.renderer.tooling;

import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import dev.sbs.renderer.exception.AssetPipelineException;
import dev.sbs.renderer.pipeline.AssetPipelineOptions;
import dev.sbs.renderer.pipeline.client.ClientJarDownloader;
import dev.sbs.renderer.pipeline.client.HttpFetcher;
import dev.sbs.renderer.pipeline.loader.BlockEntityModelLoader;
import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentList;
import dev.simplified.collection.ConcurrentMap;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.FieldInsnNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.IntInsnNode;
import org.objectweb.asm.tree.LdcInsnNode;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

/**
 * Entry point invoked by the {@code generateBlockEntityModels} Gradle task.
 * <p>
 * Downloads the deobfuscated Minecraft client jar, parses block entity model classes via
 * {@link Parser}, and writes the result to
 * {@code src/main/resources/renderer/block_entity_models.json}. The runtime pipeline reads
 * the JSON via {@link dev.sbs.renderer.pipeline.loader.BlockEntityModelLoader}.
 */
@UtilityClass
public final class ToolingBlockEntityModels {

    private static final @NotNull Path OUTPUT_PATH = Path.of("src/main/resources/renderer/block_entity_models.json");
    private static final @NotNull Path BLOCK_MODEL_OUTPUT_PATH = Path.of("src/main/resources/renderer/block_entity_block_models.json");

    public static void main(String @NotNull [] args) throws IOException {
        AssetPipelineOptions options = AssetPipelineOptions.defaults();
        Path jarPath = ClientJarDownloader.download(options, new HttpFetcher());

        System.out.println("Parsing block entity models from client jar...");
        ConcurrentMap<String, JsonObject> models = Parser.parse(jarPath);
        System.out.printf("Extracted %d block entity models%n", models.size());

        Files.createDirectories(OUTPUT_PATH.getParent());
        Files.writeString(OUTPUT_PATH, buildJson(models, options.getVersion()));
        System.out.println("Wrote " + OUTPUT_PATH.toAbsolutePath());

        // NEW: also output block model elements format
        JsonObject blockModels = BlockModelConverter.convert(models);
        Files.writeString(BLOCK_MODEL_OUTPUT_PATH,
            new GsonBuilder().setPrettyPrinting().create().toJson(blockModels) + System.lineSeparator());
        System.out.println("Wrote block model conversion: " + BLOCK_MODEL_OUTPUT_PATH.toAbsolutePath());
    }

    private static @NotNull String buildJson(@NotNull ConcurrentMap<String, JsonObject> models, @NotNull String mcVersion) {
        JsonObject root = new JsonObject();
        root.addProperty("//", "Generated by ToolingBlockEntityModels. From net.minecraft.client.**.class$*Layer/Mesh(). Run the tooling/blockEntityModels Gradle task to refresh. Block-to-model wiring lives in block_entity_mappings.json (hand-edited).");
        root.addProperty("source_version", mcVersion);

        JsonObject modelsObj = new JsonObject();
        models.entrySet()
            .stream()
            .sorted(Map.Entry.comparingByKey())
            .forEach(entry -> modelsObj.add(entry.getKey(), entry.getValue()));
        root.add("models", modelsObj);

        return new GsonBuilder().setPrettyPrinting().create().toJson(root) + System.lineSeparator();
    }

    /**
     * An ASM bytecode walker that extracts block entity model geometry from the deobfuscated
     * Minecraft 26.1 client jar. Parses the {@code createSingleBodyLayer()} / {@code createBodyLayer()}
     * methods of model classes to extract cube definitions, UV offsets, pivot points, and texture
     * dimensions into {@code EntityModelData}-compatible JSON.
     * <p>
     * The parser tracks a numeric literal stack and recognises the builder-chain pattern used by
     * vanilla model classes:
     * <pre><code>
     * root.addOrReplaceChild("name",
     *     CubeListBuilder.create().texOffs(u, v).addBox(x, y, z, w, h, d),
     *     PartPose.offset(px, py, pz));
     * </code></pre>
     * Each {@code addOrReplaceChild} call emits a bone with its cubes. The texture dimensions are
     * extracted from the final {@code LayerDefinition.create(mesh, texW, texH)} call.
     *
     * @see BlockEntityModelLoader
     */
    @UtilityClass
    static class Parser {

        private static final @NotNull String CUBE_LIST_BUILDER = "net/minecraft/client/model/geom/builders/CubeListBuilder";
        private static final @NotNull String PART_POSE = "net/minecraft/client/model/geom/PartPose";
        private static final @NotNull String PART_DEFINITION = "net/minecraft/client/model/geom/builders/PartDefinition";
        private static final @NotNull String LAYER_DEFINITION = "net/minecraft/client/model/geom/builders/LayerDefinition";

        /**
         * Block entity model sources: class entry path, method name, output entity id, and the
         * source's Y axis convention. Methods that take parameters (like
         * {@code createFlagLayer(boolean)}) are parsed with default values - conditional branches
         * are ignored (first path taken).
         * <p>
         * Most Java {@code ModelPart}-derived block entities are Y-down (standard mob-style
         * convention - a vertex with the smallest Y points at the highest spot on the model).
         * A few block-native models, notably {@code ChestModel}, author their cubes in Y-up
         * block-space directly; those are marked {@link YAxis#UP} so the parser post-processes
         * them back into the canonical Y-down form before emission.
         */
        private static final @NotNull List<Source> SOURCES = List.of(
            // ChestModel is authored in Y-up block-space (positive Y is up) rather than the
            // Y-down ModelPart convention used elsewhere - the lid sits at y=9..14 and the body
            // at y=0..10 in the raw data, which is how the chest block looks when rendered.
            // {@code ChestRenderer} yaws the rendering by {@code -NORTH.toYRot() = 180} to face
            // the lock toward the camera; that pose is carried through as {@code inventoryYRotation}.
            new Source("net/minecraft/client/model/object/chest/ChestModel.class", "createSingleBodyLayer", "minecraft:chest", YAxis.UP, 180f),
            new Source("net/minecraft/client/model/object/banner/BannerFlagModel.class", "createFlagLayer", "minecraft:banner", YAxis.DOWN, 0f),
            new Source("net/minecraft/client/renderer/blockentity/BedRenderer.class", "createHeadLayer", "minecraft:bed_head", YAxis.DOWN, 0f),
            new Source("net/minecraft/client/renderer/blockentity/BedRenderer.class", "createFootLayer", "minecraft:bed_foot", YAxis.DOWN, 0f),
            new Source("net/minecraft/client/model/monster/shulker/ShulkerModel.class", "createShellMesh", "minecraft:shulker_box", YAxis.DOWN, 0f),
            new Source("net/minecraft/client/renderer/blockentity/StandingSignRenderer.class", "createSignLayer", "minecraft:sign", YAxis.DOWN, 0f),
            new Source("net/minecraft/client/renderer/blockentity/HangingSignRenderer.class", "createHangingSignLayer", "minecraft:hanging_sign", YAxis.DOWN, 0f),
            new Source("net/minecraft/client/renderer/blockentity/ConduitRenderer.class", "createShellLayer", "minecraft:conduit", YAxis.DOWN, 0f),

            // DecoratedPotRenderer.createBaseLayer is the main pot geometry (foot + belly + neck
            // + top rim). The createSidesLayer produces separate quads for the sherd decorations
            // - skipped for the atlas icon because it requires per-face pattern lookups we do
            // not model here; the base layer by itself shows a recognisable empty pot.
            new Source("net/minecraft/client/renderer/blockentity/DecoratedPotRenderer.class", "createBaseLayer", "minecraft:decorated_pot", YAxis.DOWN, 0f),

            // CopperGolemStatueBlockRenderer bakes four Copper Golem poses
            // (COPPER_GOLEM / _RUNNING / _SITTING / _STAR from ModelLayers); picks one per
            // blockstate pose at runtime. For the atlas we pick COPPER_GOLEM (the default
            // standing pose) via CopperGolemModel.createBodyLayer - same geometry as the
            // copper golem mob, just rendered as a static block.
            new Source("net/minecraft/client/model/animal/golem/CopperGolemModel.class", "createBodyLayer", "minecraft:copper_golem_statue", YAxis.DOWN, 0f)
        );

        /** The Y axis orientation used by a Java block entity model's source data. */
        private enum YAxis { UP, DOWN }

        private record Source(
            @NotNull String classEntry,
            @NotNull String methodName,
            @NotNull String entityId,
            @NotNull YAxis yAxis,
            float inventoryYRotation
        ) {}

        /**
         * Parses all known block entity model classes from the supplied client jar and returns
         * the extracted models as serialised JSON objects keyed by entity id.
         *
         * @param jarPath the deobfuscated client jar (MC 26.1+)
         * @return a map of entity id to model JSON
         */
        public static @NotNull ConcurrentMap<String, JsonObject> parse(@NotNull Path jarPath) {
            ConcurrentMap<String, JsonObject> results = Concurrent.newMap();

            try (ZipFile zip = new ZipFile(jarPath.toFile())) {
                for (Source source : SOURCES) {
                    ZipEntry entry = zip.getEntry(source.classEntry);
                    if (entry == null) {
                        System.err.printf("  skipped %s: class not found in jar%n", source.entityId);
                        continue;
                    }

                    try (InputStream stream = zip.getInputStream(entry)) {
                        byte[] classBytes = stream.readAllBytes();
                        ClassNode classNode = new ClassNode();
                        new ClassReader(classBytes).accept(classNode, ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);

                        MethodNode method = classNode.methods.stream()
                            .filter(m -> m.name.equals(source.methodName))
                            .findFirst()
                            .orElse(null);

                        if (method == null) {
                            System.err.printf("  skipped %s: method '%s' not found%n", source.entityId, source.methodName);
                            continue;
                        }

                        JsonObject model = parseLayerMethod(method.instructions);
                        if (model != null) {
                            if (source.yAxis == YAxis.UP)
                                flipToYDown(model);
                            model.addProperty("y_axis", source.yAxis.name());
                            if (source.inventoryYRotation != 0f)
                                model.addProperty("inventory_y_rotation", source.inventoryYRotation);
                            results.put(source.entityId, model);
                        }

                    } catch (Exception ex) {
                        System.err.printf("  skipped %s: %s%n", source.entityId, ex.getMessage());
                    }
                }
            } catch (IOException ex) {
                throw new AssetPipelineException(ex, "Failed to read client jar '%s'", jarPath);
            }

            return results;
        }

        /**
         * Post-processes a Y-up block entity model into the canonical Y-down form. For each
         * bone, negates the pivot's Y so the {@code PartPose} offset flips into the Y-down
         * frame; for each cube, mirrors the {@code origin.y} about the pivot's XZ plane. Because
         * {@code origin} is the <b>min</b> corner and {@code size} is an unsigned extent, the
         * new min Y is the negated former max: {@code origin.y = -origin.y - size.y}. X, Z, and
         * size are unaffected.
         */
        private static void flipToYDown(@NotNull JsonObject model) {
            JsonObject bones = model.getAsJsonObject("bones");
            if (bones == null) return;

            for (Map.Entry<String, JsonElement> entry : bones.entrySet()) {
                JsonObject bone = entry.getValue().getAsJsonObject();

                JsonArray pivot = bone.getAsJsonArray("pivot");
                if (pivot != null && pivot.size() == 3)
                    pivot.set(1, new JsonPrimitive(-pivot.get(1).getAsFloat()));

                JsonArray cubes = bone.getAsJsonArray("cubes");
                if (cubes == null) continue;

                for (JsonElement cubeElement : cubes) {
                    JsonObject cube = cubeElement.getAsJsonObject();
                    JsonArray origin = cube.getAsJsonArray("origin");
                    JsonArray size = cube.getAsJsonArray("size");
                    if (origin == null || size == null || origin.size() != 3 || size.size() != 3)
                        continue;

                    float oy = origin.get(1).getAsFloat();
                    float sy = size.get(1).getAsFloat();
                    origin.set(1, new JsonPrimitive(-oy - sy));
                }
            }
        }

        /**
         * Parses a single layer-creation method's bytecode and extracts the model geometry.
         */
        private static @Nullable JsonObject parseLayerMethod(@NotNull InsnList instructions) {
            ConcurrentList<Number> numStack = Concurrent.newList();
            @Nullable String pendingPartName = null;
            int pendingTexU = 0;
            int pendingTexV = 0;

            // Per-cube state (accumulated across texOffs + addBox chains)
            ConcurrentList<float[]> pendingCubes = Concurrent.newList();
            int[] pendingUv = {0, 0};

            // Per-part state
            float[] pendingPivot = {0, 0, 0};
            float[] pendingRotation = {0, 0, 0};

            // Accumulated parts
            JsonObject bones = new JsonObject();
            int texWidth = 64;
            int texHeight = 64;

            for (AbstractInsnNode node = instructions.getFirst(); node != null; node = node.getNext()) {
                // Track numeric literals
                Number literal = readNumericLiteral(node);
                if (literal != null) {
                    numStack.add(literal);
                    if (numStack.size() > 12)
                        numStack.removeFirst();
                    continue;
                }

                int opcode = node.getOpcode();

                switch (node) {
                    case FieldInsnNode fieldInsn when opcode == Opcodes.GETSTATIC -> {
                        if (fieldInsn.owner.equals(PART_POSE) && fieldInsn.name.equals("ZERO")) {
                            pendingPivot = new float[]{ 0, 0, 0 };
                            pendingRotation = new float[]{ 0, 0, 0 };
                        }
                    }
                    case MethodInsnNode methodInsn -> {
                        if (methodInsn.owner.equals(CUBE_LIST_BUILDER)) {
                            if (methodInsn.name.equals("texOffs") && methodInsn.desc.startsWith("(II")) {
                                pendingUv[1] = popInt(numStack);
                                pendingUv[0] = popInt(numStack);
                            } else if (methodInsn.name.equals("addBox") && methodInsn.desc.startsWith("(FFFFFF")) {
                                float d = popFloat(numStack);
                                float h = popFloat(numStack);
                                float w = popFloat(numStack);
                                float z = popFloat(numStack);
                                float y = popFloat(numStack);
                                float x = popFloat(numStack);
                                pendingCubes.add(new float[]{ x, y, z, w, h, d, pendingUv[0], pendingUv[1] });
                            }
                        } else if (methodInsn.owner.equals(PART_POSE)) {
                            if (methodInsn.name.equals("offset") && methodInsn.desc.startsWith("(FFF")) {
                                float pz = popFloat(numStack);
                                float py = popFloat(numStack);
                                float px = popFloat(numStack);
                                pendingPivot = new float[]{ px, py, pz };
                                pendingRotation = new float[]{ 0, 0, 0 };
                            } else if (methodInsn.name.equals("rotation") && methodInsn.desc.startsWith("(FFF")) {
                                // PartPose.rotation(rx, ry, rz) — rotation only, pivot stays at origin.
                                // Used by BedRenderer legs.
                                float rz = popFloat(numStack);
                                float ry = popFloat(numStack);
                                float rx = popFloat(numStack);
                                pendingPivot = new float[]{ 0, 0, 0 };
                                pendingRotation = new float[]{
                                    (float) Math.toDegrees(rx),
                                    (float) Math.toDegrees(ry),
                                    (float) Math.toDegrees(rz)
                                };
                            } else if (methodInsn.name.equals("offsetAndRotation") && methodInsn.desc.startsWith("(FFFFFF")) {
                                float rz = popFloat(numStack);
                                float ry = popFloat(numStack);
                                float rx = popFloat(numStack);
                                float pz = popFloat(numStack);
                                float py = popFloat(numStack);
                                float px = popFloat(numStack);
                                pendingPivot = new float[]{ px, py, pz };
                                pendingRotation = new float[]{
                                    (float) Math.toDegrees(rx),
                                    (float) Math.toDegrees(ry),
                                    (float) Math.toDegrees(rz)
                                };
                            }
                        } else if (methodInsn.owner.equals(PART_DEFINITION) && methodInsn.name.equals("addOrReplaceChild")) {
                            // The part name was pushed as an ldc String before the CubeListBuilder chain.
                            // Find it by scanning backward from numStack context.
                            if (pendingPartName != null && !pendingCubes.isEmpty()) {
                                bones.add(pendingPartName, buildBone(pendingPivot, pendingRotation, pendingCubes));
                            }
                            pendingPartName = null;
                            pendingCubes = Concurrent.newList();
                            pendingPivot = new float[]{ 0, 0, 0 };
                            pendingRotation = new float[]{ 0, 0, 0 };
                            pendingUv = new int[]{ 0, 0 };
                        } else if (methodInsn.owner.equals(LAYER_DEFINITION) && methodInsn.name.equals("create")) {
                            texHeight = popInt(numStack);
                            texWidth = popInt(numStack);
                        }
                    }
                    case LdcInsnNode ldc when ldc.cst instanceof String s ->
                        // Track the last string literal as potential part name
                        pendingPartName = s;
                    default -> { }
                }
            }

            if (bones.isEmpty()) return null;

            JsonObject model = new JsonObject();
            model.addProperty("textureWidth", texWidth);
            model.addProperty("textureHeight", texHeight);
            model.add("bones", bones);
            return model;
        }

        private static @NotNull JsonObject buildBone(float @NotNull [] pivot, float @NotNull [] rotation, @NotNull ConcurrentList<float[]> cubes) {
            JsonObject bone = new JsonObject();
            bone.add("pivot", floatArray(pivot));
            bone.add("rotation", floatArray(rotation));

            JsonArray cubeArray = new JsonArray();
            for (float[] c : cubes) {
                JsonObject cube = new JsonObject();
                cube.add("origin", floatArray(c[0], c[1], c[2]));
                cube.add("size", floatArray(c[3], c[4], c[5]));

                JsonArray uv = new JsonArray();
                uv.add((int) c[6]);
                uv.add((int) c[7]);
                cube.add("uv", uv);

                cube.addProperty("inflate", 0.0);
                cube.addProperty("mirror", false);
                cube.add("face_uv", new JsonObject());
                cubeArray.add(cube);
            }
            bone.add("cubes", cubeArray);
            return bone;
        }

        private static @NotNull JsonArray floatArray(float @NotNull ... values) {
            JsonArray arr = new JsonArray();
            for (float v : values) arr.add(v);
            return arr;
        }

        private static @Nullable Number readNumericLiteral(@NotNull AbstractInsnNode node) {
            int opcode = node.getOpcode();

            // iconst_m1 through iconst_5
            if (opcode >= Opcodes.ICONST_M1 && opcode <= Opcodes.ICONST_5)
                return opcode - Opcodes.ICONST_0;

            // fconst_0 through fconst_2
            if (opcode >= Opcodes.FCONST_0 && opcode <= Opcodes.FCONST_2)
                return (float) (opcode - Opcodes.FCONST_0);

            // bipush, sipush
            if ((opcode == Opcodes.BIPUSH || opcode == Opcodes.SIPUSH) && node instanceof IntInsnNode intInsn)
                return intInsn.operand;

            // ldc int or float
            if (opcode == Opcodes.LDC && node instanceof LdcInsnNode ldc) {
                if (ldc.cst instanceof Integer || ldc.cst instanceof Float)
                    return (Number) ldc.cst;
            }

            return null;
        }

        private static int popInt(@NotNull ConcurrentList<Number> stack) {
            if (stack.isEmpty()) return 0;
            return stack.remove(stack.size() - 1).intValue();
        }

        private static float popFloat(@NotNull ConcurrentList<Number> stack) {
            if (stack.isEmpty()) return 0f;
            return stack.remove(stack.size() - 1).floatValue();
        }

    }

    /**
     * Converts parsed entity model JSON (bones/cubes with box UV) into block model elements
     * JSON (from/to/faces with per-face UV). The output is in standard block model Y-up format
     * compatible with {@link dev.sbs.renderer.kit.GeometryKit#buildFromElements}.
     * <p>
     * Conversion steps per model:
     * <ol>
     * <li>Each bone's cubes provide origin, size, and box UV offset</li>
     * <li>Bone rotation is baked into cube positions (already done by Parser.bakeBoneRotations)</li>
     * <li>Y-down geometry is flipped to Y-up (already done by Parser.flipToYDown for Y-UP models,
     *     applied here for Y-DOWN models)</li>
     * <li>Box UV (u, v origin + w, h, d size) is expanded to 6 per-face UV rectangles using the
     *     vanilla Java {@code ModelPart.Cube} texture layout</li>
     * </ol>
     */
    @UtilityClass
    static class BlockModelConverter {

        /**
         * Vanilla inventory transforms per model type. Each transform is applied to the
         * model-space cube corners (in Y-down model units) before converting to Y-up block
         * model format. Values extracted from vanilla BedRenderer.createModelTransform and
         * ChestRenderer bytecode.
         */
        private static final java.util.Map<String, float[]> INVENTORY_TRANSFORMS = java.util.Map.of(
            // BedRenderer: translate(0, 9, 0) * Rx(90°) in model units
            "minecraft:bed_head", new float[]{ 0, 9, 0, 90, 0, 0 },
            "minecraft:bed_foot", new float[]{ 0, 9, 0, 90, 0, 0 }
        );

        /**
         * Converts all parsed entity models into a JSON object containing block model elements
         * keyed by entity model id.
         */
        static @NotNull JsonObject convert(@NotNull ConcurrentMap<String, JsonObject> entityModels) {
            JsonObject result = new JsonObject();
            result.addProperty("//", "Generated block model elements from entity model geometry. Run tooling/blockEntityModels to refresh.");

            for (Map.Entry<String, JsonObject> entry : entityModels.entrySet()) {
                String modelId = entry.getKey();
                JsonObject entityModel = entry.getValue();

                int texW = entityModel.has("textureWidth") ? entityModel.get("textureWidth").getAsInt() : 64;
                int texH = entityModel.has("textureHeight") ? entityModel.get("textureHeight").getAsInt() : 64;
                String yAxis = entityModel.has("y_axis") ? entityModel.get("y_axis").getAsString() : "DOWN";
                boolean isYDown = "DOWN".equals(yAxis);

                JsonObject bones = entityModel.getAsJsonObject("bones");
                if (bones == null) continue;

                // Look up the vanilla inventory transform for this model type
                float[] invTransform = INVENTORY_TRANSFORMS.get(modelId);
                boolean hasInvTransform = invTransform != null;

                JsonArray elements = new JsonArray();
                for (Map.Entry<String, JsonElement> boneEntry : bones.entrySet()) {
                    JsonObject bone = boneEntry.getValue().getAsJsonObject();
                    JsonArray pivotArr = bone.getAsJsonArray("pivot");
                    float px = pivotArr != null ? pivotArr.get(0).getAsFloat() : 0f;
                    float py = pivotArr != null ? pivotArr.get(1).getAsFloat() : 0f;
                    float pz = pivotArr != null ? pivotArr.get(2).getAsFloat() : 0f;

                    JsonArray cubes = bone.getAsJsonArray("cubes");
                    if (cubes == null) continue;

                    // Parse bone rotation (in degrees)
                    JsonArray rotArr = bone.getAsJsonArray("rotation");
                    float brx = 0, bry = 0, brz = 0;
                    if (rotArr != null && rotArr.size() == 3) {
                        brx = rotArr.get(0).getAsFloat();
                        bry = rotArr.get(1).getAsFloat();
                        brz = rotArr.get(2).getAsFloat();
                    }
                    boolean hasBoneRot = brx != 0 || bry != 0 || brz != 0;

                    // Precompute bone rotation matrix: Rz * Ry * Rx (matching vanilla's rotationZYX)
                    double rxR = Math.toRadians(brx), ryR = Math.toRadians(bry), rzR = Math.toRadians(brz);
                    double[][] mRx = {{ 1, 0, 0 }, { 0, Math.cos(rxR), -Math.sin(rxR) }, { 0, Math.sin(rxR), Math.cos(rxR) }};
                    double[][] mRy = {{ Math.cos(ryR), 0, Math.sin(ryR) }, { 0, 1, 0 }, { -Math.sin(ryR), 0, Math.cos(ryR) }};
                    double[][] mRz = {{ Math.cos(rzR), -Math.sin(rzR), 0 }, { Math.sin(rzR), Math.cos(rzR), 0 }, { 0, 0, 1 }};
                    double[][] boneRot = hasBoneRot ? matMul3(matMul3(mRz, mRy), mRx) : null;

                    for (JsonElement cubeEl : cubes) {
                        JsonObject cube = cubeEl.getAsJsonObject();
                        JsonArray originArr = cube.getAsJsonArray("origin");
                        JsonArray sizeArr = cube.getAsJsonArray("size");
                        int[] uv = { cube.getAsJsonArray("uv").get(0).getAsInt(), cube.getAsJsonArray("uv").get(1).getAsInt() };

                        float ox = originArr.get(0).getAsFloat();
                        float oy = originArr.get(1).getAsFloat();
                        float oz = originArr.get(2).getAsFloat();
                        float sw = sizeArr.get(0).getAsFloat();
                        float sh = sizeArr.get(1).getAsFloat();
                        float sd = sizeArr.get(2).getAsFloat();

                        // Transform all 8 corners: bone rotation + pivot + inventory transform + Y-flip
                        float minX = Float.MAX_VALUE, minY = Float.MAX_VALUE, minZ = Float.MAX_VALUE;
                        float maxX = -Float.MAX_VALUE, maxY = -Float.MAX_VALUE, maxZ = -Float.MAX_VALUE;
                        for (int dx = 0; dx <= 1; dx++) {
                            for (int dy = 0; dy <= 1; dy++) {
                                for (int dz = 0; dz <= 1; dz++) {
                                    float cx = ox + dx * sw;
                                    float cy = oy + dy * sh;
                                    float cz = oz + dz * sd;

                                    // 1. Apply bone rotation (Rz * Ry * Rx)
                                    if (boneRot != null) {
                                        double rx2 = boneRot[0][0]*cx + boneRot[0][1]*cy + boneRot[0][2]*cz;
                                        double ry2 = boneRot[1][0]*cx + boneRot[1][1]*cy + boneRot[1][2]*cz;
                                        double rz2 = boneRot[2][0]*cx + boneRot[2][1]*cy + boneRot[2][2]*cz;
                                        cx = (float) rx2; cy = (float) ry2; cz = (float) rz2;
                                    }

                                    // 2. Add bone pivot
                                    cx += px; cy += py; cz += pz;

                                    // 3. Apply inventory transform (model-specific)
                                    if (hasInvTransform) {
                                        float pitch = (float) Math.toRadians(invTransform[3]);
                                        float cosP = (float) Math.cos(pitch), sinP = (float) Math.sin(pitch);
                                        float ry = cy * cosP - cz * sinP;
                                        float rz = cy * sinP + cz * cosP;
                                        cy = ry + invTransform[1];
                                        cz = rz + invTransform[2];
                                    }

                                    // 4. Y-flip for non-inventory-transformed models
                                    if (!hasInvTransform) cy = -cy;

                                    minX = Math.min(minX, cx); maxX = Math.max(maxX, cx);
                                    minY = Math.min(minY, cy); maxY = Math.max(maxY, cy);
                                    minZ = Math.min(minZ, cz); maxZ = Math.max(maxZ, cz);
                                }
                            }
                        }

                        float fromX = minX, fromY = minY, fromZ = minZ;
                        float toX = maxX, toY = maxY, toZ = maxZ;

                        // Build per-face UV from box UV layout
                        // Vanilla Java Cube UV layout for box UV (u,v) with cube size (w,h,d):
                        //   DOWN:  (u+d,     v,     u+d+w,     v+d)
                        //   UP:    (u+d+w,   v+d,   u+d+w+d,   v)       [V reversed]
                        //   WEST:  (u,       v+d,   u+d,       v+d+h)
                        //   NORTH: (u+d,     v+d,   u+d+w,     v+d+h)
                        //   EAST:  (u+d+w,   v+d,   u+d+w+d,   v+d+h)
                        //   SOUTH: (u+d+w+d, v+d,   u+d+w+d+w, v+d+h)
                        int u = uv[0], v = uv[1];
                        int w = (int) sw, h = (int) sh, d = (int) sd;
                        float scale = 16.0f / texW;  // texture pixels to 0-16 block UV

                        JsonObject faces = new JsonObject();
                        addFace(faces, "down",  (u+d)*scale, v*scale, (u+d+w)*scale, (v+d)*scale, isYDown ? 0 : 180);
                        addFace(faces, "up",    (u+d)*scale, v*scale, (u+d+w)*scale, (v+d)*scale, 0);  // same region as down for entity models
                        addFace(faces, "west",  (u)*scale, (v+d)*scale, (u+d)*scale, (v+d+h)*scale, isYDown ? 0 : 180);
                        addFace(faces, "north", (u+d)*scale, (v+d)*scale, (u+d+w)*scale, (v+d+h)*scale, isYDown ? 0 : 180);
                        addFace(faces, "east",  (u+d+w)*scale, (v+d)*scale, (u+d+w+d)*scale, (v+d+h)*scale, isYDown ? 0 : 180);
                        addFace(faces, "south", (u+d+w+d)*scale, (v+d)*scale, (u+d+w+d+w)*scale, (v+d+h)*scale, isYDown ? 0 : 180);

                        JsonObject element = new JsonObject();
                        JsonArray from = new JsonArray(); from.add(round2(fromX)); from.add(round2(fromY)); from.add(round2(fromZ));
                        JsonArray to = new JsonArray(); to.add(round2(toX)); to.add(round2(toY)); to.add(round2(toZ));
                        element.add("from", from);
                        element.add("to", to);
                        element.add("faces", faces);
                        elements.add(element);
                    }
                }

                JsonObject modelOutput = new JsonObject();
                modelOutput.addProperty("textureWidth", texW);
                modelOutput.addProperty("textureHeight", texH);
                modelOutput.add("elements", elements);
                result.add(modelId, modelOutput);
            }

            return result;
        }

        private static double[][] matMul3(double[][] a, double[][] b) {
            double[][] r = new double[3][3];
            for (int i = 0; i < 3; i++)
                for (int j = 0; j < 3; j++)
                    r[i][j] = a[i][0] * b[0][j] + a[i][1] * b[1][j] + a[i][2] * b[2][j];
            return r;
        }

        private static void addFace(@NotNull JsonObject faces, @NotNull String dir, float u0, float v0, float u1, float v1, int rotation) {
            JsonObject face = new JsonObject();
            face.addProperty("texture", "#entity");
            JsonArray uv = new JsonArray();
            uv.add(round2(u0)); uv.add(round2(v0)); uv.add(round2(u1)); uv.add(round2(v1));
            face.add("uv", uv);
            if (rotation != 0) face.addProperty("rotation", rotation);
            faces.add(dir, face);
        }

        private static float round2(double v) {
            return (float) (Math.round(v * 100.0) / 100.0);
        }

    }

}
