package dev.sbs.renderer.tooling;

import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import dev.sbs.renderer.exception.AssetPipelineException;
import dev.sbs.renderer.pipeline.AssetPipelineOptions;
import dev.sbs.renderer.pipeline.client.ClientJarDownloader;
import dev.sbs.renderer.pipeline.client.HttpFetcher;
import dev.sbs.renderer.pipeline.loader.PotionColorLoader;
import dev.sbs.renderer.tooling.asm.AsmKit;
import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentMap;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.LdcInsnNode;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.TypeInsnNode;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.TreeMap;
import java.util.zip.ZipFile;

/**
 * Entry point invoked by the {@code potionColors} Gradle task.
 * <p>
 * Downloads (or reuses the cached) MC 26.1 client jar, runs {@link Parser} over its
 * {@code MobEffects} class, and writes the resulting effect colour table to
 * {@code src/main/resources/renderer/potion_colors.json}. The runtime pipeline reads the JSON
 * via {@link PotionColorLoader} so the ASM walker is never on the production classpath - the
 * only people who run it are developers bumping the bundled potion colour snapshot when a new
 * Minecraft version ships.
 * <p>
 * The output file format mirrors {@link ToolingBlockTints}'s shape: a top-level {@code effects}
 * array of {@code {effect, color}} objects, with colours stored as {@code 0x}-prefixed
 * uppercase hex strings.
 */
@UtilityClass
public final class ToolingPotionColors {

    private static final @NotNull Path OUTPUT_PATH = Path.of("src/main/resources/renderer/potion_colors.json");

    /**
     * Runs the generator.
     *
     * @param args ignored - the output path is fixed to keep the resource location stable
     * @throws IOException if writing the JSON file fails
     */
    public static void main(String @NotNull [] args) throws IOException {
        AssetPipelineOptions options = AssetPipelineOptions.defaults();
        Path jarPath;
        try {
            jarPath = ClientJarDownloader.download(options, new HttpFetcher());
        } catch (AssetPipelineException ex) {
            System.err.println("Failed to download client jar for potion colour generation: " + ex.getMessage());
            throw ex;
        }
        System.out.println("Parsing MobEffects from " + jarPath);

        ConcurrentMap<String, Integer> colors = Parser.parse(jarPath);
        System.out.println("Parser produced " + colors.size() + " potion effect colour entries");

        Files.createDirectories(OUTPUT_PATH.getParent());
        Files.writeString(OUTPUT_PATH, buildJson(colors, options.getVersion()));
        System.out.println("Wrote " + OUTPUT_PATH.toAbsolutePath());
    }

    /**
     * Serialises the parsed colour map into the bundled JSON format. Entries are sorted by
     * effect id so diffs stay reviewable on version bumps.
     */
    private static @NotNull String buildJson(@NotNull ConcurrentMap<String, Integer> colors, @NotNull String mcVersion) {
        JsonObject root = new JsonObject();
        root.addProperty("//", "Generated by ToolingPotionColors. From net.minecraft.world.effect.MobEffects clinit. Run the tooling/potionColors Gradle task to refresh.");
        root.addProperty("source_version", mcVersion);

        JsonArray entries = new JsonArray();
        // Sort deterministically so the checked-in JSON has stable ordering.
        Map<String, Integer> sorted = new TreeMap<>();
        colors.forEach(sorted::put);
        sorted.forEach((effectId, color) -> {
            JsonObject entry = new JsonObject();
            entry.addProperty("effect", effectId);
            entry.addProperty("color", String.format("0x%08X", color | 0xFF000000));
            entries.add(entry);
        });
        root.add("effects", entries);

        return new GsonBuilder().setPrettyPrinting().create().toJson(root) + System.lineSeparator();
    }

    /**
     * An ASM bytecode walker that parses {@code net.minecraft.world.effect.MobEffects}'s static
     * initializer and extracts one {@code effectId - &gt; argb} mapping per registered effect.
     * <p>
     * Walks the class-constructor instruction list and recognises the vanilla registration pattern:
     * <pre>
     *   ldc "effect_id"                                    // effect id
     *   new net/minecraft/world/effect/MobEffect           // (or a subclass)
     *   dup
     *   getstatic MobEffectCategory.BENEFICIAL             // category
     *   ldc 0xRRGGBB                                       // colour
     *   invokespecial &lt;effect class&gt;.&lt;init&gt;(category, int)
     *   ... optional chained builder calls ...
     *   invokestatic MobEffects.register(String, MobEffect)
     *   putstatic FIELD:Holder
     * </pre>
     * Tracks the most-recent LDC string and an int-literal stack; on {@code invokespecial} of a
     * {@code net/minecraft/world/effect/**MobEffect}{@code .<init>(Category, I)V}, the top int is
     * captured as the pending colour; on {@code invokestatic} of {@code register}, a
     * {@code (pendingId, pendingColour)} pair is emitted and state resets.
     */
    @UtilityClass
    static class Parser {

        private static final @NotNull String MOB_EFFECTS_INTERNAL_NAME = "net/minecraft/world/effect/MobEffects";
        private static final @NotNull String EFFECT_PACKAGE_PREFIX = "net/minecraft/world/effect/";
        private static final @NotNull String MOB_EFFECT_INIT_DESCRIPTOR = "(Lnet/minecraft/world/effect/MobEffectCategory;I)V";
        private static final @NotNull String CLINIT_METHOD_NAME = "<clinit>";
        private static final @NotNull String INIT_METHOD_NAME = "<init>";
        private static final @NotNull String REGISTER_METHOD_NAME = "register";

        /**
         * Parses the vanilla potion effect colour table out of {@code MobEffects}'s static
         * initializer in the supplied client jar.
         *
         * @param jarPath the deobfuscated client jar to read from (MC 26.1+)
         * @return a map of effect id to ARGB colour
         * @throws AssetPipelineException if the jar cannot be read or the class is missing
         */
        public static @NotNull ConcurrentMap<String, Integer> parse(@NotNull Path jarPath) {
            try (ZipFile zip = new ZipFile(jarPath.toFile())) {
                ClassNode classNode = AsmKit.requireClass(zip, MOB_EFFECTS_INTERNAL_NAME, "MobEffects");
                MethodNode clinit = AsmKit.findMethod(classNode, CLINIT_METHOD_NAME);
                if (clinit == null)
                    throw new AssetPipelineException(
                        "MobEffects class does not expose a '%s' method - jar may be obfuscated or from an unsupported version",
                        CLINIT_METHOD_NAME
                    );
                return parseClinit(clinit.instructions);
            } catch (IOException ex) {
                throw new AssetPipelineException(ex, "Failed to read MobEffects class from jar '%s'", jarPath);
            }
        }

        /**
         * Walks the {@code <clinit>} instruction list and emits one {@code (effectId, color)} pair
         * per recognised registration. See the parser javadoc for the recognition rules.
         */
        private static @NotNull ConcurrentMap<String, Integer> parseClinit(@NotNull InsnList instructions) {
            ConcurrentMap<String, Integer> colors = Concurrent.newMap();

            @Nullable String pendingEffectId = null;
            @Nullable Integer pendingColor = null;
            AsmKit.LiteralStack intLiteralStack = new AsmKit.LiteralStack(8);

            for (AbstractInsnNode node = instructions.getFirst(); node != null; node = node.getNext()) {
                int opcode = node.getOpcode();

                Integer literal = AsmKit.readIntLiteral(node);
                if (literal != null) {
                    intLiteralStack.push(literal);
                    continue;
                }

                if (opcode == Opcodes.LDC && node instanceof LdcInsnNode ldc && ldc.cst instanceof String str) {
                    // Only capture the first LDC string between registrations (the effect id);
                    // subsequent strings (e.g. attribute modifier ids like "effect.speed") are
                    // ignored by keeping pendingEffectId stable once set.
                    if (pendingEffectId == null) pendingEffectId = str;
                    continue;
                }

                if (opcode == Opcodes.NEW && node instanceof TypeInsnNode typeInsn
                    && typeInsn.desc.startsWith(EFFECT_PACKAGE_PREFIX)) {
                    // A new MobEffect (or subclass) is being constructed; reset the int stack so
                    // only the literals pushed between now and the invokespecial are considered
                    // for the colour.
                    intLiteralStack.reset();
                    continue;
                }

                if (node instanceof MethodInsnNode methodInsn
                    && opcode == Opcodes.INVOKESPECIAL
                    && methodInsn.name.equals(INIT_METHOD_NAME)
                    && methodInsn.owner.startsWith(EFFECT_PACKAGE_PREFIX)
                    && methodInsn.desc.equals(MOB_EFFECT_INIT_DESCRIPTOR)) {
                    // Constructor signature is (MobEffectCategory, int) - the int literal on top
                    // of the stack is the ARGB colour.
                    Integer top = intLiteralStack.popInt();
                    if (top != null) pendingColor = top;
                    continue;
                }

                if (node instanceof MethodInsnNode methodInsn
                    && opcode == Opcodes.INVOKESTATIC
                    && methodInsn.owner.equals(MOB_EFFECTS_INTERNAL_NAME)
                    && methodInsn.name.equals(REGISTER_METHOD_NAME)) {
                    if (pendingEffectId != null && pendingColor != null) {
                        colors.put("minecraft:" + pendingEffectId, pendingColor);
                    }
                    pendingEffectId = null;
                    pendingColor = null;
                    intLiteralStack.reset();
                }
            }

            return colors;
        }

    }

}
