"""The one accept criterion of the probe surface: the Python is *arithmetically* the same probe.

`panel stats` can never be cited as a verdict, so its value rests entirely on agreeing with
the shipped metric. That agreement is pinned here on a fixture whose expected value is transcribed
from ``ParityMetrics.java`` rather than produced by the code under test - a fixture generated by the
implementation would prove only that the implementation is self-consistent.
"""

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from parity import pixels
from parity.norm import MissingDependency

DATA = Path(__file__).resolve().parent / "data"

#: Hand-derived from ParityMetrics.compositeOverWhite (:89-91) and compositeDiff (:81-86) over the
#: four fixture pixels: 0 + 254 + 0 + 765 = 1019, over 4 pixels.
EXPECTED_MEAN_OVER_WHITE = 254.75
EXPECTED_DIFFERING = 2
EXPECTED_COVERAGE = 0.75


@unittest.skipUnless(pixels.available(), "Pillow/numpy absent")
class ArithmeticAgreement(unittest.TestCase):
    """The Python probe must be the same probe, not merely a similar one."""

    def setUp(self):
        from parity import panel
        self.panel = panel
        self.dir = Path(tempfile.mkdtemp()) / "minecraft__fixture"
        self.dir.mkdir(parents=True)
        for name in ("vanilla", "java"):
            (self.dir / f"{name}.png").write_bytes((DATA / f"pixels-2x2-{name}.png").read_bytes())

    def test_over_white_is_byte_for_byte_the_java_formula(self):
        """(c*a + 255*(255-a) + 127) // 255, integer division, on non-negative operands."""
        for channel, alpha, expected in ((255, 255, 255), (0, 255, 0), (0, 128, 127),
                                         (255, 128, 255), (0, 0, 255), (255, 0, 255)):
            self.assertEqual(int(self.panel.over_white(channel, alpha)), expected,
                             f"over_white({channel}, {alpha})")

    def test_mean_over_white_matches_the_shipped_metric(self):
        stats = self.panel.stats(self.dir)
        self.assertAlmostEqual(stats["mean_over_white"], EXPECTED_MEAN_OVER_WHITE, places=6)

    def test_differing_pixels_matches(self):
        self.assertEqual(self.panel.stats(self.dir)["differing_pixels"], EXPECTED_DIFFERING)

    def test_coverage_matches(self):
        coverage = self.panel.stats(self.dir)["coverage"]
        self.assertEqual(coverage["vanilla"] / 4, EXPECTED_COVERAGE)
        self.assertEqual(coverage["java"] / 4, EXPECTED_COVERAGE)

    def test_the_two_metrics_are_reported_under_distinct_names(self):
        """Conflating the 0..765 and 0..1020 scales is a recorded defect."""
        stats = self.panel.stats(self.dir)
        self.assertIn("mean_over_white", stats)
        self.assertIn("mean_abs_argb_1020", stats)
        self.assertNotEqual(stats["mean_over_white"], stats["mean_abs_argb_1020"])

    def test_the_1020_metric_is_the_raw_argb_sum(self):
        # |dA|+|dR|+|dG|+|dB| on raw channels: px1 (0,0,0,127) -> 127, px3 (0,255,255,255) -> 765.
        self.assertAlmostEqual(self.panel.stats(self.dir)["mean_abs_argb_1020"],
                               (127 + 765) / 4, places=6)


@unittest.skipUnless(pixels.available(), "Pillow/numpy absent")
class Shapes(unittest.TestCase):

    def setUp(self):
        from parity import panel
        self.panel = panel
        self.dir = Path(tempfile.mkdtemp()) / "minecraft__fixture"
        self.dir.mkdir(parents=True)
        for name in ("vanilla", "java"):
            (self.dir / f"{name}.png").write_bytes((DATA / f"pixels-2x2-{name}.png").read_bytes())

    def test_attribution_shares_sum_to_a_hundred(self):
        attribution = self.panel.stats(self.dir)["attribution"]
        total = (attribution["vanilla_only"] + attribution["java_only"]
                 + attribution["both_colour"])
        self.assertAlmostEqual(total, 100.0, places=6)

    def test_silhouette_iou_is_bounded(self):
        silhouette = self.panel.stats(self.dir)["silhouette"]
        self.assertGreaterEqual(silhouette["iou"], 0.0)
        self.assertLessEqual(silhouette["iou"], 1.0)

    def test_columns_reports_width_parity(self):
        columns = self.panel.stats(self.dir, columns=True)["columns"]
        self.assertEqual(columns["width_parity"], "even")
        self.assertIn("centre_share", columns)

    def test_bbox_is_the_painted_content_not_the_canvas(self):
        """The canvas-mismatch back-solve: it decides java-versus-harness with no re-render."""
        bbox = self.panel.stats(self.dir, bbox=True)["bbox"]
        self.assertEqual(bbox["vanilla"]["width"], 2)
        self.assertEqual(bbox["vanilla"]["y0"], 0)


SWEEP_OUTPUT = Path(__file__).resolve().parents[4] / "cache/visual/entity-parity-vanilla"


@unittest.skipUnless(pixels.available() and SWEEP_OUTPUT.is_dir(), "sweep output or pixels absent")
class AgreesWithTheJavaOnRealRenders(unittest.TestCase):
    """The fixture pins the formula; this pins the whole pipeline against the shipped writer.

    The sweep table's ``mean_argb_delta`` was computed by ``ParityMetrics`` in Java over the same
    PNG pair, so agreement here is cross-implementation on real data rather than on four pixels.
    The tolerance is the table's own ``%.4f``, not a fitted epsilon.
    """

    def test_ten_subjects_agree_to_the_tables_own_precision(self):
        from parity import panel, sweep
        table_path = SWEEP_OUTPUT / "parity-report.tsv"
        if not table_path.is_file():
            self.skipTest("no parity-report.tsv beside the renders")
        table = sweep.read_table(table_path, "entity")
        expected = {row.key: row.values["mean_argb_delta"] for row in table.rows}

        checked = 0
        for directory in sorted(SWEEP_OUTPUT.iterdir()):
            if checked >= 10:
                break
            if not directory.is_dir() or directory.name not in expected:
                continue
            if not (directory / "java.png").is_file():
                continue
            measured = panel.stats(directory)["mean_over_white"]
            self.assertAlmostEqual(measured, float(expected[directory.name]), places=3,
                                   msg=directory.name)
            checked += 1
        self.assertGreater(checked, 0, "no subject was actually compared")


class DependencyBoundary(unittest.TestCase):
    """The gate path is stdlib by construction; this is the surface where that stops."""

    def test_available_is_a_bool_and_never_raises(self):
        self.assertIn(pixels.available(), (True, False))

    def test_require_names_the_install_line(self):
        if pixels.available():
            self.assertEqual(len(pixels.missing()), 0)
            return
        with self.assertRaises(MissingDependency) as caught:
            pixels.require("panel stats")
        self.assertIn("pip install", str(caught.exception))

    def test_panel_is_not_importable_without_the_pair(self):
        """panel imports pixels, never numpy - so the boundary holds from the other side too."""
        source = (Path(__file__).resolve().parents[1] / "panel.py").read_text(encoding="utf-8")
        self.assertNotIn("import numpy", source)
        self.assertNotIn("from PIL", source)


if __name__ == "__main__":
    unittest.main()
