"""The one accept criterion of the probe surface: the Python is *arithmetically* the same probe.

`panel stats` can never be cited as a verdict, so its value rests entirely on agreeing with
the shipped metric. That agreement is pinned here on a fixture whose expected value is transcribed
from ``ParityMetrics.java`` rather than produced by the code under test - a fixture generated by the
implementation would prove only that the implementation is self-consistent.
"""

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from parity import pixels
from parity.norm import MissingDependency

DATA = Path(__file__).resolve().parent / "data"

#: Hand-derived from ``ParityMetrics.compositeOverWhite`` and ``compositeDiff`` over the four fixture
#: pixels: 0 + 254 + 0 + 765 = 1019, over 4 pixels.
EXPECTED_MEAN_OVER_WHITE = 254.75
EXPECTED_DIFFERING = 2
EXPECTED_COVERAGE = 0.75


@unittest.skipUnless(pixels.available(), "Pillow/numpy absent")
class ArithmeticAgreement(unittest.TestCase):
    """The Python probe must be the same probe, not merely a similar one."""

    def setUp(self):
        from parity import panel
        self.panel = panel
        self.dir = Path(tempfile.mkdtemp()) / "minecraft__fixture"
        self.dir.mkdir(parents=True)
        for name in ("vanilla", "java"):
            (self.dir / f"{name}.png").write_bytes((DATA / f"pixels-2x2-{name}.png").read_bytes())

    def test_over_white_is_byte_for_byte_the_java_formula(self):
        """(c*a + 255*(255-a) + 127) // 255, integer division, on non-negative operands."""
        for channel, alpha, expected in ((255, 255, 255), (0, 255, 0), (0, 128, 127),
                                         (255, 128, 255), (0, 0, 255), (255, 0, 255)):
            self.assertEqual(int(self.panel.over_white(channel, alpha)), expected,
                             f"over_white({channel}, {alpha})")

    def test_mean_over_white_matches_the_shipped_metric(self):
        stats = self.panel.stats(self.dir)
        self.assertAlmostEqual(stats["mean_over_white"], EXPECTED_MEAN_OVER_WHITE, places=6)

    def test_differing_pixels_matches(self):
        self.assertEqual(self.panel.stats(self.dir)["differing_pixels"], EXPECTED_DIFFERING)

    def test_coverage_matches(self):
        coverage = self.panel.stats(self.dir)["coverage"]
        self.assertEqual(coverage["vanilla"] / 4, EXPECTED_COVERAGE)
        self.assertEqual(coverage["java"] / 4, EXPECTED_COVERAGE)

    def test_the_two_metrics_are_reported_under_distinct_names(self):
        """Conflating the 0..765 and 0..1020 scales is a recorded defect."""
        stats = self.panel.stats(self.dir)
        self.assertIn("mean_over_white", stats)
        self.assertIn("mean_abs_argb_1020", stats)
        self.assertNotEqual(stats["mean_over_white"], stats["mean_abs_argb_1020"])

    def test_the_1020_metric_is_the_raw_argb_sum(self):
        # |dA|+|dR|+|dG|+|dB| on raw channels: px1 (0,0,0,127) -> 127, px3 (0,255,255,255) -> 765.
        self.assertAlmostEqual(self.panel.stats(self.dir)["mean_abs_argb_1020"],
                               (127 + 765) / 4, places=6)


@unittest.skipUnless(pixels.available(), "Pillow/numpy absent")
class Shapes(unittest.TestCase):

    def setUp(self):
        from parity import panel
        self.panel = panel
        self.dir = Path(tempfile.mkdtemp()) / "minecraft__fixture"
        self.dir.mkdir(parents=True)
        for name in ("vanilla", "java"):
            (self.dir / f"{name}.png").write_bytes((DATA / f"pixels-2x2-{name}.png").read_bytes())

    def test_attribution_shares_sum_to_a_hundred(self):
        attribution = self.panel.stats(self.dir)["attribution"]
        total = (attribution["vanilla_only"] + attribution["java_only"]
                 + attribution["both_colour"])
        self.assertAlmostEqual(total, 100.0, places=6)

    def test_silhouette_iou_is_bounded(self):
        silhouette = self.panel.stats(self.dir)["silhouette"]
        self.assertGreaterEqual(silhouette["iou"], 0.0)
        self.assertLessEqual(silhouette["iou"], 1.0)

    def test_columns_reports_width_parity(self):
        columns = self.panel.stats(self.dir, columns=True)["columns"]
        self.assertEqual(columns["width_parity"], "even")
        self.assertIn("centre_share", columns)

    def test_bbox_is_the_painted_content_not_the_canvas(self):
        """The canvas-mismatch back-solve: it decides java-versus-harness with no re-render."""
        bbox = self.panel.stats(self.dir, bbox=True)["bbox"]
        self.assertEqual(bbox["vanilla"]["width"], 2)
        self.assertEqual(bbox["vanilla"]["y0"], 0)


def _png(path: Path, width: int, height: int, *red: tuple[int, int]) -> None:
    """Writes a transparent ``width x height`` PNG with an opaque red pixel at each ``(x, y)``."""
    image = pixels.image_module().new("RGBA", (width, height), (0, 0, 0, 0))
    for point in red:
        image.putpixel(point, (255, 0, 0, 255))
    image.save(path)


@unittest.skipUnless(pixels.available(), "Pillow/numpy absent")
class PadsLikeTheSweeps(unittest.TestCase):
    """A pair whose canvases differ is centred the way the sweeps centre it.

    Every expected value is transcribed from ``ParityMetrics.padToCanvas`` - each side at
    ``((canvasW - w) / 2, (canvasH - h) / 2)`` in ``int`` arithmetic on a transparent canvas - and
    from ``compareImages`` over the whole union it pads to. Every painted pixel is opaque red, so red
    on red is a zero delta and red against transparent is ``0 + 255 + 255 = 510`` over white.
    """

    def setUp(self):
        from parity import panel
        self.panel = panel
        root = Path(tempfile.mkdtemp())
        self.larger = root / "minecraft__larger_vanilla"
        self.crossed = root / "minecraft__crossed"
        self.odd = root / "minecraft__odd_margin"
        for directory in (self.larger, self.crossed, self.odd):
            directory.mkdir(parents=True)
        # vanilla 3x3 with its one red pixel at the centre; java 1x1 red.
        _png(self.larger / "vanilla.png", 3, 3, (1, 1))
        _png(self.larger / "java.png", 1, 1, (0, 0))
        # vanilla 3 wide and 1 tall, java 1 wide and 3 tall, each red at its middle.
        _png(self.crossed / "vanilla.png", 3, 1, (1, 0))
        _png(self.crossed / "java.png", 1, 3, (0, 1))
        # vanilla 2x1 red on the left; java 1x1 red, one column of margin to split.
        _png(self.odd / "vanilla.png", 2, 1, (0, 0))
        _png(self.odd / "java.png", 1, 1, (0, 0))

    def test_a_larger_vanilla_canvas_is_centred_not_cropped(self):
        """Java lands at (1, 1), on the red. A top-left crop reads 510 over one pixel, and a pad at
        the corner or centred on one axis alone reads 1020 / 9."""
        stats = self.panel.stats(self.larger)
        self.assertAlmostEqual(stats["mean_over_white"], 0.0, places=6)
        self.assertEqual(stats["differing_pixels"], 0)
        self.assertEqual(stats["canvas"], {"height": 3, "width": 3})

    def test_each_side_is_centred_on_its_own_short_axis(self):
        """Vanilla is centred down and java across, so both reds land at (1, 1) of a 3x3 union. A
        pad at the corner reads 1020 / 9; a crop reads 0 over a 1x1 canvas, which the canvas
        assertion refuses."""
        stats = self.panel.stats(self.crossed)
        self.assertAlmostEqual(stats["mean_over_white"], 0.0, places=6)
        self.assertEqual(stats["canvas"], {"height": 3, "width": 3})

    def test_an_odd_margin_floors_like_java(self):
        """``(2 - 1) / 2`` is 0 in ``int`` arithmetic, so java lands on the left, on the red. An
        offset rounded up reads 1020 / 2."""
        stats = self.panel.stats(self.odd)
        self.assertAlmostEqual(stats["mean_over_white"], 0.0, places=6)
        self.assertEqual(stats["canvas"], {"height": 1, "width": 2})

    def test_each_side_keeps_its_own_canvas_and_content_box(self):
        """The content box is where that side's renderer put the content, which is what the
        canvas-mismatch back-solve reads, so it is taken before the pad moves anything."""
        stats = self.panel.stats(self.larger, bbox=True)
        self.assertEqual(stats["canvases"], {"java": {"height": 1, "width": 1},
                                             "vanilla": {"height": 3, "width": 3}})
        self.assertEqual(stats["bbox"]["java"],
                         {"height": 1, "width": 1, "x0": 0, "x1": 0, "y0": 0, "y1": 0})
        self.assertEqual(stats["bbox"]["vanilla"],
                         {"height": 1, "width": 1, "x0": 1, "x1": 1, "y0": 1, "y1": 1})


SWEEP_OUTPUT = Path(__file__).resolve().parents[4] / "cache/visual/entity-parity-vanilla"


@unittest.skipUnless(pixels.available() and SWEEP_OUTPUT.is_dir(), "sweep output or pixels absent")
class AgreesWithTheJavaOnRealRenders(unittest.TestCase):
    """The fixture pins the formula; this pins the whole pipeline against the shipped writer.

    The sweep table's ``mean_argb_delta`` was computed by ``ParityMetrics`` in Java over the same
    PNG pair, so agreement here is cross-implementation on real data rather than on four pixels. It
    checks the first ten rows the table holds and every row whose two canvases differ, because the
    pad is what a mismatched row exercises and a scoped run's table holds only the rows that run
    rendered. Rows are read from the table rather than from the directory listing, so a subject
    directory an earlier run left behind is never compared against a row it was not computed for.
    The tolerance is the table's own ``%.4f``, not a fitted epsilon.
    """

    def test_the_first_rows_and_every_mismatched_canvas_agree_to_the_tables_own_precision(self):
        from parity import panel, sweep
        table_path = SWEEP_OUTPUT / "parity-report.tsv"
        if not table_path.is_file():
            self.skipTest("no parity-report.tsv beside the renders")
        table = sweep.read_table(table_path, "entity")
        comparable = sorted((row for row in table.rows if row.delta() is not None
                             and (SWEEP_OUTPUT / row.key / "vanilla.png").is_file()
                             and (SWEEP_OUTPUT / row.key / "java.png").is_file()),
                            key=lambda row: row.key)
        if not comparable:
            self.skipTest("the table holds no row with a delta and a vanilla/java pair")
        java_w, java_h, vanilla_w, vanilla_h = sweep.CANVAS
        mismatched = [row for row in comparable
                      if (row.values[java_w], row.values[java_h])
                      != (row.values[vanilla_w], row.values[vanilla_h])]
        chosen = comparable[:10] + [row for row in mismatched if row not in comparable[:10]]
        for row in chosen:
            where = f"{row.key} (the table holds {len(mismatched)} canvas-mismatched rows)"
            stats = panel.stats(SWEEP_OUTPUT / row.key)
            self.assertEqual(stats["canvas"],
                             {"height": max(int(row.values[java_h]), int(row.values[vanilla_h])),
                              "width": max(int(row.values[java_w]), int(row.values[vanilla_w]))},
                             where)
            self.assertAlmostEqual(stats["mean_over_white"], row.delta(), places=3, msg=where)


class DependencyBoundary(unittest.TestCase):
    """The gate path is stdlib by construction; this is the surface where that stops."""

    def test_available_is_a_bool_and_never_raises(self):
        self.assertIn(pixels.available(), (True, False))

    def test_require_names_the_install_line(self):
        if pixels.available():
            self.assertEqual(len(pixels.missing()), 0)
            return
        with self.assertRaises(MissingDependency) as caught:
            pixels.require("panel stats")
        self.assertIn("pip install", str(caught.exception))

    def test_panel_is_not_importable_without_the_pair(self):
        """panel imports pixels, never numpy - so the boundary holds from the other side too."""
        source = (Path(__file__).resolve().parents[1] / "panel.py").read_text(encoding="utf-8")
        self.assertNotIn("import numpy", source)
        self.assertNotIn("from PIL", source)


if __name__ == "__main__":
    unittest.main()
