"""Class-level parity reach, derived from the compiled constant pool.

Answers which parity artifacts a changed Java type can move, by walking the reference graph the
compiler emitted rather than the directory the file sits in.

The constant pool is the substrate because an import is not evidence. The javadoc convention
requires importing a ``{@link}`` target rather than inlining an FQN, so documenting a type creates an
import that is not a dependency; measured over this tree, 104 import edges are javadoc-only and 360
real edges carry no import at all, same-package and nested references needing none. Neither error
appears in a class file: javadoc never reaches one, and a same-package call puts a ``CONSTANT_Class``
in the pool exactly as a cross-package one does.

The roots are producers rather than renderers. A renderer is entered by a producer, and ninety types
- every loader, index builder and deserialiser - are referenced by no renderer at all, so rooting at
one leaves them unreachable. Rooting at the producer walks test to renderer to kit, which is why an
edge INTO a renderer is load-bearing here and why the renderer-to-renderer edges that survive are
real: an entity draws a carried block through ``BlockRenderer``.

This module computes and returns. It prints nothing and writes nothing - ``cli`` prints and ``norm``
writes.
"""

from __future__ import annotations

import hashlib
import re
import struct
from collections import defaultdict, deque
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Mapping, Sequence

from parity import declarations as declarations_mod
from parity.blindness import Rule, matches

from .norm import MissingInput

#: The package every edge this module cares about lives under, in binary (slash) form.
PACKAGE = "lib/minecraft/renderer"

#: Source roots holding types that can carry a parity reach, relative to the repo root.
#:
#: The generators are here for the same reason the renderer's test and visual trees are: they are a
#: producer, and what a producer reaches is what its artifact can be moved by. The visual tree holds
#: every sweep and driver. The generators' TEST tree is absent because no artifact roots at a tooling
#: test, and walking it would add edges into the renderer that no producer travels.
SOURCE_ROOTS = ("src/main/java", "src/test/java", "src/visual/java", "tooling/src/main/java")

#: Compiled roots, walked for constant pools. One per source root that carries a producer, in the
#: same order.
CLASS_ROOTS = ("build/classes/java/main", "build/classes/java/test", "build/classes/java/visual",
               "tooling/build/classes/java/main")

#: The committed graph, relative to the ``parity/`` directory.
STORED = "reach.json"

#: Each artifact's producer entry point, by simple type name.
#:
#: A row produced by a whole SUITE is rooted at the class that WRITES it rather than at the suite,
#: which is the same distinction the capture wiring draws: ``test`` runs the whole fast suite to
#: write the shipped-tables digest and the pins the store keeps, and what those rows can be moved by
#: is what their own writer reaches. A suite as a root would be every test class, which answers
#: "everything" and says nothing.
#:
#: A row one class writes under a property is rooted at that class, because a property changes what
#: the class measures and never its constant pool, which is all this graph reads.
#: ``sweep.entity-walk`` is ``EntityAnimationParitySweep`` run under ``asset.parity.gait=walk``, so
#: it roots where ``sweep.entity-animation`` does and a type answers the walk row wherever it answers
#: that one.
#:
#: What is rooted is the index's ``artifacts`` map, the one home a capture writes a file into and
#: so the one a plan can name. Its ``pointers``, ``sources`` and ``external`` maps register
#: artifacts the store keeps no file for, each with an empty producer list in ``ParityArtifacts``,
#: so none of them has a writer to root at.
#:
#: Three artifacts the ``artifacts`` map holds have no root either, because no type in this tree
#: writes them, and ``UNROOTED`` below records each with that reason:
#:
#: - ``manifest.references`` hashes the harness's reference tree, which a separate Gradle build
#:   writes and this build reaches only by shelling into its wrapper. The blindness map's authored
#:   rules select it instead.
#: - ``report.oracle-index`` is the store's ``index.json``, which ``parityPromote`` rewrites on
#:   every promotion.
#: - ``roster.blindness-rules`` is the store's ``blindness.json``, authored by hand with its trigger
#:   paths regenerated by the toolkit's ``triggers`` command.
#:
#: The two store files have no capture step, so no plan has a row of theirs to select. An artifact
#: the ``artifacts`` map holds that is in neither table fails the toolkit's selftest, because a
#: derived rule plans off this graph alone and would leave that artifact out of every plan without
#: saying so.
#:
#: A root is matched by SIMPLE name, first in sorted binary order, over every type the four source
#: roots declare - the renderer's three trees and the generators' main - so a simple name is the
#: whole of what picks a root's type. A root added under a name two trees declare would resolve to
#: whichever sorts first rather than being refused, and nothing reports the tie, so give one a name
#: only its own tree carries.
ROOTS: dict[str, tuple[str, ...]] = {
    # --- sweeps, each a JavaExec main of its own
    "sweep.entity": ("EntityParitySweep",),
    "sweep.entity-animation": ("EntityAnimationParitySweep",),
    # the same driver at a gait, measured against the walk/ sub-tree rather than idle/
    "sweep.entity-walk": ("EntityAnimationParitySweep",),
    "sweep.block": ("BlockParitySweep",),
    "sweep.item": ("ItemParitySweep",),
    "sweep.glint": ("GlintParitySweep",),
    "sweep.player": ("PlayerParitySweep",),
    "sweep.armor": ("ArmorParitySweep",),
    "sweep.menu": ("MenuParitySweep",),
    # --- render manifests. player-raw aggregates both rescaling sweeps rather than either one.
    "manifest.player-raw": ("PlayerParitySweep", "ArmorParitySweep"),
    "manifest.player-sheets": ("PlayerRenderDriver",),
    "manifest.fluid": ("FluidRenderDriver",),
    "manifest.portal": ("PortalRenderDriver",),
    "manifest.dump.vanilla": ("PipelineParityDump",),
    "manifest.dump.packs": ("PipelineParityDump",),
    # --- the eight visual drivers whose cache/visual sub-tree no other artifact covers
    "manifest.visual": ("BlockRenderDriver", "EntityProjectionsDriver", "EntityRenderDriver",
                        "ItemDayCycleDriver", "ItemRenderDriver", "LoreTooltipDriver",
                        "MenuRenderDriver", "BlockProjectionsDriver"),
    # --- self-captured rows, at their writer rather than at the suite that runs it
    "digest.shipped-tables": ("BundledResourceShaTest",),
    "digest.colormap-lut": ("ClientAcquisitionIntegrationTest",),
    "pin.vanilla-iso-pose": ("VanillaIsoPoseGoldenTest",),
    "pin.kit-corners": ("VanillaEntityTransformGoldenTest",),
    "pin.corpus-count": ("CorpusCountPinTest",),
    "pin.player-crc": ("PlayerRendererFittedGoldenTest",),
    "pin.block-crc": ("BlockRendererRasterPinTest",),
    "pin.portal-crc": ("PortalRendererFrameBakePinTest",),
    "pin.fluid-crc": ("FluidRendererFrameBakePinTest",),
    # --- the eight generator flows, which digest into one manifest. All eight, because the artifact
    # covers every table and each flow writes its own: rooting at one would answer for a renderer
    # type only that flow reaches and call the rest blind.
    "manifest.tooling-tables": ("EntityModelsFlow", "BlockModelsFlow", "BlockDefaultsFlow",
                                "BlockItemsFlow", "BlockTintsFlow", "PotionColorsFlow",
                                "GlintItemsFlow", "ColorMapsFlow"),
}

#: Every artifact the store index's ``artifacts`` map holds that ``ROOTS`` deliberately does not
#: root, each with why.
#:
#: The toolkit's selftest holds the two tables to that map together: every artifact it holds is in
#: exactly one of them, and neither names an artifact it does not hold, so a coined artifact whose
#: index row lands without a root fails there rather than planning as though nothing reached it.
UNROOTED: dict[str, str] = {
    "manifest.references": "the harness's reference tree, which a separate Gradle build writes "
                           "and this build reaches only by shelling into its wrapper",
    "report.oracle-index": "the store's index.json, which parityPromote rewrites and no type in "
                           "this tree writes",
    "roster.blindness-rules": "the store's blindness.json, authored by hand with its trigger "
                              "paths regenerated by the toolkit's triggers command, which no type "
                              "in this tree writes",
}

#: Every demoting claim ``reach check`` holds, mapped to the carriers allowed to reach what it
#: subtracts.
#:
#: A demote takes its ``blind`` list back out of the plan on every path it fires on, whatever put an
#: artifact in that path's union, so a carrier the graph walks to one of those artifacts has it
#: removed from its own plan and the plan says nothing. Every claim-keyed demote that fires on a
#: scanned source path is held here, against a ledger of the carriers that lose an artifact that way
#: by decision. ``reach check`` refuses a carrier that reaches what its demote subtracts and is not
#: listed - a new carrier, or a new edge into one - and a listed path that no longer reaches it or
#: that the demote no longer fires on, so a ledger only shrinks.
#:
#: Two ledgers are empty. ``tooling-blindness`` is true only of code no renderer producer runs: a
#: generator change cannot move a sweep, the sweeps reading the SHIPPED tables, so a renderer caller
#: of ``TableEnvelope`` would put the sweeps it reaches in the envelope's reach and the demote would
#: subtract them from every plan selecting it. ``menu-closure`` is true only while a menu type
#: reaches nothing but the visual manifest and the menu sweep.
#:
#: The other four subtract what the graph reaches, by decision. The three derived ones -
#: ``engine-renders``, ``tensor-math`` and ``face-vocabulary`` - take the two dumps off a type the
#: dump reads or serialises and never renders; ``cit-grammar`` takes the item, armour, entity, menu
#: and player renders off a grammar type those producers reach through a match none of them
#: exercises, since none stacks a pack carrying a CIT rule. The ``harness-*`` claims fire on no
#: scanned source path, so the graph has nothing to check for them and none is held.
HELD_DEMOTES: dict[str, frozenset[str]] = {
    "tooling-blindness": frozenset(),
    "menu-closure": frozenset(),
    "engine-renders": frozenset({
        "src/main/java/lib/minecraft/renderer/diagnostic/Substitutions.java",
        "src/main/java/lib/minecraft/renderer/engine/draw/PassDeclaration.java",
        "src/main/java/lib/minecraft/renderer/engine/frame/RasterPass.java",
        "src/main/java/lib/minecraft/renderer/engine/frame/Timeline.java",
        "src/main/java/lib/minecraft/renderer/engine/geometry/EulerRotation.java",
        "src/main/java/lib/minecraft/renderer/engine/geometry/Face.java",
        "src/main/java/lib/minecraft/renderer/engine/geometry/ModelUnits.java",
        "src/main/java/lib/minecraft/renderer/engine/texture/MissingSprite.java",
        "src/main/java/lib/minecraft/renderer/content/index/MapRendererContext.java",
        "src/main/java/lib/minecraft/renderer/content/index/RendererContext.java",
    }),
    "tensor-math": frozenset({
        "src/main/java/lib/minecraft/renderer/engine/geometry/EulerRotation.java",
        "src/main/java/lib/minecraft/renderer/engine/pose/VanillaEase.java",
        "src/main/java/lib/minecraft/renderer/engine/pose/VanillaMth.java",
        "src/main/java/lib/minecraft/renderer/engine/math/Matrix4f.java",
        "src/main/java/lib/minecraft/renderer/engine/math/Quaternionf.java",
        "src/main/java/lib/minecraft/renderer/engine/math/SimdOps.java",
        "src/main/java/lib/minecraft/renderer/engine/math/SimdSupport.java",
        "src/main/java/lib/minecraft/renderer/engine/math/Vector2f.java",
        "src/main/java/lib/minecraft/renderer/engine/math/Vector3f.java",
        "src/main/java/lib/minecraft/renderer/engine/math/Vector4f.java",
    }),
    "face-vocabulary": frozenset({
        "src/main/java/lib/minecraft/renderer/engine/geometry/Face.java",
    }),
    "cit-grammar": frozenset({
        "src/main/java/lib/minecraft/renderer/asset/rule/CitOutput.java",
        "src/main/java/lib/minecraft/renderer/asset/rule/CitRule.java",
        "src/main/java/lib/minecraft/renderer/asset/rule/CitType.java",
        "src/main/java/lib/minecraft/renderer/asset/rule/DamageSpec.java",
        "src/main/java/lib/minecraft/renderer/asset/rule/EnchantmentSpec.java",
        "src/main/java/lib/minecraft/renderer/asset/rule/Hand.java",
        "src/main/java/lib/minecraft/renderer/asset/rule/filter/IntRange.java",
        "src/main/java/lib/minecraft/renderer/asset/rule/filter/IntRanges.java",
        "src/main/java/lib/minecraft/renderer/asset/rule/filter/NbtPath.java",
        "src/main/java/lib/minecraft/renderer/asset/rule/filter/NbtPredicate.java",
        "src/main/java/lib/minecraft/renderer/asset/rule/filter/NbtRule.java",
        "src/main/java/lib/minecraft/renderer/asset/rule/filter/NbtValues.java",
    }),
}

_REFERENCE = re.compile(re.escape(PACKAGE) + r"/[A-Za-z0-9_/$]+")

#: Constant-pool tags whose entry occupies the given number of bytes after the tag.
_FIXED_WIDTH = {7: 2, 8: 2, 16: 2, 19: 2, 20: 2, 15: 3,
                3: 4, 4: 4, 9: 4, 10: 4, 11: 4, 12: 4, 17: 4, 18: 4}

#: The two tags that consume a second constant-pool slot, per JVMS 4.4.5.
_TWO_SLOT = (5, 6)

#: ``ACC_INTERFACE``, which is what tells a declaration of capability from a body that calls.
_ACC_INTERFACE = 0x0200

#: The class attribute a sealed type lists its permitted subtypes in, per JVMS 4.7.31.
_PERMITTED = "PermittedSubclasses"

#: Each instruction's length in bytes, its opcode included, per JVMS 6.5. The three whose length
#: depends on where they sit or on what they widen - ``tableswitch``, ``lookupswitch`` and ``wide`` -
#: are measured where they are met and carry no entry, and neither does an opcode JVMS gives no
#: meaning in a class file.
_OPCODE_WIDTH: dict[int, int] = {
    **dict.fromkeys(range(0x00, 0x10), 1),                  # nop to dconst_1
    0x10: 2, 0x11: 3, 0x12: 2, 0x13: 3, 0x14: 3,            # bipush, sipush, ldc, ldc_w, ldc2_w
    **dict.fromkeys(range(0x15, 0x1a), 2),                  # iload to aload
    **dict.fromkeys(range(0x1a, 0x36), 1),                  # iload_0 to saload
    **dict.fromkeys(range(0x36, 0x3b), 2),                  # istore to astore
    **dict.fromkeys(range(0x3b, 0x84), 1),                  # istore_0 to lxor
    0x84: 3,                                                # iinc
    **dict.fromkeys(range(0x85, 0x99), 1),                  # i2l to dcmpg
    **dict.fromkeys(range(0x99, 0xa9), 3),                  # ifeq to jsr
    0xa9: 2,                                                # ret
    **dict.fromkeys(range(0xac, 0xb2), 1),                  # ireturn to return
    **dict.fromkeys(range(0xb2, 0xb9), 3),                  # getstatic to invokestatic
    0xb9: 5, 0xba: 5, 0xbb: 3, 0xbc: 2, 0xbd: 3,            # invokeinterface to anewarray
    0xbe: 1, 0xbf: 1, 0xc0: 3, 0xc1: 3, 0xc2: 1, 0xc3: 1,  # arraylength to monitorexit
    0xc5: 4, 0xc6: 3, 0xc7: 3, 0xc8: 5, 0xc9: 5,            # multianewarray to jsr_w
}

#: The opcodes the walk reads by name: ``ldc``, whose operand is one byte, ``iinc``, which ``wide``
#: widens to six bytes, and the three measured where they are met.
_LDC, _IINC, _TABLESWITCH, _LOOKUPSWITCH, _WIDE = 0x12, 0x84, 0xaa, 0xab, 0xc4

#: The instructions whose two-byte operand names a class entry: ``new``, ``anewarray``,
#: ``checkcast``, ``instanceof`` and ``multianewarray`` always, ``ldc_w`` when what it loads is one.
_CLASS_OPERAND = frozenset({0xbb, 0xbd, 0xc0, 0xc1, 0xc5, 0x13})

#: What ``wide`` may widen besides ``iinc``: the loads, the stores and ``ret``, each to four bytes.
_WIDENABLE = frozenset({*range(0x15, 0x1a), *range(0x36, 0x3b), 0xa9})


@dataclass(frozen=True)
class Graph:
    """The reference graph of one compiled tree, and what it was derived from."""

    #: Every top-level type declared in the scanned source roots, as a binary name.
    declared: frozenset[str]
    #: The types declared ``Subject.IGNORED``, whose outgoing edges do not compose.
    ignored: frozenset[str]
    #: The types each type references, keyed by the referring type.
    edges: dict[str, frozenset[str]]
    #: The artifacts each type can move, keyed by type.
    artifacts: dict[str, frozenset[str]]
    #: Each artifact's producer roots, as binary names.
    roots: dict[str, tuple[str, ...]]
    #: A digest over the class files the graph was derived from.
    compiled_digest: str


def _pool(data: bytes) -> tuple[list[object], int]:
    """The constant pool, indexed as the class file indexes it, and where the body starts.

    A ``CONSTANT_Class`` is kept as ``("class", name index)`` rather than resolved here, because the
    header below reads its own class, its superclass and its interfaces through exactly that
    indirection. A field, method or interface-method reference is kept as ``("member", class
    index)`` and a ``CONSTANT_String`` as ``("string", name index)``, because the permits reader
    asks which entries something other than a permits list points at, and each of those is one.
    Every other entry is stepped over.

    :param data the class file's bytes
    :returns the pool and the offset of ``access_flags``, or an empty pool when it is not a class file
    :throws MissingInput if the pool carries a tag this reader has no width for
    """
    if data[:4] != b"\xca\xfe\xba\xbe":
        return [], 0
    count = struct.unpack(">H", data[8:10])[0]
    entries: list[object] = [None] * (count + 1)
    offset, index = 10, 1
    while index < count:
        tag = data[offset]
        offset += 1
        if tag == 1:
            length = struct.unpack(">H", data[offset:offset + 2])[0]
            entries[index] = data[offset + 2:offset + 2 + length].decode("utf-8", "replace")
            offset += 2 + length
        elif tag == 7:
            entries[index] = ("class", struct.unpack(">H", data[offset:offset + 2])[0])
            offset += 2
        elif tag == 8:
            entries[index] = ("string", struct.unpack(">H", data[offset:offset + 2])[0])
            offset += 2
        elif tag in (9, 10, 11):
            entries[index] = ("member", struct.unpack(">H", data[offset:offset + 2])[0])
            offset += 4
        elif tag in _FIXED_WIDTH:
            offset += _FIXED_WIDTH[tag]
        elif tag in _TWO_SLOT:
            offset += 8
            index += 1
        else:
            raise MissingInput(f"unknown constant-pool tag '{tag}' at offset '{offset}'")
        index += 1
    return entries, offset


def utf8_entries(data: bytes) -> list[str]:
    """Every ``CONSTANT_Utf8`` entry of a class file, which is where every type name is spelled.

    :param data the class file's bytes
    :returns the pool's string entries, empty when the bytes are not a class file
    :throws MissingInput if the pool carries a tag this reader has no width for
    """
    entries, _ = _pool(data)
    return [entry for entry in entries if isinstance(entry, str)]


def edge_strings(data: bytes) -> list[str]:
    """Every pool string a class file names a type through - every one but a permits list's.

    A sealed type's ``PermittedSubclasses`` attribute names each permitted subtype, and the name is
    no reference: listing a subtype runs none of its code, and read as an edge it makes everything
    that reaches the supertype reach every subtype. A listed name is passed over when nothing else in
    the file references the same class - no member reference, no class operand of an instruction,
    catch type, stack-map entry or bootstrap argument, no header or ``throws`` slot - and no string
    constant shares it. A descriptor or a signature naming the subtype is a string of its own and is
    read as one, so only the listing goes.

    A compile-time constant read from a permitted subtype is the one use this cannot tell from the
    listing: javac inlines the value and keeps only the class entry the listing already holds.

    :param data the class file's bytes
    :returns the pool's string entries less the names only a permits list gives, empty when the
        bytes are not a class file
    :throws MissingInput if the pool carries a tag, a method body an opcode or a stack map an entry
        this reader has no width for, or a walk does not end where its attribute does
    """
    entries, offset = _pool(data)
    if not entries:
        return []
    listed, inner, used = _class_sites(data, entries, offset)

    def name_index(index: int) -> int | None:
        entry = entries[index] if 0 < index < len(entries) else None
        return entry[1] if isinstance(entry, tuple) and entry[0] == "class" else None

    only = frozenset(index for index in listed if index not in used)
    # The InnerClasses entry javac writes for a listed type nested in another file is part of the
    # listing, and so is the outer class entry it adds - unless something else names that one, or
    # another InnerClasses entry names it for a type that is not passed over.
    outers = {outer for nested, outer in inner if outer and nested in only} - set(listed) - used
    passed = only | {outer for outer in outers
                     if all(nested in only and named == outer
                            for nested, named in inner if outer in (nested, named))}
    kept = {entry[1] for index, entry in enumerate(entries) if isinstance(entry, tuple)
            and (entry[0] == "string" or (entry[0] == "class" and index not in passed))}
    dropped = {name_index(index) for index in passed} - kept
    return [entry for index, entry in enumerate(entries)
            if isinstance(entry, str) and index not in dropped]


def _class_sites(data: bytes, entries: list[object], offset: int) \
        -> tuple[list[int], list[tuple[int, int]], set[int]]:
    """Every place one class file names a class entry, walked from ``access_flags`` to its end.

    The header's own class, superclass and interfaces, and every member reference's class; per field
    and method, its ``Exceptions`` slots and its ``Code`` - each instruction decoded at its JVMS 6.5
    width, the two switches padded to four bytes from the method's first instruction and ``wide``
    sized by what it widens, the exception table's catch types and every ``Object`` entry of the
    ``StackMapTable``; then the class attributes ``PermittedSubclasses``, ``InnerClasses``,
    ``BootstrapMethods``, ``EnclosingMethod``, ``NestHost`` and ``NestMembers``. Every other
    attribute is stepped over by its length, none of them naming a class entry outside a module
    declaration.

    A walk that reads one instruction at the wrong width loses step and reports fewer uses rather
    than failing - the pool reader's own classic defect, one level down - so an opcode or a stack-map
    type with no known width refuses rather than guessing one, and so does a walk that does not end
    where its method body or its stack map does.

    :param data the class file's bytes
    :param entries the pool, as :func:`_pool` keeps it
    :param offset where ``access_flags`` starts
    :returns the class entries the permits list names, each ``InnerClasses`` entry's inner and
        outer class entries, and every class entry referenced anywhere else
    :throws MissingInput if a method body carries an opcode, or a stack map a frame or entry type,
        this reader has no width for, or a walk does not end where its attribute does
    """
    def u2(at: int) -> int:
        return struct.unpack(">H", data[at:at + 2])[0]

    def u4(at: int) -> int:
        return struct.unpack(">I", data[at:at + 4])[0]

    def s4(at: int) -> int:
        return struct.unpack(">i", data[at:at + 4])[0]

    def kind(index: int) -> str | None:
        entry = entries[index] if 0 < index < len(entries) else None
        return entry[0] if isinstance(entry, tuple) else None

    def utf8(index: int) -> str:
        entry = entries[index] if 0 < index < len(entries) else None
        return entry if isinstance(entry, str) else ""

    listed: list[int] = []
    inner: list[tuple[int, int]] = []
    used: set[int] = {entry[1] for entry in entries
                      if isinstance(entry, tuple) and entry[0] == "member"}

    def verification_type(at: int) -> int:
        tag = data[at]
        if tag == 7:
            used.add(u2(at + 1))
        elif tag > 8:
            raise MissingInput(f"unknown stack-map entry type '{tag}' at offset '{at}'")
        return at + (3 if tag in (7, 8) else 1)

    def stack_map(start: int, length: int) -> None:
        position = start + 2
        for _ in range(u2(start)):
            frame = data[position]
            position += 1
            if 64 <= frame <= 127:
                position = verification_type(position)
            elif frame == 247:
                position = verification_type(position + 2)
            elif 248 <= frame <= 251:
                position += 2
            elif 252 <= frame <= 254:
                position += 2
                for _ in range(frame - 251):
                    position = verification_type(position)
            elif frame == 255:
                position += 2
                for _ in range(2):          # the locals, then the stack
                    count = u2(position)
                    position += 2
                    for _ in range(count):
                        position = verification_type(position)
            elif frame > 63:
                raise MissingInput(
                    f"unknown stack-map frame type '{frame}' at offset '{position - 1}'")
        if position != start + length:
            raise MissingInput(
                f"a stack map read to offset '{position}' and ends at '{start + length}'")

    def code(start: int) -> int:
        length = u4(start + 4)
        first = start + 8
        pc = 0
        while pc < length:
            at = first + pc
            opcode = data[at]
            if opcode in (_TABLESWITCH, _LOOKUPSWITCH):
                # Padded so the operands start a multiple of four from the method's first byte.
                operands = at + 1 + (3 - pc % 4)
                if opcode == _TABLESWITCH:
                    cases = s4(operands + 8) - s4(operands + 4) + 1
                    width = operands - at + 12 + 4 * cases
                else:
                    cases = s4(operands + 4)
                    width = operands - at + 8 + 8 * cases
                if cases < 0:
                    raise MissingInput(f"a switch of '{cases}' cases at offset '{at}'")
            elif opcode == _WIDE:
                widened = data[at + 1]
                if widened != _IINC and widened not in _WIDENABLE:
                    raise MissingInput(f"'wide' over opcode '{widened}' at offset '{at}'")
                width = 6 if widened == _IINC else 4
            elif opcode in _OPCODE_WIDTH:
                width = _OPCODE_WIDTH[opcode]
                if opcode == _LDC and kind(data[at + 1]) == "class":
                    used.add(data[at + 1])
                elif opcode in _CLASS_OPERAND and kind(u2(at + 1)) == "class":
                    used.add(u2(at + 1))
            else:
                raise MissingInput(f"unknown opcode '{opcode}' at offset '{at}'")
            pc += width
        if pc != length:
            raise MissingInput(
                f"a method body read to offset '{first + pc}' and ends at '{first + length}'")
        position = first + length
        handlers = u2(position)
        for slot in range(handlers):
            used.add(u2(position + 8 + 8 * slot))       # catch_type, after start, end and handler
        return attributes(position + 2 + 8 * handlers)

    def attributes(position: int) -> int:
        count = u2(position)
        position += 2
        for _ in range(count):
            name = utf8(u2(position))
            length = u4(position + 2)
            body = position + 6
            if name == "Code":
                code(body)
            elif name == "StackMapTable":
                stack_map(body, length)
            elif name == _PERMITTED:
                listed.extend(u2(body + 2 + 2 * slot) for slot in range(u2(body)))
            elif name in ("Exceptions", "NestMembers"):
                used.update(u2(body + 2 + 2 * slot) for slot in range(u2(body)))
            elif name == "InnerClasses":
                # inner, outer, simple name and flags, two bytes each
                slots = range(body + 2, body + 2 + 8 * u2(body), 8)
                inner.extend((u2(at), u2(at + 2)) for at in slots)
            elif name in ("EnclosingMethod", "NestHost"):
                used.add(u2(body))
            elif name == "BootstrapMethods":
                at = body + 2
                for _ in range(u2(body)):
                    arguments = [u2(at + 4 + 2 * slot) for slot in range(u2(at + 2))]
                    used.update(argument for argument in arguments if kind(argument) == "class")
                    at += 4 + 2 * len(arguments)
            position = body + length
        return position

    used.update((u2(offset + 2), u2(offset + 4)))
    position = offset + 8
    for _ in range(u2(offset + 6)):
        used.add(u2(position))
        position += 2
    # fields[] then methods[], which share a shape: access_flags, name, descriptor, attributes.
    for _ in range(2):
        members = u2(position)
        position += 2
        for _ in range(members):
            position = attributes(position + 6)
    attributes(position)
    used.discard(0)
    return listed, inner, used


@dataclass(frozen=True)
class Surface:
    """What a class file DECLARES, as against what it merely mentions somewhere in its pool.

    The declaration is its own name, its supertypes and every field and method descriptor and generic
    signature - the shape a caller compiles against. Everything else a class file names it names in a
    method BODY, and the difference is what tells a declared capability from an exercised one.
    """

    #: The types the declaration mentions, as they are spelled in the pool.
    types: frozenset[str]
    #: Whether the file declares an interface, whose members are capabilities rather than calls.
    is_interface: bool


def signature_surface(data: bytes) -> Surface:
    """Read one class file's declaration surface.

    :param data the class file's bytes
    """
    entries, offset = _pool(data)
    if not entries:
        return Surface(types=frozenset(), is_interface=False)

    def utf8(index: int) -> str:
        entry = entries[index] if 0 < index < len(entries) else None
        return entry if isinstance(entry, str) else ""

    def class_name(index: int) -> str:
        entry = entries[index] if 0 < index < len(entries) else None
        return utf8(entry[1]) if isinstance(entry, tuple) and entry[0] == "class" else ""

    flags = struct.unpack(">H", data[offset:offset + 2])[0]
    found = {class_name(struct.unpack(">H", data[offset + 2:offset + 4])[0]),
             class_name(struct.unpack(">H", data[offset + 4:offset + 6])[0])}
    total = struct.unpack(">H", data[offset + 6:offset + 8])[0]
    position = offset + 8
    for _ in range(total):
        found.add(class_name(struct.unpack(">H", data[position:position + 2])[0]))
        position += 2

    # fields[] then methods[], which share a shape: access_flags, name, descriptor, attributes.
    for _ in range(2):
        members = struct.unpack(">H", data[position:position + 2])[0]
        position += 2
        for _ in range(members):
            found.add(utf8(struct.unpack(">H", data[position + 4:position + 6])[0]))
            attributes = struct.unpack(">H", data[position + 6:position + 8])[0]
            position += 8
            for _ in range(attributes):
                name = utf8(struct.unpack(">H", data[position:position + 2])[0])
                length = struct.unpack(">I", data[position + 2:position + 6])[0]
                if name == "Signature":
                    found.add(utf8(struct.unpack(">H", data[position + 6:position + 8])[0]))
                elif name == "Exceptions":
                    thrown = struct.unpack(">H", data[position + 6:position + 8])[0]
                    for slot in range(thrown):
                        found.add(class_name(struct.unpack(
                            ">H", data[position + 8 + 2 * slot:position + 10 + 2 * slot])[0]))
                position += 6 + length
    return Surface(types=frozenset(text for text in found if text),
                   is_interface=bool(flags & _ACC_INTERFACE))


def source_paths(base: Path) -> list[str]:
    """Every compilation unit in the scanned source roots that declares a type, repo-relative.

    :param base the repository root
    """
    out: list[str] = []
    for source_root in SOURCE_ROOTS:
        root = base / source_root
        if not root.is_dir():
            continue
        out.extend(path.relative_to(base).as_posix() for path in root.rglob("*.java")
                   if path.name != "package-info.java")
    return sorted(out)


def declared_types(base: Path) -> frozenset[str]:
    """Every top-level type in the scanned source roots, as a binary name.

    :param base the repository root
    """
    return frozenset(to_binary(path) for path in source_paths(base))


def owning_type(binary_name: str, declared: frozenset[str]) -> str | None:
    """The top-level type a binary name belongs to, folding nested, anonymous and lambda classes.

    :param binary_name a slash-form name, possibly carrying a ``$`` suffix
    :param declared the types that may be answered
    """
    outer = binary_name.split("$")[0]
    return outer if outer in declared else None


def to_binary(path: str) -> str | None:
    """The binary name of a repo-relative ``.java`` path, or nothing when it is not a scanned one.

    :param path a repo-relative path in either separator
    """
    text = path.replace("\\", "/")
    if not text.endswith(".java") or text.endswith("package-info.java"):
        return None
    for source_root in SOURCE_ROOTS:
        prefix = f"{source_root}/"
        if text.startswith(prefix):
            return text[len(prefix):-len(".java")]
    return None


def _resolve_roots(declared: frozenset[str]) -> dict[str, tuple[str, ...]]:
    """Each artifact's roots as binary names, refusing a root the tree does not declare."""
    by_simple: dict[str, str] = {}
    for name in sorted(declared):
        by_simple.setdefault(name.rsplit("/", 1)[1], name)
    out: dict[str, tuple[str, ...]] = {}
    for artifact, simple_names in ROOTS.items():
        resolved: list[str] = []
        for simple in simple_names:
            found = by_simple.get(simple)
            if found is None:
                raise MissingInput(f"artifact '{artifact}' roots at '{simple}', which is not declared")
            resolved.append(found)
        out[artifact] = tuple(resolved)
    return out


def _edges(base: Path, declared: frozenset[str]) \
        -> tuple[dict[str, frozenset[str]], dict[str, frozenset[str]], frozenset[str], str]:
    """The reference graph, each type's declaration surface, the interfaces, and a tree digest.

    The surface is accumulated over every class file folded onto a type, nested ones included, since
    a nested type's own descriptors are as much a declaration as its outer's. The interface flag is
    read from the TOP-LEVEL file alone: a nested class inside an interface is still a class, and it
    is the outer type that a seam declaration names.
    """
    building: dict[str, set[str]] = defaultdict(set)
    surfaces: dict[str, set[str]] = defaultdict(set)
    interfaces: set[str] = set()
    digest = hashlib.sha256()
    seen = 0
    for class_root in CLASS_ROOTS:
        root = base / class_root
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("*.class")):
            relative = path.relative_to(root).with_suffix("").as_posix()
            owner = owning_type(relative, declared)
            if owner is None:
                continue
            seen += 1
            data = path.read_bytes()
            digest.update(relative.encode())
            digest.update(hashlib.sha256(data).digest())
            surface = signature_surface(data)
            if relative == owner and surface.is_interface:
                interfaces.add(owner)
            # A sealed type's permits list names every subtype it permits and runs none of them, so
            # a name only the listing gives is no edge; every other naming of the subtype still is.
            for entry in edge_strings(data):
                for reference in _REFERENCE.findall(entry):
                    target = owning_type(reference, declared)
                    if target is not None and target != owner:
                        building[owner].add(target)
            for entry in surface.types:
                for reference in _REFERENCE.findall(entry):
                    target = owning_type(reference, declared)
                    if target is not None and target != owner:
                        surfaces[owner].add(target)
    if not seen:
        raise MissingInput("no class files found - run './gradlew compileJava compileTestJava'")
    return ({name: frozenset(targets) for name, targets in building.items()},
            {name: frozenset(targets) for name, targets in surfaces.items()},
            frozenset(interfaces), digest.hexdigest())


def forward(start: str, edges: dict[str, frozenset[str]]) -> set[str]:
    """Every type transitively referenced from ``start``, excluding it.

    :param start the type to walk from
    :param edges the reference graph
    """
    seen: set[str] = set()
    stack = [start]
    while stack:
        for target in edges.get(stack.pop(), ()):
            if target not in seen:
                seen.add(target)
                stack.append(target)
    seen.discard(start)
    return seen


def chain(start: str, goal: str, edges: dict[str, frozenset[str]]) -> list[str] | None:
    """The shortest reference chain from ``start`` to ``goal``, or nothing when unconnected.

    :param start the type to walk from
    :param goal the type to reach
    :param edges the reference graph
    """
    previous: dict[str, str | None] = {start: None}
    queue = deque([start])
    while queue:
        current = queue.popleft()
        if current == goal:
            out: list[str] = []
            node: str | None = current
            while node is not None:
                out.append(node)
                node = previous[node]
            return list(reversed(out))
        for target in sorted(edges.get(current, ())):
            if target not in previous:
                previous[target] = current
                queue.append(target)
    return None


def ignored_types(base: Path, declared: frozenset[str]) -> frozenset[str]:
    """Every type declaring ``ignored = true``, read from source as every declaration is.

    :param base the repository root
    :param declared the types that may be answered
    """
    scan = declarations_mod.scan(base)
    out: set[str] = set()
    for declaration in scan.declarations:
        if not declaration.ignored or declaration.on == "package":
            continue
        binary = to_binary(declaration.path)
        if binary in declared:
            out.add(binary)
    return frozenset(out)


def build(base: Path) -> Graph:
    """Derive the whole reach graph from a compiled tree.

    :param base the repository root
    :throws MissingInput if the tree is not compiled, or a declared root is missing
    """
    declared = declared_types(base)
    edges, surfaces, interfaces, digest = _edges(base, declared)
    ignored = ignored_types(base, declared)
    # Outgoing edges only. Reach stops composing THROUGH a wiring type, and a change TO one is still
    # seen by everything that reaches it - which is what keeps a defaulted interface member honest.
    #
    # What is cut depends on what the seam IS, and the two answers are the same sentence read at two
    # kinds of type. An INTERFACE declares capabilities: its members' descriptors put every type they
    # mention in the pool whether or not anything calls them, which is the collapse, and an abstract
    # member cannot change alone because every implementor moves with it. Its default BODIES are not
    # that - they are code, with no implementor to carry a change, so what they call is kept. A CLASS
    # has no such split: every reference it holds is one it makes, so it is cut whole.
    #
    # Measured. Cutting the interfaces by declaration alone moves two types and no others, each of
    # them reached from a default body; cutting the concrete context that way instead collapses the
    # graph, from 29 engine-wide types to 151.
    edges = {name: (targets - surfaces.get(name, frozenset()) if name in interfaces
                    else frozenset()) if name in ignored else targets
             for name, targets in edges.items()}
    roots = _resolve_roots(declared)
    artifacts: dict[str, set[str]] = defaultdict(set)
    for artifact, entry_points in roots.items():
        touched: set[str] = set()
        for entry in entry_points:
            touched.add(entry)
            touched |= forward(entry, edges)
        for name in touched:
            artifacts[name].add(artifact)
    return Graph(declared=declared, ignored=ignored, edges=edges,
                 artifacts={name: frozenset(found) for name, found in artifacts.items()},
                 roots=roots, compiled_digest=digest)


def of(graph: Graph, paths: list[str]) -> dict[str, list[str]]:
    """The artifacts each given path reaches, keyed by the path as it was given.

    A path that is not a scanned Java source answers nothing rather than an empty reach, because the
    blindness map is what answers it and an empty list here would read as a licensed narrowing.

    :param graph a derived graph
    :param paths repo-relative paths
    """
    out: dict[str, list[str]] = {}
    for path in paths:
        binary = to_binary(path)
        if binary is None or binary not in graph.declared:
            continue
        out[path] = sorted(graph.artifacts.get(binary, frozenset()))
    return out


def answered_by(payload: dict, path: str) -> list[str] | None:
    """What a committed graph says one repo-relative path reaches, or nothing when it cannot answer.

    The reader a derived blindness rule resolves through, and it answers off the COMMITTED file
    rather than off a freshly walked tree. A graph derived at plan time is whatever was last
    compiled, which is the one way this scheduling can be quietly wrong rather than loudly stale;
    ``reach check`` on a verification run is what holds the committed file to the tree instead.

    Two shapes under a source root answer the empty list rather than nothing, each because no class
    file anywhere can reference it. A ``package-info.java`` declares no type, and what it does carry
    - a package's own declaration - moves this map's trigger paths rather than any render. A
    ``doc-files`` directory is javadoc's own reserved name: javac passes over it and the doclet copies
    it verbatim, so what sits there is illustration rather than input. Anything else under a source
    root is refused, a new type and a shipped resource each needing an answer somebody wrote down.

    :param payload: a committed graph, as :func:`to_payload` writes one
    :param path: a repo-relative path in either separator
    """
    text = path.replace("\\", "/")
    if any(text.startswith(f"{root}/") for root in SOURCE_ROOTS) and (
            text.endswith("/package-info.java") or "/doc-files/" in text):
        return []
    binary = to_binary(text)
    if binary is None:
        return None
    row = (payload.get("types") or {}).get(binary)
    return None if row is None else list(row.get("artifacts", ()))


def orphans(graph: Graph) -> list[str]:
    """Every declared type no producer root reaches, which is what a declaration has to answer for.

    :param graph a derived graph
    """
    return sorted(name for name in graph.declared if not graph.artifacts.get(name))


def declared_reach(base: Path, declared: frozenset[str]) -> dict[str, tuple[str, ...]]:
    """Each type's own declared reach, read from source as every declaration is.

    A reach is a declaration of its OWN, naming a subject and no claim. A subject written beside a
    claim decorates that claim - it says which renderers the claim is about - and reading one as a
    reach would take a statement about a blindness rule for a statement about a type. A type
    carrying both writes both, which is two facts rather than one overloaded member.

    :param base the repository root
    :param declared the types that may be answered
    """
    out: dict[str, tuple[str, ...]] = {}
    for declaration in declarations_mod.scan(base).declarations:
        if declaration.on == "package" or declaration.claim or declaration.joins:
            continue
        binary = to_binary(declaration.path)
        if declaration.subject and binary in declared:
            out[binary] = declaration.subject
    return out


def unexplained(base: Path, graph: Graph) -> list[str]:
    """Every LIBRARY type that reaches nothing and says nothing about it.

    A type no producer root reaches answers the empty set, and two very different things look like
    that: a renderer the store holds no artifact for by decision, and a type the graph cannot see an
    edge to - reached only across a wiring seam, or built by a service loader out of a file no
    constant pool mentions. The first is correct and the second is a gate quietly not running, and
    nothing derived can tell them apart, so the type says which and this refuses one that does not.

    Scoped to the library's own source root. A test class is reached by a producer root only when it
    IS one, so every other test in the tree answers nothing by construction, and asking each of them
    to say so would be asking for a declaration per assertion.

    :param base the repository root
    :param graph a derived graph
    """
    explained = declared_reach(base, graph.declared)
    root = base / SOURCE_ROOTS[0]
    return sorted(name for name in orphans(graph)
                  if name not in explained and (root / f"{name}.java").is_file())


def self_demotions(payload: dict, rules: Sequence[Rule], paths: Iterable[str],
                   held: Mapping[str, frozenset[str]] = HELD_DEMOTES) -> list[str]:
    """Every path on which a held demote and its ledger disagree, one line each.

    A carrier is a path the demoting rule fires on, so a type is held whether its own declaration,
    its package's or an authored trigger put it under the rule. What it reaches is the graph's
    answer for that path. A carrier reaching an artifact the demote subtracts is named unless the
    claim's ledger lists it, and a listed path is named once it no longer reaches one or is no
    longer a carrier at all, so the ledger stays exactly the carriers that lose an artifact by
    decision. A path the graph has no row for reaches nothing here, being a type the graph
    predates, which the comparison of the graph against the tree already names.

    A held claim that no demoting rule carries, or that fires on no source path, is refused rather
    than passed: a renamed slug or a moved carrier would otherwise leave this holding nothing and
    reporting that nothing is wrong.

    :param payload a graph, as :func:`to_payload` writes one
    :param rules the map's rules, each carrying the trigger paths the tree derives
    :param paths the repo-relative source paths a rule may fire on
    :param held each held claim, mapped to the carriers allowed to reach what it subtracts
    :returns one line per unlisted carrier reaching what its demote subtracts and per listed path
        that no longer does, sorted, empty when every ledger agrees with the tree
    :throws MissingInput if a held claim is carried by no demoting rule, or fires on no source path
    """
    candidates = sorted(paths)
    out: list[str] = []
    for claim, listed in held.items():
        demoting = [rule for rule in rules if rule.claim_key == claim and rule.mode == "demote"]
        if not demoting:
            raise MissingInput(
                f"the held demote '{claim}' is carried by no demoting rule in the map")
        fired: set[str] = set()
        reaching: set[str] = set()
        for rule in demoting:
            carriers = [path for path in candidates if matches(path, rule.trigger_paths)]
            if not carriers:
                raise MissingInput(
                    f"the held demote '{claim}' ({rule.id}) fires on no scanned source path")
            fired.update(carriers)
            for path in carriers:
                subtracted = sorted(set(answered_by(payload, path) or ()) & set(rule.blind))
                if not subtracted:
                    continue
                reaching.add(path)
                if path not in listed:
                    out.append(f"{path}: reaches {', '.join(subtracted)}, which {rule.id} "
                               f"'{claim}' subtracts, and HELD_DEMOTES does not list it")
        for path in sorted(listed - reaching):
            state = ("reaches nothing that demote subtracts" if path in fired
                     else "is not one of that demote's carriers")
            out.append(f"{path}: HELD_DEMOTES lists it under '{claim}', and it {state}")
    return sorted(out)


def to_payload(graph: Graph) -> dict:
    """The stored form of a graph, for the committed reach file.

    Carries no digest of the tree it came from, deliberately. A class-file digest moves on every
    commit that changes any code at all, so storing it would churn this file on changes that move no
    reach and bury the diffs that do. What guards staleness is the comparison itself: ``check``
    re-derives from a freshly compiled tree and reports the map's own difference.

    :param graph a derived graph
    """
    return {
        "format": 1,
        "kind": "class-reach",
        "ignored": sorted(graph.ignored),
        "roots": {artifact: list(names) for artifact, names in sorted(graph.roots.items())},
        "types": {name: {"artifacts": sorted(graph.artifacts.get(name, frozenset())),
                         "source": "derived"}
                  for name in sorted(graph.declared)},
    }


def differences(stored: dict, derived: dict) -> list[str]:
    """What moved between a committed graph and a freshly derived one, as one line per type.

    :param stored the committed payload
    :param derived the payload just derived
    :returns the moved types, sorted, empty when the two agree
    """
    was = {name: row.get("artifacts", []) for name, row in (stored.get("types") or {}).items()}
    now = {name: row.get("artifacts", []) for name, row in (derived.get("types") or {}).items()}
    moved: list[str] = []
    for name in sorted(set(was) | set(now)):
        if name not in was:
            moved.append(f"+ {name}: {', '.join(now[name]) or '(none)'}")
        elif name not in now:
            moved.append(f"- {name}")
        elif was[name] != now[name]:
            moved.append(f"~ {name}: {', '.join(was[name]) or '(none)'} "
                         f"-> {', '.join(now[name]) or '(none)'}")
    if (stored.get("roots") or {}) != (derived.get("roots") or {}):
        moved.append("~ roots")
    return moved
