package dev.sbs.renderer.gradle;

import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import dev.sbs.renderer.exception.AssetPipelineException;
import dev.sbs.renderer.model.Block;
import dev.sbs.renderer.pipeline.AssetPipelineOptions;
import dev.sbs.renderer.pipeline.ClientJarDownloader;
import dev.sbs.renderer.pipeline.HttpFetcher;
import dev.sbs.renderer.pipeline.VanillaTintsLoader;
import dev.sbs.renderer.pipeline.asm.BlockColorsParser;
import dev.simplified.collection.ConcurrentMap;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Entry point invoked by the {@code generateVanillaTints} Gradle task.
 * <p>
 * Downloads (or reuses the cached) MC 26.1 client jar, runs
 * {@link BlockColorsParser} over its {@code BlockColors} class, and writes the resulting tint
 * table to {@code src/main/resources/renderer/vanilla_tints.json}. The runtime pipeline reads
 * the JSON via {@link VanillaTintsLoader VanillaTintsLoader} so the ASM walker is never on the
 * production classpath - the only people who run it are developers bumping the bundled tint
 * snapshot when a new Minecraft version ships.
 * <p>
 * The output file format mirrors the loader's expectations: a top-level {@code tints} array of
 * {@code {block, target, constant?}} objects, with constants stored as {@code 0x}-prefixed
 * uppercase hex strings (Gson cannot round-trip {@code 0x80000000}-class signed integers
 * literally).
 */
@UtilityClass
public final class GenerateVanillaTintsMain {

    private static final @NotNull Path OUTPUT_PATH = Path.of("src/main/resources/renderer/vanilla_tints.json");

    /**
     * Runs the generator.
     *
     * @param args ignored - the output path is fixed to keep the resource location stable
     * @throws IOException if writing the JSON file fails
     */
    public static void main(String @NotNull [] args) throws IOException {
        AssetPipelineOptions options = AssetPipelineOptions.defaults();
        Path jarPath;
        try {
            jarPath = ClientJarDownloader.download(options, new HttpFetcher());
        } catch (AssetPipelineException ex) {
            System.err.println("Failed to download client jar for vanilla tints generation: " + ex.getMessage());
            throw ex;
        }
        System.out.println("Parsing BlockColors from " + jarPath);

        ConcurrentMap<String, Block.Tint> tints = BlockColorsParser.parse(jarPath);
        System.out.println("Parser produced " + tints.size() + " block tint entries");

        Files.createDirectories(OUTPUT_PATH.getParent());
        Files.writeString(OUTPUT_PATH, buildJson(tints, options.getVersion()));
        System.out.println("Wrote " + OUTPUT_PATH.toAbsolutePath());
    }

    /**
     * Serialises the parsed tint list into the bundled JSON format. The header comment notes
     * the source jar version so a future contributor can tell at a glance how stale the snapshot
     * is.
     */
    private static @NotNull String buildJson(@NotNull ConcurrentMap<String, Block.Tint> tints, @NotNull String mcVersion) {
        JsonObject root = new JsonObject();
        root.addProperty("//", "Generated by GenerateVanillaTintsMain from net.minecraft.client.color.block.BlockColors$createDefault() in MC " + mcVersion + ". Run the 'generateVanillaTints' Gradle task to refresh.");
        root.addProperty("source_version", mcVersion);

        JsonArray entries = new JsonArray();
        tints.forEach((blockId, tint) -> {
            JsonObject entry = new JsonObject();
            entry.addProperty("block", blockId);
            entry.addProperty("target", tint.target().name());
            tint.constant().ifPresent(value -> entry.addProperty("constant", String.format("0x%08X", value)));
            entries.add(entry);
        });
        root.add("tints", entries);

        return new GsonBuilder().setPrettyPrinting().create().toJson(root) + System.lineSeparator();
    }

}
