package dev.sbs.renderer.gradle;

import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import dev.sbs.renderer.exception.AssetPipelineException;
import dev.sbs.renderer.model.ColorMap;
import dev.sbs.renderer.pipeline.AssetPipelineOptions;
import dev.sbs.renderer.pipeline.client.ClientJarDownloader;
import dev.sbs.renderer.pipeline.client.ClientJarExtractor;
import dev.sbs.renderer.pipeline.client.HttpFetcher;
import dev.sbs.renderer.pipeline.parser.ColorMapParser;
import dev.simplified.collection.ConcurrentList;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Base64;

/**
 * Entry point invoked by the {@code generateColorMaps} Gradle task.
 * <p>
 * Downloads (or reuses the cached) MC client jar, extracts the vanilla assets, reads the three
 * biome colormap PNGs via {@link ColorMapParser}, and writes the pixel data to
 * {@code src/main/resources/renderer/color_maps.json}. The runtime pipeline reads the JSON via
 * {@link dev.sbs.renderer.pipeline.loader.ColorMapLoader ColorMapLoader} so the PNG reading step
 * only runs during development when a new Minecraft version ships.
 */
@UtilityClass
public final class GenerateColorMapsMain {

    private static final @NotNull Path OUTPUT_PATH = Path.of("src/main/resources/renderer/color_maps.json");

    public static void main(String @NotNull [] args) throws IOException {
        AssetPipelineOptions options = AssetPipelineOptions.defaults();
        HttpFetcher fetcher = new HttpFetcher();

        Path jarPath;
        try {
            jarPath = ClientJarDownloader.download(options, fetcher);
        } catch (AssetPipelineException ex) {
            System.err.println("Failed to download client jar: " + ex.getMessage());
            throw ex;
        }

        Path packRoot = options.getCacheRoot().toPath().resolve("vanilla").resolve(options.getVersion());
        ClientJarExtractor.extract(jarPath, packRoot);

        ConcurrentList<ColorMap> colorMaps = ColorMapParser.parse(packRoot);
        System.out.println("Parsed " + colorMaps.size() + " colormaps");

        Files.createDirectories(OUTPUT_PATH.getParent());
        Files.writeString(OUTPUT_PATH, buildJson(colorMaps, options.getVersion()));
        System.out.println("Wrote " + OUTPUT_PATH.toAbsolutePath());
    }

    private static @NotNull String buildJson(@NotNull ConcurrentList<ColorMap> colorMaps, @NotNull String mcVersion) {
        JsonObject root = new JsonObject();
        root.addProperty("//", "Generated by GenerateColorMapsMain from MC " + mcVersion + " biome colormaps. Run the \\'generateColorMaps\\' Gradle task to refresh.");
        root.addProperty("source_version", mcVersion);

        JsonArray entries = new JsonArray();
        for (ColorMap colorMap : colorMaps) {
            JsonObject entry = new JsonObject();
            entry.addProperty("type", colorMap.getType().name());
            entry.addProperty("pixels", Base64.getEncoder().encodeToString(colorMap.getPixels()));
            entries.add(entry);
        }
        root.add("color_maps", entries);

        return new GsonBuilder().setPrettyPrinting().create().toJson(root) + System.lineSeparator();
    }

}
