package lib.minecraft.renderer.pipeline.load.block;

import com.google.gson.JsonObject;
import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentMap;
import lib.minecraft.renderer.exception.PipelineException;
import lib.minecraft.renderer.pipeline.load.BundledResources;
import lib.minecraft.renderer.pipeline.load.ResourceDocument;
import lib.minecraft.renderer.tooling.kernel.Diagnostics;
import org.jetbrains.annotations.NotNull;

import java.util.HashMap;

/**
 * The reader for the block-to-item alias map.
 *
 * <p>{@code block_items.json} carries an {@code aliases{}} object mapping each secondary block id (a
 * block that owns no item of its own - a wall banner, a wall skull / head, a filled cauldron,
 * {@code big_dripleaf_stem}) to the standing block id whose item both share, generated by
 * {@code ToolingBlockItems} from the vanilla {@code Items} registry. The runtime uses it so an
 * aliased block's inventory icon poses through the shared item's {@code display.gui} rather than the
 * default iso pose, matching the in-game inventory.
 */
public final class BlockItemsReader {

    private static final @NotNull String RESOURCE_NAME = "block_items.json";

    private BlockItemsReader() {}

    /**
     * Reads the secondary-to-standing block-item alias map from {@code block_items.json}.
     *
     * @param diagnostics the scope envelope warnings are recorded to
     * @return secondary block id to the standing block id whose item it shares, wrapped unmodifiable;
     *     blocks that own their own item are absent
     * @throws PipelineException if the resource is missing or has no {@code aliases} object
     */
    public static @NotNull ConcurrentMap<String, String> load(@NotNull Diagnostics diagnostics) {
        ResourceDocument document = BundledResources.read(RESOURCE_NAME, BundledResources.MissingPolicy.REQUIRED, diagnostics).orElseThrow();
        JsonObject root = document.payload().toGson().getAsJsonObject();
        if (!root.has("aliases"))
            throw new PipelineException("Block-items resource '%s' has no 'aliases' object", RESOURCE_NAME);

        JsonObject aliases = root.getAsJsonObject("aliases");
        HashMap<String, String> map = new HashMap<>();
        for (String secondaryId : aliases.keySet())
            map.put(secondaryId, aliases.get(secondaryId).getAsString());
        return Concurrent.adoptMap(map).toUnmodifiable();
    }
}
