package dev.sbs.renderer.pipeline.loader;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonSyntaxException;
import dev.sbs.renderer.asset.model.BlockModelData;
import dev.sbs.renderer.asset.model.ModelElement;
import dev.sbs.renderer.asset.model.ModelFace;
import dev.sbs.renderer.exception.AssetPipelineException;
import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentList;
import dev.simplified.collection.ConcurrentMap;
import dev.simplified.collection.linked.ConcurrentLinkedMap;
import dev.simplified.gson.GsonSettings;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Map;

/**
 * Loads block entity geometry from two bundled resources:
 * <ul>
 * <li>{@code /renderer/block_entity_block_models.json} - generated by
 *     {@code ToolingBlockEntityModels}, contains block model elements (from/to/faces with
 *     per-face UV) keyed by entity model id</li>
 * <li>{@code /renderer/block_entity_mappings.json} - hand-edited, maps block ids to their
 *     entity model id + entity texture path</li>
 * </ul>
 * The output is a flat map of block id to {@link BlockEntityEntry} carrying a populated
 * {@link BlockModelData} (with real {@link ModelElement elements}) and the entity texture
 * reference. These blocks render through the standard block model path
 * ({@link dev.sbs.renderer.kit.GeometryKit#buildFromElements}) with no entity model pipeline.
 */
@UtilityClass
public class BlockEntityModelLoader {

    private static final @NotNull String BLOCK_MODELS_PATH = "/renderer/block_entity_block_models.json";
    private static final @NotNull String MAPPINGS_PATH = "/renderer/block_entity_mappings.json";
    private static final @NotNull Gson GSON = GsonSettings.defaults().create();

    /**
     * Loads block entity geometry and wiring, producing a map of block id to model + texture.
     *
     * @return the loaded block entity entries keyed by block id
     * @throws AssetPipelineException if either resource is missing or cannot be parsed
     */
    public static @NotNull ConcurrentMap<String, BlockEntityEntry> load() {
        ConcurrentMap<String, JsonObject> blockModels = loadBlockModels();
        ConcurrentMap<String, BlockEntityEntry> result = Concurrent.newMap();

        // Read the mappings file to wire block ids to models + textures
        try (InputStream stream = BlockEntityModelLoader.class.getResourceAsStream(MAPPINGS_PATH)) {
            if (stream == null)
                throw new AssetPipelineException("Block entity mappings resource '%s' not found", MAPPINGS_PATH);

            String json = new String(stream.readAllBytes(), StandardCharsets.UTF_8);
            JsonObject root = GSON.fromJson(json, JsonObject.class);
            if (root == null)
                throw new AssetPipelineException("Block entity mappings resource '%s' is empty", MAPPINGS_PATH);

            for (Map.Entry<String, JsonElement> modelEntry : root.entrySet()) {
                String modelId = modelEntry.getKey();
                if (!modelEntry.getValue().isJsonArray()) continue;

                JsonObject blockModelJson = blockModels.get(modelId);
                if (blockModelJson == null) {
                    System.err.printf("  Warning: no block model for entity model '%s'%n", modelId);
                    continue;
                }

                for (JsonElement element : modelEntry.getValue().getAsJsonArray()) {
                    JsonObject obj = element.getAsJsonObject();
                    String blockId = obj.get("blockId").getAsString();
                    String textureId = obj.get("textureId").getAsString();

                    // Parse the primary model's elements
                    BlockModelData modelData = parseBlockModelData(blockModelJson, textureId);

                    // Merge composite parts (e.g. bed foot) with offset
                    if (obj.has("parts") && obj.get("parts").isJsonArray()) {
                        for (JsonElement partEl : obj.getAsJsonArray("parts")) {
                            JsonObject partObj = partEl.getAsJsonObject();
                            String partModelId = partObj.get("model").getAsString();
                            String partTexture = partObj.get("texture").getAsString();
                            float[] offset = new float[]{ 0, 0, 0 };
                            if (partObj.has("offset") && partObj.get("offset").isJsonArray()) {
                                com.google.gson.JsonArray off = partObj.getAsJsonArray("offset");
                                offset = new float[]{ off.get(0).getAsFloat(), off.get(1).getAsFloat(), off.get(2).getAsFloat() };
                            }

                            JsonObject partBlockModel = blockModels.get(partModelId);
                            if (partBlockModel == null) continue;
                            BlockModelData partData = parseBlockModelData(partBlockModel, partTexture);

                            // Merge part elements into the primary model, applying the offset
                            for (ModelElement partElem : partData.getElements()) {
                                float[] from = partElem.getFrom().clone();
                                float[] to = partElem.getTo().clone();
                                from[0] += offset[0]; from[1] += offset[1]; from[2] += offset[2];
                                to[0] += offset[0]; to[1] += offset[1]; to[2] += offset[2];

                                // Create a new element with the offset positions via Gson roundtrip
                                JsonObject elemJson = GSON.toJsonTree(partElem).getAsJsonObject();
                                JsonArray fromArr = new JsonArray(); fromArr.add(from[0]); fromArr.add(from[1]); fromArr.add(from[2]);
                                JsonArray toArr = new JsonArray(); toArr.add(to[0]); toArr.add(to[1]); toArr.add(to[2]);
                                elemJson.add("from", fromArr);
                                elemJson.add("to", toArr);
                                modelData.getElements().add(GSON.fromJson(elemJson, ModelElement.class));
                            }
                        }
                    }

                    // Detect multi-block models (any element extends beyond 0-16 on any axis)
                    boolean multiBlock = false;
                    for (ModelElement me : modelData.getElements()) {
                        if (me.getFrom()[0] < -0.1f || me.getFrom()[1] < -0.1f || me.getFrom()[2] < -0.1f ||
                            me.getTo()[0] > 16.1f || me.getTo()[1] > 16.1f || me.getTo()[2] > 16.1f) {
                            multiBlock = true;
                            break;
                        }
                    }

                    int iconRotation = obj.has("iconRotation") ? obj.get("iconRotation").getAsInt() : 0;
                    result.put(blockId, new BlockEntityEntry(modelData, textureId, modelId, iconRotation, multiBlock));
                }
            }
        } catch (IOException | JsonSyntaxException ex) {
            throw new AssetPipelineException(ex, "Failed to load block entity mappings '%s'", MAPPINGS_PATH);
        }

        return result;
    }

    /**
     * Reads the generated block model elements JSON.
     */
    private static @NotNull ConcurrentMap<String, JsonObject> loadBlockModels() {
        try (InputStream stream = BlockEntityModelLoader.class.getResourceAsStream(BLOCK_MODELS_PATH)) {
            if (stream == null)
                throw new AssetPipelineException("Block entity block models resource '%s' not found", BLOCK_MODELS_PATH);

            String json = new String(stream.readAllBytes(), StandardCharsets.UTF_8);
            JsonObject root = GSON.fromJson(json, JsonObject.class);
            if (root == null)
                throw new AssetPipelineException("Block entity block models resource '%s' is empty", BLOCK_MODELS_PATH);

            ConcurrentMap<String, JsonObject> models = Concurrent.newMap();
            for (Map.Entry<String, JsonElement> entry : root.entrySet()) {
                if (entry.getValue().isJsonObject() && entry.getValue().getAsJsonObject().has("elements"))
                    models.put(entry.getKey(), entry.getValue().getAsJsonObject());
            }
            return models;
        } catch (IOException | JsonSyntaxException ex) {
            throw new AssetPipelineException(ex, "Failed to load block entity block models '%s'", BLOCK_MODELS_PATH);
        }
    }

    /**
     * Parses a block model JSON object (with elements array) into a {@link BlockModelData},
     * including the texture variable binding so {@code #entity} resolves at render time.
     */
    private static @NotNull BlockModelData parseBlockModelData(@NotNull JsonObject json, @NotNull String textureId) {
        JsonObject modelJson = new JsonObject();

        // Copy elements
        if (json.has("elements"))
            modelJson.add("elements", json.getAsJsonArray("elements"));

        // Set texture variable: "entity" → "minecraft:entity/chest/normal" etc.
        // so #entity in face references resolves to the actual texture path.
        JsonObject textures = new JsonObject();
        textures.addProperty("entity", textureId);
        modelJson.add("textures", textures);

        return GSON.fromJson(modelJson, BlockModelData.class);
    }

    /**
     * A loaded block entity entry carrying the block model data (with real elements for
     * rendering via {@link dev.sbs.renderer.kit.GeometryKit}), the entity texture path,
     * and the source model id for diagnostics.
     */
    @Getter
    @RequiredArgsConstructor
    public static final class BlockEntityEntry {

        private final @NotNull BlockModelData model;
        private final @NotNull String textureId;
        private final @NotNull String modelId;
        /** Y-axis rotation in degrees for the atlas icon (e.g. 90 for beds). */
        private final int iconRotation;
        /** Whether this model spans multiple blocks and needs recentering for the atlas icon. */
        private final boolean multiBlock;

    }

}
