package dev.sbs.renderer.pipeline.loader;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonSyntaxException;
import dev.sbs.renderer.asset.binding.DyeColor;
import dev.sbs.renderer.asset.model.BlockModelData;
import dev.sbs.renderer.asset.model.ModelElement;
import dev.sbs.renderer.asset.model.ModelFace;
import dev.sbs.renderer.exception.AssetPipelineException;
import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentList;
import dev.simplified.collection.ConcurrentMap;
import dev.simplified.collection.linked.ConcurrentLinkedMap;
import dev.simplified.gson.GsonSettings;
import dev.simplified.image.pixel.ColorMath;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Map;

/**
 * Loads block entity geometry from two bundled resources:
 * <ul>
 * <li>{@code /renderer/tile_entity_models.json} - generated by {@code ToolingBlockEntities},
 *     contains block model elements (from/to/faces with per-face UV) keyed by entity model id</li>
 * <li>{@code /renderer/tile_entity_mappings.json} - hand-edited, maps block ids to their
 *     entity model id + entity texture path</li>
 * </ul>
 * The output is a flat map of block id to {@link BlockEntityEntry} carrying a populated
 * {@link BlockModelData} (with real {@link ModelElement elements}) and the entity texture
 * reference. These blocks render through the standard block model path
 * ({@link dev.sbs.renderer.kit.GeometryKit#buildFromElements}) with no entity model pipeline.
 */
@UtilityClass
public class BlockEntityLoader {

    private static final @NotNull String BLOCK_MODELS_PATH = "/renderer/tile_entity_models.json";
    private static final @NotNull String MAPPINGS_PATH = "/renderer/tile_entity_mappings.json";
    private static final @NotNull Gson GSON = GsonSettings.defaults().create();

    /**
     * Loads block entity geometry and wiring, producing a map of block id to model + texture.
     *
     * @return the loaded block entity entries keyed by block id
     * @throws AssetPipelineException if either resource is missing or cannot be parsed
     */
    public static @NotNull ConcurrentMap<String, BlockEntityEntry> load() {
        ConcurrentMap<String, JsonObject> blockModels = loadBlockModels();
        ConcurrentMap<String, BlockEntityEntry> result = Concurrent.newMap();

        // Read the mappings file to wire block ids to models + textures
        try (InputStream stream = BlockEntityLoader.class.getResourceAsStream(MAPPINGS_PATH)) {
            if (stream == null)
                throw new AssetPipelineException("Block entity mappings resource '%s' not found", MAPPINGS_PATH);

            String json = new String(stream.readAllBytes(), StandardCharsets.UTF_8);
            JsonObject root = GSON.fromJson(json, JsonObject.class);
            if (root == null)
                throw new AssetPipelineException("Block entity mappings resource '%s' is empty", MAPPINGS_PATH);

            for (Map.Entry<String, JsonElement> modelEntry : root.entrySet()) {
                String modelId = modelEntry.getKey();
                if (!modelEntry.getValue().isJsonArray()) continue;

                JsonObject blockModelJson = blockModels.get(modelId);
                if (blockModelJson == null) {
                    System.err.printf("  Warning: no block model for entity model '%s'%n", modelId);
                    continue;
                }

                for (JsonElement element : modelEntry.getValue().getAsJsonArray()) {
                    JsonObject obj = element.getAsJsonObject();
                    String blockId = obj.get("blockId").getAsString();
                    String textureId = obj.get("textureId").getAsString();

                    // Parse the primary model's elements
                    BlockModelData modelData = parseBlockModelData(blockModelJson, textureId);

                    // Merge composite parts (e.g. bed foot) with offset
                    if (obj.has("parts") && obj.get("parts").isJsonArray()) {
                        for (JsonElement partEl : obj.getAsJsonArray("parts")) {
                            JsonObject partObj = partEl.getAsJsonObject();
                            String partModelId = partObj.get("model").getAsString();
                            String partTexture = partObj.get("texture").getAsString();
                            float[] offset = new float[]{ 0, 0, 0 };
                            if (partObj.has("offset") && partObj.get("offset").isJsonArray()) {
                                com.google.gson.JsonArray off = partObj.getAsJsonArray("offset");
                                offset = new float[]{ off.get(0).getAsFloat(), off.get(1).getAsFloat(), off.get(2).getAsFloat() };
                            }

                            JsonObject partBlockModel = blockModels.get(partModelId);
                            if (partBlockModel == null) continue;
                            BlockModelData partData = parseBlockModelData(partBlockModel, partTexture);

                            // Merge part elements into the primary model, applying the offset.
                            // Rewrite each face's {@code #entity} texture ref to the part's absolute
                            // texture id, since the merged model's texture variables map only
                            // resolves {@code #entity} to the primary texture - without this rewrite,
                            // parts with a different texture (decorated_pot sides using
                            // decorated_pot_side, distinct from decorated_pot_base) silently sample
                            // the primary's pixels instead.
                            for (ModelElement partElem : partData.getElements()) {
                                float[] from = partElem.getFrom().clone();
                                float[] to = partElem.getTo().clone();
                                from[0] += offset[0]; from[1] += offset[1]; from[2] += offset[2];
                                to[0] += offset[0]; to[1] += offset[1]; to[2] += offset[2];

                                JsonObject elemJson = GSON.toJsonTree(partElem).getAsJsonObject();
                                JsonArray fromArr = new JsonArray(); fromArr.add(from[0]); fromArr.add(from[1]); fromArr.add(from[2]);
                                JsonArray toArr = new JsonArray(); toArr.add(to[0]); toArr.add(to[1]); toArr.add(to[2]);
                                elemJson.add("from", fromArr);
                                elemJson.add("to", toArr);

                                JsonObject facesJson = elemJson.getAsJsonObject("faces");
                                if (facesJson != null && !partTexture.equals(textureId)) {
                                    for (Map.Entry<String, JsonElement> faceEntry : facesJson.entrySet()) {
                                        JsonObject faceJson = faceEntry.getValue().getAsJsonObject();
                                        if (faceJson.has("texture") && "#entity".equals(faceJson.get("texture").getAsString()))
                                            faceJson.addProperty("texture", partTexture);
                                    }
                                }

                                modelData.getElements().add(GSON.fromJson(elemJson, ModelElement.class));
                            }
                        }
                    }

                    // Detect multi-block models (any element extends beyond 0-16 on any axis)
                    boolean multiBlock = false;
                    for (ModelElement me : modelData.getElements()) {
                        if (me.getFrom()[0] < -0.1f || me.getFrom()[1] < -0.1f || me.getFrom()[2] < -0.1f ||
                            me.getTo()[0] > 16.1f || me.getTo()[1] > 16.1f || me.getTo()[2] > 16.1f) {
                            multiBlock = true;
                            break;
                        }
                    }

                    int iconRotation = obj.has("iconRotation") ? obj.get("iconRotation").getAsInt() : 0;
                    int tintArgb = obj.has("tint") ? resolveTint(obj.get("tint").getAsString()) : ColorMath.WHITE;
                    result.put(blockId, new BlockEntityEntry(modelData, textureId, modelId, iconRotation, multiBlock, tintArgb));
                }
            }
        } catch (IOException | JsonSyntaxException ex) {
            throw new AssetPipelineException(ex, "Failed to load block entity mappings '%s'", MAPPINGS_PATH);
        }

        return result;
    }

    /**
     * Reads the generated block model elements JSON.
     */
    private static @NotNull ConcurrentMap<String, JsonObject> loadBlockModels() {
        try (InputStream stream = BlockEntityLoader.class.getResourceAsStream(BLOCK_MODELS_PATH)) {
            if (stream == null)
                throw new AssetPipelineException("Block entity block models resource '%s' not found", BLOCK_MODELS_PATH);

            String json = new String(stream.readAllBytes(), StandardCharsets.UTF_8);
            JsonObject root = GSON.fromJson(json, JsonObject.class);
            if (root == null)
                throw new AssetPipelineException("Block entity block models resource '%s' is empty", BLOCK_MODELS_PATH);

            ConcurrentMap<String, JsonObject> models = Concurrent.newMap();
            for (Map.Entry<String, JsonElement> entry : root.entrySet()) {
                if (entry.getValue().isJsonObject() && entry.getValue().getAsJsonObject().has("elements"))
                    models.put(entry.getKey(), entry.getValue().getAsJsonObject());
            }
            return models;
        } catch (IOException | JsonSyntaxException ex) {
            throw new AssetPipelineException(ex, "Failed to load block entity block models '%s'", BLOCK_MODELS_PATH);
        }
    }

    /**
     * Parses a block model JSON object (with elements array) into a {@link BlockModelData},
     * including the texture variable binding so {@code #entity} resolves at render time.
     */
    private static @NotNull BlockModelData parseBlockModelData(@NotNull JsonObject json, @NotNull String textureId) {
        JsonObject modelJson = new JsonObject();

        // Copy elements
        if (json.has("elements"))
            modelJson.add("elements", json.getAsJsonArray("elements"));

        // Set texture variable: "entity" → "minecraft:entity/chest/normal" etc.
        // so #entity in face references resolves to the actual texture path.
        JsonObject textures = new JsonObject();
        textures.addProperty("entity", textureId);
        modelJson.add("textures", textures);

        return GSON.fromJson(modelJson, BlockModelData.class);
    }

    /**
     * Resolves a mapping-JSON {@code tint} string to an ARGB int. Values are interpreted as:
     * <ul>
     * <li>{@link DyeColor.Vanilla} enum names (case-sensitive, e.g. {@code "RED"}, {@code "LIGHT_BLUE"})
     *     - preferred, carries the canonical {@code textureDiffuseColor} value from vanilla</li>
     * <li>Hex colour string ({@code #RRGGBB}, {@code #AARRGGBB}, or {@code 0x}-prefixed) for
     *     custom colours outside the sixteen vanilla dyes</li>
     * </ul>
     */
    private static int resolveTint(@NotNull String value) {
        DyeColor dye = DyeColor.ofName(value);
        if (dye != null) return dye.argb();
        String trimmed = value.startsWith("#") ? value.substring(1)
            : value.startsWith("0x") || value.startsWith("0X") ? value.substring(2)
            : value;
        long packed = Long.parseLong(trimmed, 16);
        if (trimmed.length() <= 6) packed |= 0xFF000000L;
        return (int) packed;
    }

    /**
     * A loaded block entity entry carrying the block model data (with real elements for
     * rendering via {@link dev.sbs.renderer.kit.GeometryKit}), the entity texture path,
     * and the source model id for diagnostics.
     */
    @Getter
    @RequiredArgsConstructor
    public static final class BlockEntityEntry {

        private final @NotNull BlockModelData model;
        private final @NotNull String textureId;
        private final @NotNull String modelId;
        /** Y-axis rotation in degrees for the atlas icon (e.g. 90 for beds). */
        private final int iconRotation;
        /** Whether this model spans multiple blocks and needs recentering for the atlas icon. */
        private final boolean multiBlock;
        /**
         * Per-entry ARGB tint multiplied against every sampled texel at render time. Used
         * when a block-entity block's colour comes from runtime state rather than a
         * dedicated per-variant texture - banners read {@code DyeColor.getTextureDiffuseColor()}
         * via BlockColors in vanilla, and we bake that colour in at mapping time. Defaults
         * to {@link ColorMath#WHITE} (no tint) for entries that don't set {@code tint} in
         * the mapping JSON.
         */
        private final int tintArgb;

    }

}
