package dev.sbs.renderer.pipeline.loader;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonSyntaxException;
import dev.sbs.renderer.exception.AssetPipelineException;
import dev.sbs.renderer.asset.Block;
import dev.sbs.renderer.asset.Entity;
import dev.sbs.renderer.asset.model.EntityModelData;
import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentMap;
import dev.simplified.gson.GsonSettings;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.Optional;

/**
 * A loader that reads the bundled block entity model geometry from
 * {@code /renderer/block_entity_models.json} and the block-to-model wiring from
 * {@code /renderer/block_entity_mappings.json}. The models file is generated by
 * {@code ToolingBlockEntityModels} (ASM parse of the deobfuscated client jar); the mappings
 * file is hand-edited and binds each block id to the entity model + texture to use for its
 * atlas tile.
 * <p>
 * Block entity models are hand-authored because neither Java nor Bedrock Edition ships them
 * as structured JSON - the geometry is hardcoded in the client. The UV coordinates and bone
 * layout are verified against the MC 26.1 deobfuscated client source.
 *
 * @see Block.EntityMapping
 * @see EntityModelData
 */
@UtilityClass
public class BlockEntityModelLoader {

    private static final @NotNull String MODELS_PATH = "/renderer/block_entity_models.json";
    private static final @NotNull String MAPPINGS_PATH = "/renderer/block_entity_mappings.json";
    private static final @NotNull Gson GSON = GsonSettings.defaults().create();

    /**
     * Loads both the model geometry and the block-to-entity mappings and returns them as a
     * single result.
     *
     * @return the parsed result containing entity models and block mappings
     * @throws AssetPipelineException if either resource is missing or cannot be parsed
     */
    public static @NotNull LoadResult load() {
        ConcurrentMap<String, Entity> entities = loadModels();
        ConcurrentMap<String, Block.EntityMapping> mappings = loadMappings();
        return new LoadResult(entities, mappings);
    }

    /**
     * Reads the generated model geometry from {@link #MODELS_PATH}.
     */
    private static @NotNull ConcurrentMap<String, Entity> loadModels() {
        try (InputStream stream = BlockEntityModelLoader.class.getResourceAsStream(MODELS_PATH)) {
            if (stream == null)
                throw new AssetPipelineException("Block entity models resource '%s' not found on the classpath", MODELS_PATH);

            String json = new String(stream.readAllBytes(), StandardCharsets.UTF_8);
            JsonObject root = GSON.fromJson(json, JsonObject.class);
            if (root == null)
                throw new AssetPipelineException("Block entity models resource '%s' is empty", MODELS_PATH);

            ConcurrentMap<String, Entity> entities = Concurrent.newMap();
            if (root.has("models") && root.get("models").isJsonObject()) {
                for (Map.Entry<String, JsonElement> entry : root.getAsJsonObject("models").entrySet()) {
                    String entityId = entry.getKey();
                    EntityModelData model = GSON.fromJson(entry.getValue(), EntityModelData.class);
                    String name = entityId.contains(":") ? entityId.substring(entityId.indexOf(':') + 1) : entityId;
                    entities.put(entityId, new Entity(entityId, "minecraft", name, model, Optional.empty()));
                }
            }
            return entities;
        } catch (IOException | JsonSyntaxException ex) {
            throw new AssetPipelineException(ex, "Failed to load block entity models resource '%s'", MODELS_PATH);
        }
    }

    /**
     * Reads the hand-edited block-to-entity mappings from {@link #MAPPINGS_PATH}. The JSON
     * schema is an object keyed by model id, each value being an array of
     * {@code {"blockId": "...", "textureId": "..."}} sub-objects.
     */
    private static @NotNull ConcurrentMap<String, Block.EntityMapping> loadMappings() {
        try (InputStream stream = BlockEntityModelLoader.class.getResourceAsStream(MAPPINGS_PATH)) {
            if (stream == null)
                throw new AssetPipelineException("Block entity mappings resource '%s' not found on the classpath", MAPPINGS_PATH);

            String json = new String(stream.readAllBytes(), StandardCharsets.UTF_8);
            JsonObject root = GSON.fromJson(json, JsonObject.class);
            if (root == null)
                throw new AssetPipelineException("Block entity mappings resource '%s' is empty", MAPPINGS_PATH);

            ConcurrentMap<String, Block.EntityMapping> mappings = Concurrent.newMap();
            for (Map.Entry<String, JsonElement> modelEntry : root.entrySet()) {
                String modelId = modelEntry.getKey();
                if (!modelEntry.getValue().isJsonArray()) continue;
                for (JsonElement element : modelEntry.getValue().getAsJsonArray()) {
                    JsonObject obj = element.getAsJsonObject();
                    String blockId = obj.get("blockId").getAsString();
                    String textureId = obj.get("textureId").getAsString();
                    mappings.put(blockId, new Block.EntityMapping(modelId, textureId));
                }
            }
            return mappings;
        } catch (IOException | JsonSyntaxException ex) {
            throw new AssetPipelineException(ex, "Failed to load block entity mappings resource '%s'", MAPPINGS_PATH);
        }
    }

    /**
     * The result of loading the block entity models resource, containing both the parsed
     * entity models and the block-to-entity mappings.
     */
    @Getter
    @RequiredArgsConstructor
    public static final class LoadResult {

        private final @NotNull ConcurrentMap<String, Entity> entities;
        private final @NotNull ConcurrentMap<String, Block.EntityMapping> mappings;

    }

}
