package lib.minecraft.renderer.tooling2.bridge;

import com.google.gson.JsonObject;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.StringJoiner;
import java.util.TreeSet;

/**
 * Reconstructs {@code block_defaults.json} from the v2 form (10-bridge SS5.4). The absent-vs-empty
 * distinction is why this file needed a schema repair (decision 24): legacy value {@code ""} means
 * "resolved, declares no properties", while an ABSENT key means the {@code Blocks} clinit walk could
 * not resolve the block's class. v2 records the failure set in-file as {@code unresolved[]}, so
 * legacy is reconstructible from v2 alone:
 * <ul>
 *   <li>each {@code blocks.<id>} object {@code {prop:val, ...}} -&gt; the comma-joined
 *       property-sorted string {@code "prop=val,prop=val"} (v2 already sorts within each object);</li>
 *   <li>an empty object -&gt; the empty string;</li>
 *   <li>{@code unresolved[]} members -&gt; absent keys (filtered out);</li>
 *   <li>keys emitted block-id sorted (the legacy {@code TreeMap} order).</li>
 * </ul>
 */
final class BlockDefaultsBridge {

    private static final @NotNull String HEADER =
        "Generated by ToolingBlockDefaults. Default blockstate key per block from an ASM bytewalk of "
            + "registerDefaultState. Run the tooling/blockDefaults Gradle task to refresh.";

    private BlockDefaultsBridge() {
    }

    /**
     * Converts the v2 block-defaults object into its legacy form.
     *
     * @param v2 the parsed v2 {@code block_defaults} object
     * @return the legacy-shaped object
     */
    static @NotNull JsonObject convert(@NotNull JsonObject v2) {
        Set<String> unresolved = new HashSet<>();
        if (v2.has("unresolved"))
            for (var element : v2.getAsJsonArray("unresolved")) unresolved.add(element.getAsString());

        JsonObject v2Blocks = v2.getAsJsonObject("blocks");
        Set<String> ids = new TreeSet<>();
        for (String id : v2Blocks.keySet())
            if (!unresolved.contains(id)) ids.add(id);

        JsonObject out = LegacyBridge.legacyEnvelope(HEADER, v2);
        JsonObject blocks = new JsonObject();
        for (String id : ids)
            blocks.addProperty(id, joinProperties(v2Blocks.getAsJsonObject(id)));
        out.add("blocks", blocks);
        return out;
    }

    /**
     * Joins a default-state object into the legacy {@code prop=val,prop=val} string,
     * property-name-sorted; an empty object joins to the empty string.
     *
     * @param state the v2 default-state object
     * @return the comma-joined property string
     */
    private static @NotNull String joinProperties(@NotNull JsonObject state) {
        List<String> properties = new ArrayList<>(state.keySet());
        properties.sort(null);
        StringJoiner joiner = new StringJoiner(",");
        for (String property : properties)
            joiner.add(property + "=" + state.get(property).getAsString());
        return joiner.toString();
    }

}
