package lib.minecraft.renderer.tooling2.bridge;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import lib.minecraft.renderer.tooling2.kernel.ToolingException;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * The only 2:1 converter (10-bridge SS5.3): consumes {@code v2/block_models.json} +
 * {@code v2/block_geometry.json} and re-nests each referenced bone tree under the legacy entry's
 * {@code model} sub-object (decision 13 split them so both subjects share one bone/cube dialect;
 * legacy had the geometry inline). It also reverses the A10 deltas:
 * <ul>
 *   <li>entry key order = {@link LegacyOrder#BLOCK_MODELS_KEYS} (the impure-merge order, not
 *       derivable from any walk), which also filters the v2 superset
 *       ({@code enchanting_table}/{@code lectern} drop);</li>
 *   <li>member order {@code model} -&gt; {@code y_axis} -&gt; {@code inventory_y_rotation} -&gt;
 *       {@code entity_flip} -&gt; {@code inventory_transform?} -&gt; {@code tinted} -&gt;
 *       {@code parts?} -&gt; {@code blocks?};</li>
 *   <li>{@code inventory.*} un-grouped; {@code icon.rotation}/{@code icon.additive} re-slotted onto
 *       the per-block rows ({@code iconRotation} on beds, {@code additive} on bells);</li>
 *   <li>block rows {@code block}/{@code texture} renamed to {@code blockId}/{@code textureId} with
 *       the texture path stripped to the legacy grammar ({@code minecraft:entity/bed/red}).</li>
 * </ul>
 * The geometry side re-adds the cube defaults legacy always emitted ({@code inflate}, {@code mirror},
 * {@code face_uv: {}}), exactly as {@code entity_geometry} does (10-bridge SS5.2).
 */
final class BlockModelsBridge {

    private static final @NotNull String HEADER =
        "Generated by ToolingBlockModels (tooling/blockModels Gradle task). Unified block-entity "
            + "catalog keyed by entity-model id: each entry carries the ASM-extracted geometry (a "
            + "parent-relative bone/cube tree, the same schema as entity_geometry.json, composed at "
            + "render time via BlockGeometryKit.buildFromBones), metadata (y_axis source convention, "
            + "inventory_y_rotation GUI-facing yaw, entity_flip gate, inventory_transform decomposed "
            + "from the Renderer's PoseStack, tinted flag) that the render presentation applies around "
            + "the bones, optional sub-model parts with their render offsets, and the list of block "
            + "variants that render as this entity model along with their entity-texture paths. "
            + "Supersedes the former split between tile_entity_models.json (generated geometry) and "
            + "tile_entity_mappings.json (hand-edited block bindings); both source files are now "
            + "derived in one pass from the 26.1 client jar. Per-block atlas/GUI fields (iconRotation "
            + "on beds, additive on bells, per-block tint on banners) are pattern-matched onto block "
            + "entries by applyPerBlockFamilyFields at tooling time. Run the tooling/blockModels Gradle "
            + "task to refresh; BlockModelsGoldenTest guards against silent drift via a SHA-256 over "
            + "the canonical JSON.";

    private static final @NotNull String TEXTURE_PREFIX = "textures/";
    private static final @NotNull String TEXTURE_SUFFIX = ".png";

    private BlockModelsBridge() {
    }

    /**
     * Converts the v2 block-models + block-geometry pair into the legacy {@code block_models} form.
     *
     * @param v2Models the parsed {@code v2/block_models.json}
     * @param v2Geometry the parsed {@code v2/block_geometry.json}
     * @return the legacy-shaped {@code block_models} object
     */
    static @NotNull JsonObject convert(@NotNull JsonObject v2Models, @NotNull JsonObject v2Geometry) {
        JsonObject models = v2Models.getAsJsonObject("models");
        JsonObject geometries = v2Geometry.getAsJsonObject("geometries");

        JsonObject out = LegacyBridge.legacyEnvelope(HEADER, v2Models);
        JsonObject entries = new JsonObject();
        for (String id : LegacyOrder.BLOCK_MODELS_KEYS) {
            JsonObject v2Entry = models.getAsJsonObject(id);
            if (v2Entry == null)
                throw new ToolingException("Legacy block_models id '%s' absent from v2 catalog", id);
            entries.add(id, convertEntry(v2Entry, geometries));
        }
        out.add("models", entries);
        return out;
    }

    /**
     * Converts one v2 block-model entry into the legacy entry shape.
     *
     * @param v2 the v2 entry
     * @param geometries the v2 geometry map for the nested bone tree
     * @return the legacy entry
     */
    private static @NotNull JsonObject convertEntry(@NotNull JsonObject v2, @NotNull JsonObject geometries) {
        JsonObject entry = new JsonObject();
        entry.add("model", nestedModel(v2.get("geometry").getAsString(), geometries));
        entry.add("y_axis", v2.get("y_axis").deepCopy());

        JsonObject inventory = v2.getAsJsonObject("inventory");
        entry.add("inventory_y_rotation", inventory.get("y_rotation").deepCopy());
        entry.add("entity_flip", inventory.get("flip").deepCopy());
        if (inventory.has("transform")) entry.add("inventory_transform", inventory.get("transform").deepCopy());

        entry.add("tinted", v2.get("tinted").deepCopy());
        if (v2.has("parts")) entry.add("parts", convertParts(v2.getAsJsonArray("parts")));
        if (v2.has("blocks"))
            entry.add("blocks", convertBlocks(v2.getAsJsonArray("blocks"),
                v2.has("icon") ? v2.getAsJsonObject("icon") : null));
        return entry;
    }

    /**
     * Builds the legacy {@code model} sub-object from a v2 geometry entry: un-pairs
     * {@code texture_size} into {@code textureWidth}/{@code textureHeight}, keeps the bone tree
     * (with cube defaults re-added), and drops the v2-only {@code source}/{@code y_axis}.
     *
     * @param coordinate the v2 geometry-coordinate key
     * @param geometries the v2 geometry map
     * @return the legacy {@code model} sub-object
     */
    private static @NotNull JsonObject nestedModel(@NotNull String coordinate, @NotNull JsonObject geometries) {
        JsonObject geometry = geometries.getAsJsonObject(coordinate);
        if (geometry == null)
            throw new ToolingException("v2 block geometry '%s' missing", coordinate);
        JsonArray size = geometry.getAsJsonArray("texture_size");
        JsonObject model = new JsonObject();
        model.add("textureWidth", size.get(0).deepCopy());
        model.add("textureHeight", size.get(1).deepCopy());
        JsonObject bones = new JsonObject();
        for (var bone : geometry.getAsJsonObject("bones").entrySet())
            bones.add(bone.getKey(), convertBone(bone.getValue().getAsJsonObject()));
        model.add("bones", bones);
        return model;
    }

    /**
     * Converts a v2 bone into the legacy bone shape (10-bridge SS5.2 bone member order).
     *
     * @param v2 the v2 bone
     * @return the legacy bone
     */
    static @NotNull JsonObject convertBone(@NotNull JsonObject v2) {
        JsonObject bone = new JsonObject();
        bone.add("pivot", v2.get("pivot").deepCopy());
        bone.add("rotation", v2.get("rotation").deepCopy());
        if (v2.has("scale")) bone.add("scale", v2.get("scale").deepCopy());
        if (v2.has("parent")) bone.add("parent", v2.get("parent").deepCopy());
        JsonArray cubes = new JsonArray();
        if (v2.has("cubes"))
            for (JsonElement cube : v2.getAsJsonArray("cubes")) cubes.add(convertCube(cube.getAsJsonObject()));
        bone.add("cubes", cubes);
        return bone;
    }

    /**
     * Converts a v2 cube into the legacy cube shape, re-adding the defaults legacy always emitted:
     * {@code origin} -&gt; {@code size} -&gt; {@code uv} -&gt; {@code inflate} -&gt; {@code mirror}
     * -&gt; {@code face_uv} (10-bridge SS5.2). v2 omits {@code grow}/{@code mirror} at defaults and
     * deleted {@code face_uv} [X1]; {@code grow} arrives scalar or {@code [x,y,z]} (mean-averaged).
     *
     * @param v2 the v2 cube
     * @return the legacy cube
     */
    static @NotNull JsonObject convertCube(@NotNull JsonObject v2) {
        JsonObject cube = new JsonObject();
        cube.add("origin", v2.get("origin").deepCopy());
        cube.add("size", v2.get("size").deepCopy());
        cube.add("uv", v2.get("uv").deepCopy());
        cube.add("inflate", inflate(v2.get("grow")));
        cube.add("mirror", v2.has("mirror") ? v2.get("mirror").deepCopy() : new JsonPrimitive(false));
        cube.add("face_uv", new JsonObject());
        return cube;
    }

    /**
     * Reduces a v2 {@code grow} value to the legacy scalar {@code inflate}: a scalar passes
     * through verbatim, an {@code [x,y,z]} array becomes its mean (legacy's lossy /3 average), and
     * an absent value defaults to {@code 0.0}.
     *
     * @param grow the v2 grow element, or {@code null} when absent
     * @return the legacy scalar inflate primitive
     */
    private static @NotNull JsonElement inflate(@Nullable JsonElement grow) {
        if (grow == null) return new JsonPrimitive(0.0F);
        if (grow.isJsonArray()) {
            JsonArray xyz = grow.getAsJsonArray();
            float mean = (xyz.get(0).getAsFloat() + xyz.get(1).getAsFloat() + xyz.get(2).getAsFloat()) / 3.0F;
            return new JsonPrimitive(mean);
        }
        return grow.deepCopy();
    }

    /**
     * Converts the v2 {@code parts} array: {@code model} passthrough, optional {@code offset}, and
     * an optional {@code texture} stripped to the legacy grammar.
     *
     * @param v2Parts the v2 parts array
     * @return the legacy parts array
     */
    private static @NotNull JsonArray convertParts(@NotNull JsonArray v2Parts) {
        JsonArray parts = new JsonArray(v2Parts.size());
        for (JsonElement element : v2Parts) {
            JsonObject v2 = element.getAsJsonObject();
            JsonObject part = new JsonObject();
            part.add("model", v2.get("model").deepCopy());
            if (v2.has("offset")) part.add("offset", v2.get("offset").deepCopy());
            if (v2.has("texture")) part.addProperty("texture", stripTexture(v2.get("texture").getAsString()));
            parts.add(part);
        }
        return parts;
    }

    /**
     * Converts the v2 {@code blocks} array: {@code block}/{@code texture} -&gt;
     * {@code blockId}/{@code textureId}, the entry-level {@code icon} re-slotted per row, then the
     * optional {@code variant}/{@code tint}.
     *
     * @param v2Blocks the v2 blocks array
     * @param icon the entry-level icon object, or {@code null}
     * @return the legacy blocks array
     */
    private static @NotNull JsonArray convertBlocks(@NotNull JsonArray v2Blocks, @Nullable JsonObject icon) {
        JsonArray blocks = new JsonArray(v2Blocks.size());
        for (JsonElement element : v2Blocks) {
            JsonObject v2 = element.getAsJsonObject();
            JsonObject block = new JsonObject();
            block.addProperty("blockId", v2.get("block").getAsString());
            block.addProperty("textureId", stripTexture(v2.get("texture").getAsString()));
            if (icon != null) {
                if (icon.has("rotation")) block.add("iconRotation", icon.get("rotation").deepCopy());
                if (icon.has("additive")) block.add("additive", icon.get("additive").deepCopy());
            }
            if (v2.has("variant")) block.add("variant", v2.get("variant").deepCopy());
            if (v2.has("tint")) block.add("tint", v2.get("tint").deepCopy());
            blocks.add(block);
        }
        return blocks;
    }

    /**
     * Strips a full v2 texture path to the legacy block-texture grammar: the namespace is kept, the
     * leading {@code textures/} segment and the {@code .png} suffix dropped
     * ({@code minecraft:textures/entity/bed/red.png} -&gt; {@code minecraft:entity/bed/red}).
     *
     * @param path the full v2 texture path
     * @return the legacy texture id
     */
    private static @NotNull String stripTexture(@NotNull String path) {
        int colon = path.indexOf(':');
        String namespace = path.substring(0, colon + 1);
        String rest = path.substring(colon + 1);
        if (rest.startsWith(TEXTURE_PREFIX)) rest = rest.substring(TEXTURE_PREFIX.length());
        if (rest.endsWith(TEXTURE_SUFFIX)) rest = rest.substring(0, rest.length() - TEXTURE_SUFFIX.length());
        return namespace + rest;
    }

}
