package lib.minecraft.renderer.tooling2.bridge;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import org.jetbrains.annotations.NotNull;

import java.util.Map;

/**
 * Reconstructs {@code entity_geometry.json} from the v2 form (10-bridge SS5.2): each v2 geometry
 * entry becomes the legacy bone/cube tree, keyed by {@link LegacyGeometryIds}. Per entry:
 * un-pair {@code texture_size} into {@code textureWidth}/{@code textureHeight}, keep the bone tree
 * with the v2 member order preserved (the two pipelines share the parser, so
 * {@code pivot -> rotation -> [parent] -> cubes -> [scale]} is identical), re-add the cube defaults
 * legacy always emitted ({@code inflate}, {@code mirror}, {@code face_uv: {}}), then {@code y_axis}
 * (after {@code bones}) and an optional trailing {@code cull}. The v2-only {@code source} twin is
 * dropped.
 *
 * <p>After the renderer-scale flow fix the two key sets coincide for every shared mesh (124/125
 * byte-exact); the residual differences are v2-superior meshes legacy lacked (the warden pulsating
 * overlay, per-family baby meshes, the scaled happy_ghast harness) which are emitted so the models
 * refs resolve, and legacy's {@code drowned_1} which v2 represents as an overlay {@code grow} on the
 * shared drowned mesh - kept per the more-accurate-is-better decision, recorded by
 * {@code BridgeParityTest} rather than degraded.
 */
final class EntityGeometryBridge {

    private static final @NotNull String HEADER =
        "Generated by ToolingEntityModels. Per-geometry bone/cube tree from Java client jar bytecode, "
            + "deduplicated by factory class+method. Frame is vanilla Java's natural Y-DOWN.";

    private EntityGeometryBridge() {
    }

    /**
     * Converts the v2 models + geometry pair into the legacy {@code entity_geometry} form.
     *
     * @param v2Models the parsed {@code v2/entity_models.json} (for the key replay walk)
     * @param v2Geometry the parsed {@code v2/entity_geometry.json}
     * @return the legacy-shaped {@code entity_geometry} object
     */
    static @NotNull JsonObject convert(@NotNull JsonObject v2Models, @NotNull JsonObject v2Geometry) {
        Map<String, String> keys = LegacyGeometryIds.map(v2Models, v2Geometry);
        JsonObject geometries = v2Geometry.getAsJsonObject("geometries");

        JsonObject out = LegacyBridge.legacyEnvelope(HEADER, v2Models);
        JsonObject entries = new JsonObject();
        for (Map.Entry<String, String> mapping : keys.entrySet())
            entries.add(mapping.getValue(), convertEntry(geometries.getAsJsonObject(mapping.getKey())));
        out.add("geometries", entries);
        return out;
    }

    /**
     * Converts one v2 geometry entry into the legacy entry shape.
     *
     * @param v2 the v2 geometry entry
     * @return the legacy entry
     */
    static @NotNull JsonObject convertEntry(@NotNull JsonObject v2) {
        JsonArray size = v2.getAsJsonArray("texture_size");
        JsonObject entry = new JsonObject();
        entry.add("textureWidth", size.get(0).deepCopy());
        entry.add("textureHeight", size.get(1).deepCopy());
        JsonObject bones = new JsonObject();
        for (Map.Entry<String, JsonElement> bone : v2.getAsJsonObject("bones").entrySet())
            bones.add(bone.getKey(), convertBone(bone.getValue().getAsJsonObject()));
        entry.add("bones", bones);
        entry.add("y_axis", v2.get("y_axis").deepCopy());
        if (v2.has("cull")) entry.add("cull", v2.get("cull").deepCopy());
        return entry;
    }

    /**
     * Converts a bone, preserving the v2 member order and re-adding cube defaults inside the
     * {@code cubes} array only.
     *
     * @param v2 the v2 bone
     * @return the legacy bone
     */
    private static @NotNull JsonObject convertBone(@NotNull JsonObject v2) {
        JsonObject bone = new JsonObject();
        for (Map.Entry<String, JsonElement> member : v2.entrySet()) {
            if ("cubes".equals(member.getKey())) {
                JsonArray cubes = new JsonArray();
                for (JsonElement cube : member.getValue().getAsJsonArray())
                    cubes.add(BlockModelsBridge.convertCube(cube.getAsJsonObject()));
                bone.add("cubes", cubes);
            } else {
                bone.add(member.getKey(), member.getValue().deepCopy());
            }
        }
        return bone;
    }

}
