package lib.minecraft.renderer.tooling2.bridge;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonPrimitive;
import lib.minecraft.renderer.pipeline.loader.EntityModelLoader;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Reconstructs {@code entity_models.json} - the normalized family form - from the v2 family form
 * (10-bridge SS5.1, decision 27). v2 and legacy are both grouped one-entry-per-base-entity, so the
 * conversion is a field-rename + un-group + geometry-key remap rather than a flat-rows two-step: the
 * dynamic member order legacy's {@code group()} produces (variant families place {@code axes} early
 * with the variant axis; age/size/shape-only families attach it after {@code layers}) falls out of
 * building the family in that same order.
 *
 * <p>Per the more-accurate-is-better decision, v2's genuine improvements over legacy are KEPT (not
 * degraded to match legacy bytes) and recorded by {@code BridgeParityTest}: the superset variant/age
 * axes (axolotl, donkey, llama, ...), the armor_stand/bee/turtle bone toggles, the wither
 * energy-swirl overlay, and drowned's overlay-grow representation of the outer layer. Only v2-only
 * NON-render metadata that legacy deliberately dropped is stripped ({@code renderer}, {@code format},
 * {@code source}, {@code layer_index}, {@code spawn_conditions}, {@code textures_by_value}).
 *
 * <p>The {@code inflate: 0.001} depth-clearance re-add on grow-less overlays that inherit the base
 * mesh replays legacy bytes the loader would otherwise auto-apply; it references
 * {@link EntityModelLoader#DEPTH_CLEARANCE_INFLATE} directly (widened to public in S12) rather than
 * re-minting a literal (decision 22).
 */
final class EntityModelsBridge {

    private static final @NotNull String HEADER =
        "Generated by ToolingEntityModels. Normalized family form: one entry per base entity with axes "
            + "(id-encoded colour variants; option-encoded state/age) + layers (collar, equipment), "
            + "cross-entity groupings as family_of. Flattened to per-entity rows at load by EntityFamilyFlattener.";

    private static final @NotNull String TEXTURE_PREFIX = "minecraft:textures/entity/";
    private static final @NotNull String TEXTURE_SUFFIX = ".png";

    private final @NotNull Map<String, String> geometryKeys;

    private EntityModelsBridge(@NotNull Map<String, String> geometryKeys) {
        this.geometryKeys = geometryKeys;
    }

    /**
     * Converts the v2 models + geometry pair into the legacy {@code entity_models} form.
     *
     * @param v2Models the parsed {@code v2/entity_models.json}
     * @param v2Geometry the parsed {@code v2/entity_geometry.json} (for the shared geometry key map)
     * @return the legacy-shaped {@code entity_models} object
     */
    static @NotNull JsonObject convert(@NotNull JsonObject v2Models, @NotNull JsonObject v2Geometry) {
        EntityModelsBridge bridge = new EntityModelsBridge(LegacyGeometryIds.map(v2Models, v2Geometry));
        JsonObject out = LegacyBridge.legacyEnvelope(HEADER, v2Models);
        JsonObject families = new JsonObject();
        for (Map.Entry<String, JsonElement> family : v2Models.getAsJsonObject("families").entrySet())
            families.add(family.getKey(), bridge.family(family.getValue().getAsJsonObject()));
        out.add("families", families);
        return out;
    }

    // ------------------------------------------------------------------------------------
    // family regroup
    // ------------------------------------------------------------------------------------

    private @NotNull JsonObject family(@NotNull JsonObject v2) {
        JsonObject axes = v2.has("axes") ? v2.getAsJsonObject("axes") : new JsonObject();
        JsonObject variant = axes.has("variant") ? axes.getAsJsonObject("variant") : null;
        // Axis unification #1: the family baseline (geometry + adult texture) lives under the
        // mandatory age axis' options.adult, not at top level. Legacy takes them as the family/base-row
        // geometry_ref + texture_ref.
        JsonObject adult = adultOption(axes);
        String familyGeometry = key(adult.get("geometry").getAsString());
        JsonObject family = new JsonObject();

        if (variant != null) {
            JsonObject options = variant.getAsJsonObject("options");
            String defaultOption = variant.get("default").getAsString();
            String baseTexture = strip(options.getAsJsonObject(defaultOption)
                .getAsJsonObject("textures").get("wild").getAsString());
            JsonObject baseRow = baseRow(v2, familyGeometry, baseTexture);

            family.add("geometry_ref", new JsonPrimitive(familyGeometry));
            family.add("armor_type", baseRow.get("armor_type"));
            for (String field : LegacyOrder.FAMILY_CARRIED_ORDER)
                if (baseRow.has(field)) family.add(field, baseRow.get(field));
            if (v2.has("family_of")) family.add("family_of", v2.get("family_of").deepCopy());
            family.add("axes", variantAxes(variant, familyGeometry, axes));
        } else {
            String texture = adult.has("texture") ? strip(adult.get("texture").getAsString()) : null;
            JsonObject baseRow = baseRow(v2, familyGeometry, texture);
            family.add("geometry_ref", baseRow.get("geometry_ref"));
            family.add("armor_type", baseRow.get("armor_type"));
            if (baseRow.has("texture_ref")) family.add("texture_ref", baseRow.get("texture_ref"));
            for (String field : LegacyOrder.FAMILY_CARRIED_ORDER)
                if (baseRow.has(field)) family.add(field, baseRow.get(field));
            if (v2.has("family_of")) family.add("family_of", v2.get("family_of").deepCopy());
        }

        // Layers in legacy group() order: collar -> markings -> equipment. Attached BEFORE the
        // age/shape/size axes so a variant-less family lands layers ahead of its attached axes.
        JsonArray layers = new JsonArray();
        appendLayerRows(layers, v2, "collar", familyGeometry);
        appendLayerRows(layers, v2, "markings", familyGeometry);
        appendEquipmentRows(layers, v2);
        if (!layers.isEmpty()) family.add("layers", layers);

        // The age axis is now mandatory (options.adult holds the baseline); legacy only carried an age
        // axis when a dedicated baby mesh existed, so re-emit one ONLY when options.baby is present.
        JsonObject age = axes.getAsJsonObject("age");
        if (age.getAsJsonObject("options").has("baby")) attach(family, "age", ageAxis(age));
        if (axes.has("shape")) attach(family, "shape", shapeAxis(axes.getAsJsonObject("shape")));
        if (axes.has("size")) attach(family, "size", sizeAxis(axes.getAsJsonObject("size")));
        return family;
    }

    /** The mandatory age axis' {@code options.adult} body (axis unification #1 - carries the baseline). */
    private static @NotNull JsonObject adultOption(@NotNull JsonObject axes) {
        return axes.getAsJsonObject("age").getAsJsonObject("options").getAsJsonObject("adult");
    }

    /** The flat base row in {@code ENTITY_FLAT_ROW_KEYS} order. */
    private @NotNull JsonObject baseRow(@NotNull JsonObject v2, @NotNull String geometry, @Nullable String texture) {
        Map<String, JsonElement> values = new LinkedHashMap<>();
        values.put("geometry_ref", new JsonPrimitive(geometry));
        if (texture != null) values.put("texture_ref", new JsonPrimitive(texture));
        values.put("armor_type", v2.get("armor_type").deepCopy());
        JsonObject render = v2.has("render") ? v2.getAsJsonObject("render") : new JsonObject();
        if (render.has("scale")) values.put("renderer_scale", render.get("scale").deepCopy());
        if (render.has("yaw_addend")) values.put("setup_yaw_addend", render.get("yaw_addend").deepCopy());
        if (render.has("tint")) values.put("base_tint", render.get("tint").deepCopy());
        JsonObject bones = v2.has("bones") ? v2.getAsJsonObject("bones") : new JsonObject();
        if (bones.has("hidden")) values.put("hidden_bones", bones.get("hidden").deepCopy());
        if (bones.has("toggles")) values.put("bone_toggles", bones.get("toggles").deepCopy());
        if (v2.has("overlays")) values.put("overlays", overlayRows(v2.getAsJsonArray("overlays"), geometry));
        if (v2.has("block_overlays")) values.put("block_overlays", blockOverlayRows(v2.getAsJsonArray("block_overlays")));

        JsonObject row = new JsonObject();
        for (String field : LegacyOrder.ENTITY_FLAT_ROW_KEYS)
            if (values.containsKey(field)) row.add(field, values.get(field));
        return row;
    }

    private @NotNull JsonArray overlayRows(@NotNull JsonArray v2Rows, @NotNull String baseGeometry) {
        JsonArray rows = new JsonArray();
        for (JsonElement element : v2Rows) rows.add(overlayRow(element.getAsJsonObject(), baseGeometry));
        return rows;
    }

    private @NotNull JsonObject overlayRow(@NotNull JsonObject v2, @NotNull String baseGeometry) {
        Map<String, JsonElement> values = new LinkedHashMap<>();
        boolean inherits = !v2.has("geometry");        // absent = inherits the family mesh
        String overlayGeometry = inherits ? baseGeometry : key(v2.get("geometry").getAsString());
        values.put("geometry_ref", new JsonPrimitive(overlayGeometry));
        if (v2.has("texture")) values.put("texture_ref", new JsonPrimitive(strip(v2.get("texture").getAsString())));
        JsonObject pipeline = v2.has("pipeline") ? v2.getAsJsonObject("pipeline") : new JsonObject();
        if (pipeline.has("emissive")) values.put("emissive", pipeline.get("emissive").deepCopy());
        if (v2.has("tint")) values.put("tint_color", v2.get("tint").deepCopy());
        if (v2.has("tint_by")) values.put("tint_by", v2.get("tint_by").deepCopy());
        if (v2.has("texture_by")) values.put("texture_by", v2.get("texture_by").deepCopy());
        JsonObject when = v2.has("when") ? v2.getAsJsonObject("when") : new JsonObject();
        if ("sheared".equals(when.has("flag") ? when.get("flag").getAsString() : null))
            values.put("shearable", new JsonPrimitive(true));
        if (when.has("tinted") && when.get("tinted").getAsBoolean()) values.put("requires_tint", new JsonPrimitive(true));
        if (when.has("charged") && when.get("charged").getAsBoolean()) values.put("requires_charged", new JsonPrimitive(true));
        if (v2.has("grow")) values.put("inflate", v2.get("grow").deepCopy());
        // Legacy (EntityRuntimeJsonWriter) stamped its depth-clearance inflate onto grow-less
        // overlays that RE-SUBMIT the base mesh - vanilla's modelLayerField==null case: emissive eyes
        // and texture_by profession/crackiness layers, which resolve to the base geometry and apply no
        // colour tint. A tinted separate-LayerDefinition overlay that merely dedupes into the base id
        // (sheep wool undercoat: tint_by wool_color) is NOT stamped, so the tint gate excludes it.
        // Minted as a PARSED literal from the loader's own constant - new JsonPrimitive(0.001f) would
        // widen to the inexact double 0.0010000000474974513 on serialize (decision 22, S0 spike note).
        else if (overlayGeometry.equals(baseGeometry) && !v2.has("tint") && !v2.has("tint_by"))
            values.put("inflate", JsonParser.parseString(Float.toString(EntityModelLoader.DEPTH_CLEARANCE_INFLATE)));
        if (v2.has("skip_bounds")) values.put("skip_bounds", v2.get("skip_bounds").deepCopy());
        if (pipeline.has("blend")) values.put("blend", pipeline.get("blend").deepCopy());
        if (pipeline.has("alpha")) values.put("alpha", pipeline.get("alpha").deepCopy());
        if (v2.has("retain_bones")) values.put("retain_bones", v2.get("retain_bones").deepCopy());

        JsonObject row = new JsonObject();
        for (String field : LegacyOrder.OVERLAY_ROW_KEYS)
            if (values.containsKey(field)) row.add(field, values.get(field));
        return row;
    }

    private @NotNull JsonArray blockOverlayRows(@NotNull JsonArray v2Rows) {
        JsonArray rows = new JsonArray();
        for (JsonElement element : v2Rows) {
            JsonObject v2 = element.getAsJsonObject();
            JsonObject row = new JsonObject();
            if (v2.has("block")) row.addProperty("block_id", v2.get("block").getAsString());
            for (String field : LegacyOrder.BLOCK_OVERLAY_ROW_KEYS)
                if (!"block_id".equals(field) && v2.has(field)) row.add(field, v2.get(field).deepCopy());
            rows.add(row);
        }
        return rows;
    }

    // ------------------------------------------------------------------------------------
    // axes + layers
    // ------------------------------------------------------------------------------------

    private @NotNull JsonObject variantAxes(@NotNull JsonObject variant, @NotNull String familyGeometry, @NotNull JsonObject axes) {
        JsonObject options = variant.getAsJsonObject("options");
        String defaultOption = variant.get("default").getAsString();

        JsonObject optionsOut = new JsonObject();
        // legacy orders the variant values/options DEFAULT first, then the rest in v2 order.
        optionsOut.add(defaultOption, variantOption(options.getAsJsonObject(defaultOption), familyGeometry));
        for (Map.Entry<String, JsonElement> option : options.entrySet())
            if (!option.getKey().equals(defaultOption))
                optionsOut.add(option.getKey(), variantOption(option.getValue().getAsJsonObject(), familyGeometry));

        JsonObject variantOut = new JsonObject();
        variantOut.addProperty("id_encoded", true);
        variantOut.addProperty("default", defaultOption);
        JsonArray values = new JsonArray();
        for (String value : optionsOut.keySet()) values.add(value);
        variantOut.add("values", values);
        variantOut.add("options", optionsOut);

        JsonObject axesOut = new JsonObject();
        axesOut.add("variant", variantOut);
        if (axes.has("state")) {
            JsonObject state = axes.getAsJsonObject("state");
            JsonObject stateOut = new JsonObject();
            stateOut.add("default", state.get("default").deepCopy());
            // Axis unification #2: the state domain is now the options key-order (empty bodies), not a
            // separate values list; rebuild the legacy values array from it.
            JsonArray stateValues = new JsonArray();
            for (String stateKey : state.getAsJsonObject("options").keySet()) stateValues.add(stateKey);
            stateOut.add("values", stateValues);
            stateOut.add("options", new JsonObject());
            axesOut.add("state", stateOut);
        }
        return axesOut;
    }

    private @NotNull JsonObject variantOption(@NotNull JsonObject body, @NotNull String familyGeometry) {
        JsonObject out = new JsonObject();
        JsonObject textures = new JsonObject();
        for (Map.Entry<String, JsonElement> texture : body.getAsJsonObject("textures").entrySet())
            textures.addProperty(texture.getKey(), strip(texture.getValue().getAsString()));
        if (body.has("baby_texture")) textures.addProperty("baby", strip(body.get("baby_texture").getAsString()));
        out.add("textures", textures);
        if (body.has("geometry")) {
            String optionGeometry = key(body.get("geometry").getAsString());
            if (!optionGeometry.equals(familyGeometry)) out.addProperty("geometry_ref", optionGeometry);
        }
        return out;
    }

    private @NotNull JsonObject ageAxis(@NotNull JsonObject age) {
        JsonObject baby = age.getAsJsonObject("options").getAsJsonObject("baby");
        JsonObject babyOut = new JsonObject();
        babyOut.addProperty("geometry_ref", key(baby.get("geometry").getAsString()));
        if (baby.has("texture")) babyOut.addProperty("texture_ref", strip(baby.get("texture").getAsString()));
        return axisShape("adult", List.of("adult", "baby"), single("baby", babyOut));
    }

    private @NotNull JsonObject shapeAxis(@NotNull JsonObject shape) {
        JsonObject large = shape.getAsJsonObject("options").getAsJsonObject("large");
        String largeGeometry = key(large.get("geometry").getAsString());
        JsonObject largeOut = new JsonObject();
        largeOut.addProperty("geometry_ref", largeGeometry);
        if (large.has("texture")) largeOut.addProperty("texture_ref", strip(large.get("texture").getAsString()));
        if (large.has("overlays")) largeOut.add("overlays", overlayRows(large.getAsJsonArray("overlays"), largeGeometry));
        return axisShape("small", List.of("small", "large"), single("large", largeOut));
    }

    private @NotNull JsonObject sizeAxis(@NotNull JsonObject size) {
        JsonObject options = new JsonObject();
        for (Map.Entry<String, JsonElement> option : size.getAsJsonObject("options").entrySet()) {
            JsonObject body = option.getValue().getAsJsonObject();
            JsonObject out = new JsonObject();
            if (body.has("geometry")) out.addProperty("geometry_ref", key(body.get("geometry").getAsString()));
            if (body.has("scale")) out.add("scale", body.get("scale").deepCopy());
            options.add(option.getKey(), out);
        }
        String defaultSize = List.of("small", "medium", "large").stream()
            .filter(candidate -> !options.has(candidate)).findFirst().orElseThrow();
        return axisShape(defaultSize, List.of("small", "medium", "large"), options);
    }

    private void appendLayerRows(@NotNull JsonArray out, @NotNull JsonObject v2, @NotNull String id, @NotNull String baseGeometry) {
        if (!v2.has("layers")) return;
        for (JsonElement element : v2.getAsJsonArray("layers")) {
            JsonObject layer = element.getAsJsonObject();
            if (!id.equals(layer.get("id").getAsString())) continue;
            JsonObject overlay = layer.getAsJsonObject("overlay");
            String geometry = overlay.has("geometry") ? key(overlay.get("geometry").getAsString()) : baseGeometry;
            JsonObject row = new JsonObject();
            row.addProperty("id", id);
            JsonObject inner = new JsonObject();
            if ("collar".equals(id)) {
                JsonObject when = new JsonObject();
                when.addProperty("state", "tame");          // legacy collar fiction re-emitted (D42)
                row.add("when", when);
                inner.addProperty("geometry_ref", geometry);
                inner.addProperty("texture_ref", strip(overlay.get("texture").getAsString()));
                inner.add("tint_by", overlay.get("tint_by").deepCopy());
            } else {
                row.add("when", layer.get("when").deepCopy());
                inner.addProperty("geometry_ref", geometry);
                inner.add("texture_by", overlay.get("texture_by").deepCopy());
            }
            row.add("overlay", inner);
            out.add(row);
        }
    }

    private void appendEquipmentRows(@NotNull JsonArray out, @NotNull JsonObject v2) {
        if (!v2.has("layers")) return;
        for (JsonElement element : v2.getAsJsonArray("layers")) {
            JsonObject layer = element.getAsJsonObject();
            JsonObject when = layer.getAsJsonObject("when");
            if (!when.has("equipment")) continue;
            JsonObject overlay = layer.getAsJsonObject("overlay");
            JsonObject row = new JsonObject();
            row.add("id", layer.get("id").deepCopy());
            row.add("when", when.deepCopy());
            JsonObject inner = new JsonObject();
            inner.addProperty("geometry_ref", key(overlay.get("geometry").getAsString()));
            inner.add("texture_template", overlay.get("texture_template").deepCopy());
            inner.add("default_material", overlay.get("default_material").deepCopy());
            row.add("overlay", inner);
            out.add(row);
        }
    }

    // ------------------------------------------------------------------------------------
    // helpers
    // ------------------------------------------------------------------------------------

    private @NotNull String key(@NotNull String coordinate) {
        String legacy = this.geometryKeys.get(coordinate);
        if (legacy == null) throw new IllegalStateException("No legacy geometry key for coordinate " + coordinate);
        return legacy;
    }

    private static @NotNull String strip(@NotNull String path) {
        if (!path.startsWith(TEXTURE_PREFIX) || !path.endsWith(TEXTURE_SUFFIX))
            throw new IllegalStateException("Unexpected entity texture path " + path);
        return path.substring(TEXTURE_PREFIX.length(), path.length() - TEXTURE_SUFFIX.length());
    }

    private static @NotNull JsonObject single(@NotNull String key, @NotNull JsonObject value) {
        JsonObject object = new JsonObject();
        object.add(key, value);
        return object;
    }

    private static @NotNull JsonObject axisShape(@NotNull String defaultValue, @NotNull List<String> values, @NotNull JsonObject options) {
        JsonObject axis = new JsonObject();
        axis.addProperty("default", defaultValue);
        JsonArray array = new JsonArray();
        for (String value : values) array.add(value);
        axis.add("values", array);
        axis.add("options", options);
        return axis;
    }

    private static void attach(@NotNull JsonObject family, @NotNull String name, @NotNull JsonObject axis) {
        JsonObject axes = family.has("axes") ? family.getAsJsonObject("axes") : new JsonObject();
        axes.add(name, axis);
        if (!family.has("axes")) family.add("axes", axes);
    }

}
