package lib.minecraft.renderer.tooling;

import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import lib.minecraft.renderer.pipeline.AssetPipelineOptions;
import lib.minecraft.renderer.pipeline.client.ClientJarDownloader;
import lib.minecraft.renderer.pipeline.client.HttpFetcher;
import lib.minecraft.renderer.tooling.entity.BindPoseDiscovery;
import lib.minecraft.renderer.tooling.entity.MobRegistryDiscovery;
import lib.minecraft.renderer.tooling.util.Diagnostics;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.zip.ZipFile;

/**
 * Entry point for the {@code bindPoses} Gradle task.
 * <p>
 * Downloads the Java client jar, scans for {@code Model} constructor rotations via
 * {@link BindPoseDiscovery}, and writes the results to
 * {@code src/main/resources/lib/minecraft/renderer/entity_bind_poses.json}. The runtime loader
 * ({@link lib.minecraft.renderer.pipeline.loader.EntityModelLoader EntityModelLoader}) overlays
 * these onto each bone's {@code bindPoseRotation} field, standing in for the Bedrock animation
 * system that our static renderer can't execute.
 * <p>
 * Re-run on a Minecraft version bump. Output is deterministic: entities whose {@code Model}
 * constructor applies no static rotations drop out, and the remaining entries are sorted
 * alphabetically so a regenerated file diffs cleanly against the previous run.
 */
@UtilityClass
public final class ToolingBindPoses {

    /** Bundled output - per-entity bind-pose rotations keyed by namespaced entity id. */
    private static final @NotNull Path OUTPUT_PATH =
        Path.of("src/main/resources/lib/minecraft/renderer/entity_bind_poses.json");

    /** Namespace prefix applied to every emitted entity id. */
    private static final @NotNull String MINECRAFT_NAMESPACE = "minecraft:";

    /**
     * Runs the generator.
     *
     * @param args ignored - all output paths are fixed
     * @throws IOException if the client jar can't be downloaded or the output file can't be written
     */
    public static void main(String @NotNull [] args) throws IOException {
        HttpFetcher fetcher = new HttpFetcher();

        System.out.println("Downloading Minecraft client jar for bind-pose discovery...");
        Path clientJar = ClientJarDownloader.download(AssetPipelineOptions.defaults(), fetcher);

        Diagnostics diagnostics = new Diagnostics();
        Map<String, Map<String, BindPoseDiscovery.Pose>> poses;
        try (ZipFile zip = new ZipFile(clientJar.toFile())) {
            var mobs = MobRegistryDiscovery.discover(zip, diagnostics);
            System.out.println("Discovered " + mobs.size() + " living mob entities");

            poses = BindPoseDiscovery.discover(zip, mobs, diagnostics);
        }
        diagnostics.entries().forEach(System.out::println);

        System.out.println("Extracted bind poses for " + poses.size() + " entities");
        poses.forEach((id, bones) -> System.out.printf("  %s: %d bones%n", id, bones.size()));

        Files.createDirectories(OUTPUT_PATH.getParent());
        Files.writeString(OUTPUT_PATH, buildJson(poses));
        System.out.println("Wrote " + OUTPUT_PATH.toAbsolutePath());
    }

    /**
     * Serialises the pose map into a stable-ordered JSON document.
     */
    private static @NotNull String buildJson(@NotNull Map<String, Map<String, BindPoseDiscovery.Pose>> poses) {
        JsonObject root = new JsonObject();
        root.addProperty("//", "Generated by ToolingBindPoses. Per-bone rest-pose rotations (pitch, yaw, roll in degrees) plus pivot positions (px, py, pz) extracted from Java client Model factories. Loaded by EntityModelLoader as bind_pose_rotation overrides - the pivot lets the loader match a Java bind-pose to a Bedrock bone positionally when the names disagree (spider leg0..7 vs left_front_leg/etc.). Run ./gradlew :asset-renderer:bindPoses on a Minecraft version bump.");

        JsonObject entities = new JsonObject();
        Map<String, Map<String, BindPoseDiscovery.Pose>> sorted = new LinkedHashMap<>(poses);
        sorted.entrySet().stream()
            .sorted(Map.Entry.comparingByKey())
            .forEach(e -> entities.add(MINECRAFT_NAMESPACE + e.getKey(), buildEntityEntry(e.getValue())));
        root.add("entities", entities);

        return new GsonBuilder().setPrettyPrinting().create().toJson(root) + System.lineSeparator();
    }

    /**
     * Builds one entity's {@code bone_name -> {rotation:[pitch,yaw,roll], pivot:[px,py,pz]}}
     * block. Bone entries are sorted alphabetically so diffs across runs highlight real
     * changes, not key-ordering churn.
     */
    private static @NotNull JsonObject buildEntityEntry(@NotNull Map<String, BindPoseDiscovery.Pose> bones) {
        JsonObject entry = new JsonObject();
        bones.entrySet().stream()
            .sorted(Map.Entry.comparingByKey())
            .forEach(bone -> {
                JsonObject boneEntry = new JsonObject();
                JsonArray rot = new JsonArray();
                rot.add(bone.getValue().pitch());
                rot.add(bone.getValue().yaw());
                rot.add(bone.getValue().roll());
                boneEntry.add("rotation", rot);

                JsonArray piv = new JsonArray();
                piv.add(bone.getValue().pivotX());
                piv.add(bone.getValue().pivotY());
                piv.add(bone.getValue().pivotZ());
                boneEntry.add("pivot", piv);

                entry.add(bone.getKey(), boneEntry);
            });
        return entry;
    }

}
