package lib.minecraft.renderer.tooling;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import lib.minecraft.renderer.exception.PipelineException;
import lib.minecraft.renderer.exception.ToolingException;
import lib.minecraft.renderer.pipeline.Pipeline;
import lib.minecraft.renderer.pipeline.PipelineOptions;
import lib.minecraft.renderer.pipeline.loader.BlockStateLoader;
import lib.minecraft.renderer.tooling.util.AsmKit;
import lib.minecraft.renderer.tooling.util.ClassNodeCache;
import lib.minecraft.renderer.tooling.util.VanillaSourceClasses;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.FieldInsnNode;
import org.objectweb.asm.tree.InvokeDynamicInsnNode;
import org.objectweb.asm.tree.LdcInsnNode;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.TypeInsnNode;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

/**
 * Entry point invoked by the {@code blockStates} Gradle task.
 * <p>
 * Downloads (or reuses the cached) MC 26.1 client jar, runs {@link Parser} over the vanilla
 * {@code Blocks} registry and each block's constructor chain, and writes the resulting
 * default-state / variant-key table to
 * {@code src/main/resources/lib/minecraft/renderer/block_states.json}. The runtime pipeline
 * reads the JSON via {@link BlockStateLoader}, so the ASM walker is never on the production
 * classpath - the only people who run it are developers bumping the bundled snapshot when a new
 * Minecraft version ships.
 * <p>
 * The default state is derived from the {@code registerDefaultState(this.stateDefinition.any()
 * .setValue(...)...)} chain in each block's constructor; the variant-key list is the key set of
 * the block's {@code assets/minecraft/blockstates/<id>.json} (variants-style files only - multipart
 * files carry no discrete variant keys and emit an empty list).
 */
@UtilityClass
public final class ToolingBlockStates {

    /**
     * Fixed output path for the bundled block-defaults resource.
     */
    private static final @NotNull Path OUTPUT_PATH = Path.of("src/main/resources/lib/minecraft/renderer/block_states.json");

    /**
     * Runs the generator.
     *
     * @param args ignored - the output path is fixed to keep the resource location stable
     * @throws IOException if writing the JSON file fails
     */
    public static void main(String @NotNull [] args) throws IOException {
        PipelineOptions options = PipelineOptions.defaults();
        Path jarPath;
        try {
            jarPath = Pipeline.downloadJarToCache(options);
        } catch (PipelineException ex) {
            System.err.println("Failed to download client jar for block-defaults generation: " + ex.getMessage());
            throw ex;
        }
        System.out.println("Parsing block defaults from " + jarPath);

        Map<String, Parser.Entry> defaults = Parser.parse(jarPath);
        System.out.println("Parser produced " + defaults.size() + " block-default entries");

        Files.createDirectories(OUTPUT_PATH.getParent());
        Files.writeString(OUTPUT_PATH, buildJson(defaults, options.getVersion()));
        System.out.println("Wrote " + OUTPUT_PATH.toAbsolutePath());
    }

    /**
     * Serialises the parsed table into the bundled JSON format. The header comment records the
     * source jar version so a future contributor can tell at a glance how stale the snapshot is.
     */
    private static @NotNull String buildJson(@NotNull Map<String, Parser.Entry> defaults, @NotNull String mcVersion) {
        JsonObject root = new JsonObject();
        root.addProperty("//", "Generated by ToolingBlockStates. Default state from ASM bytewalk of "
            + "registerDefaultState; variants list from blockstate JSON. Run the tooling/blockStates Gradle task to refresh.");
        root.addProperty("source_version", mcVersion);

        JsonObject blocks = new JsonObject();
        for (Map.Entry<String, Parser.Entry> entry : defaults.entrySet()) {
            JsonObject obj = new JsonObject();
            obj.addProperty("default", entry.getValue().defaultKey());
            JsonArray variants = new JsonArray();
            for (String key : entry.getValue().variants())
                variants.add(key);
            obj.add("variants", variants);
            blocks.add(entry.getKey(), obj);
        }
        root.add("blocks", blocks);

        return new GsonBuilder().setPrettyPrinting().create().toJson(root) + System.lineSeparator();
    }

    /**
     * An ASM bytecode walker that recovers each block's canonical default state from the vanilla
     * {@code Blocks} registry, plus the variant-key enumeration from blockstate JSON.
     * <p>
     * Default-state extraction proceeds in passes over a single cached client jar:
     * <ol>
     * <li><b>Property name map</b> - {@code BlockStateProperties.<clinit>} maps each
     *     {@code FOO} field to its serialised property name (the literal first arg of the
     *     {@code XProperty.create("name", ...)} call). Block-local property fields that simply
     *     redirect to a {@code BlockStateProperties} constant (or to their own {@code create}
     *     call) are resolved on demand and cached.</li>
     * <li><b>Enum value names</b> - each enum class referenced as a {@code setValue} value is
     *     walked once for its constant -&gt; serialised-name map. Vanilla enums store the
     *     serialised name as the second {@code String} constructor argument
     *     ({@code TOP("top")}); enums without one fall back to {@code name().toLowerCase(ROOT)}.</li>
     * <li><b>Blocks registry + constructor chains</b> - {@code Blocks.<clinit>} pairs each
     *     {@code register("id", Foo::new, ...)} with its block class (resolved through the
     *     {@code Foo::new} method-reference indy or a registration-helper's inner lambda), then
     *     the block's constructor chain is walked for the {@code registerDefaultState} call and
     *     its {@code setValue(property, value)} chain decoded.</li>
     * </ol>
     */
    static final class Parser {

        private static final @NotNull String BLOCK_INTERNAL = "net/minecraft/world/level/block/Block";
        private static final @NotNull String INTEGER_BOXED = "java/lang/Integer";
        private static final @NotNull String BOOLEAN_BOXED = "java/lang/Boolean";
        private static final @NotNull String PROPERTY_DESC_SUFFIX = "Property;";
        private static final @NotNull String MAP_DESC = "Ljava/util/Map;";
        private static final @NotNull String LIST_DESC = "Ljava/util/List;";
        private static final @NotNull String LIST_INTERNAL = "java/util/List";
        private static final @NotNull String FOR_EACH = "forEach";
        private static final @NotNull String FUNCTION_RETURN_SUFFIX = ")Ljava/util/function/Function;";
        private static final @NotNull String VALUE_OF = "valueOf";
        private static final @NotNull String CREATE = "create";
        private static final @NotNull String SET_VALUE = "setValue";
        private static final @NotNull String REGISTER_DEFAULT_STATE = "registerDefaultState";
        private static final @NotNull String REGISTER_PREFIX = "register";
        private static final @NotNull String BLOCK_RETURN_DESC = ")L" + BLOCK_INTERNAL + ";";
        private static final @NotNull String STRING_ARG_PREFIX = "(Ljava/lang/String;";
        private static final @NotNull String RESOURCE_KEY_ARG_PREFIX = "(Lnet/minecraft/resources/ResourceKey;";

        private final @NotNull ZipFile zip;
        private final @NotNull ClassNodeCache cache;
        private final @NotNull Gson gson = new Gson();

        /** {@code BlockStateProperties.FOO} field name to serialised property name. */
        private final @NotNull Map<String, String> bspNames = new HashMap<>();
        /** {@code BlockIds.FOO} {@code ResourceKey} field name to serialised block id. */
        private final @NotNull Map<String, String> blockIdsNames = new HashMap<>();
        /** Resolved {@code (owner, field)} property-field references to serialised property name. */
        private final @NotNull Map<String, String> propNameCache = new HashMap<>();
        /** Per-enum-class constant -&gt; serialised-name maps, keyed by enum internal name. */
        private final @NotNull Map<String, Map<String, String>> enumNameCache = new HashMap<>();
        /** Resolved {@code (owner, field)} property-field references to {@code any()}-default value. */
        private final @NotNull Map<String, String> defaultValueCache = new HashMap<>();
        /** Per-registration-helper resolved block class, keyed by helper method name. */
        private final @NotNull Map<String, String> helperClassCache = new HashMap<>();

        private Parser(@NotNull ZipFile zip) {
            this.zip = zip;
            this.cache = new ClassNodeCache(zip);
        }

        /**
         * The extracted metadata for a single block.
         *
         * @param defaultKey the sorted {@code property=value} default-state key, or empty
         * @param variants the sorted variant-key enumeration from blockstate JSON
         */
        record Entry(@NotNull String defaultKey, @NotNull List<String> variants) {}

        /**
         * Parses the vanilla block default-state + variant table out of the supplied client jar.
         *
         * @param jarPath the deobfuscated client jar to read from (MC 26.1+)
         * @return a sorted map of namespaced block id to extracted metadata
         * @throws ToolingException if the jar cannot be read or the {@code Blocks} class is absent
         */
        static @NotNull Map<String, Entry> parse(@NotNull Path jarPath) {
            try (ZipFile zip = new ZipFile(jarPath.toFile())) {
                return new Parser(zip).run();
            } catch (IOException ex) {
                throw new ToolingException(ex, "Failed to read client jar '%s' for block defaults", jarPath);
            }
        }

        private @NotNull Map<String, Entry> run() {
            buildBspNameMap();
            buildBlockIdsMap();

            ClassNode blocks = AsmKit.requireClass(this.cache, VanillaSourceClasses.BLOCKS, "Blocks");
            MethodNode clinit = AsmKit.requireClinit(blocks, "Blocks");

            TreeMap<String, Entry> out = new TreeMap<>();
            String pendingId = null;
            String ctorClass = null;

            for (AbstractInsnNode node = clinit.instructions.getFirst(); node != null; node = node.getNext()) {
                String literal = AsmKit.readStringLiteral(node);
                if (literal != null) {
                    pendingId = literal;
                    ctorClass = null;
                    continue;
                }

                // The 26.x register(ResourceKey, Function, Properties) overload sources its id from a
                // GETSTATIC BlockIds.FOO rather than a "foo" string literal (stems, copper bars/chains/
                // lanterns, item frames). Map the field back to its serialised id so these blocks are
                // discovered like the string-literal register("foo", ...) calls.
                if (node instanceof FieldInsnNode field
                    && field.getOpcode() == Opcodes.GETSTATIC
                    && field.owner.equals(VanillaSourceClasses.BLOCK_IDS)) {
                    String mapped = this.blockIdsNames.get(field.name);
                    if (mapped != null) {
                        pendingId = mapped;
                        ctorClass = null;
                    }
                    continue;
                }

                if (node instanceof InvokeDynamicInsnNode indy
                    && indy.desc.endsWith(FUNCTION_RETURN_SUFFIX)
                    && pendingId != null
                    && isPendingIdSource(AsmKit.previousReal(indy), pendingId)) {
                    ctorClass = AsmKit.resolveLambdaTargetClass(indy, blocks);
                    continue;
                }

                if (node instanceof MethodInsnNode call
                    && call.getOpcode() == Opcodes.INVOKESTATIC
                    && call.owner.equals(VanillaSourceClasses.BLOCKS)
                    && call.name.startsWith(REGISTER_PREFIX)
                    && (call.desc.startsWith(STRING_ARG_PREFIX) || call.desc.startsWith(RESOURCE_KEY_ARG_PREFIX))
                    && call.desc.endsWith(BLOCK_RETURN_DESC)) {

                    if (pendingId != null) {
                        String blockClass = ctorClass != null ? ctorClass : resolveHelperClass(blocks, call.name);
                        if (blockClass != null) {
                            String blockId = "minecraft:" + pendingId;
                            out.put(blockId, new Entry(decodeDefaultState(blockClass), readVariantKeys(pendingId)));
                        }
                    }
                    pendingId = null;
                    ctorClass = null;
                }
            }

            return out;
        }

        /**
         * Returns {@code true} when {@code node} is the id source for {@code pendingId} - either an
         * {@code LDC} of the literal id (the {@code register("foo", ...)} form) or a {@code GETSTATIC
         * BlockIds.FOO} whose mapped id matches (the {@code register(ResourceKey, ...)} form). Used
         * to confirm a block-constructor reference indy immediately follows its block-id source
         * rather than a stray {@code Function}-producing lambda elsewhere in the chain.
         */
        private boolean isPendingIdSource(@Nullable AbstractInsnNode node, @NotNull String pendingId) {
            if (node instanceof LdcInsnNode ldc && pendingId.equals(ldc.cst)) return true;
            return node instanceof FieldInsnNode field
                && field.getOpcode() == Opcodes.GETSTATIC
                && field.owner.equals(VanillaSourceClasses.BLOCK_IDS)
                && pendingId.equals(this.blockIdsNames.get(field.name));
        }

        // -------------------------------------------------------------------------------------
        // Pass 1 - property name map
        // -------------------------------------------------------------------------------------

        /**
         * Populates {@link #bspNames} by walking {@code BlockStateProperties.<clinit>}: each
         * {@code XProperty.create("name", ...)} call (whatever the overload) is immediately
         * preceded by the property-name string literal and followed by a {@code PUTSTATIC} into
         * the field that holds it.
         */
        private void buildBspNameMap() {
            ClassNode bsp = AsmKit.requireClass(this.cache, VanillaSourceClasses.BLOCK_STATE_PROPERTIES, "BlockStateProperties");
            MethodNode clinit = AsmKit.requireClinit(bsp, "BlockStateProperties");

            String lastString = null;
            String createName = null;
            for (AbstractInsnNode node = clinit.instructions.getFirst(); node != null; node = node.getNext()) {
                String literal = AsmKit.readStringLiteral(node);
                if (literal != null) {
                    lastString = literal;
                    continue;
                }
                if (node instanceof MethodInsnNode call
                    && call.getOpcode() == Opcodes.INVOKESTATIC
                    && call.name.equals(CREATE)
                    && call.owner.endsWith(PROPERTY_DESC_SUFFIX.substring(0, PROPERTY_DESC_SUFFIX.length() - 1))) {
                    createName = lastString;
                    continue;
                }
                if (AsmKit.isPutStatic(node, VanillaSourceClasses.BLOCK_STATE_PROPERTIES) && createName != null) {
                    this.bspNames.put(((FieldInsnNode) node).name, createName);
                    createName = null;
                }
            }
        }

        /**
         * Populates {@link #blockIdsNames} by walking {@code BlockIds.<clinit>}: each field is
         * assigned {@code createKey("id")} preceded by the id string literal, so the literal that
         * most recently appeared before a {@code PUTSTATIC BlockIds.FOO} is that field's id. Absent
         * {@code BlockIds} (older jars) leaves the map empty - the {@code register(ResourceKey, ...)}
         * path then discovers nothing extra, matching the pre-26.x behaviour.
         */
        private void buildBlockIdsMap() {
            ClassNode blockIds = this.cache.load(VanillaSourceClasses.BLOCK_IDS);
            if (blockIds == null) return;
            MethodNode clinit = AsmKit.findMethod(blockIds, AsmKit.CLINIT);
            if (clinit == null) return;

            String lastString = null;
            for (AbstractInsnNode node = clinit.instructions.getFirst(); node != null; node = node.getNext()) {
                String literal = AsmKit.readStringLiteral(node);
                if (literal != null) {
                    lastString = literal;
                    continue;
                }
                if (AsmKit.isPutStatic(node, VanillaSourceClasses.BLOCK_IDS) && lastString != null) {
                    this.blockIdsNames.put(((FieldInsnNode) node).name, lastString);
                    lastString = null;
                }
            }
        }

        /**
         * Resolves a property-field reference (any {@code GETSTATIC <owner>.<field>} whose type is
         * an {@code XProperty}) to its serialised property name. Handles the common block-local
         * redirect ({@code SweetBerryBushBlock.AGE = BlockStateProperties.AGE_3}) and direct
         * {@code create} initialisation, recursing through redirect chains.
         *
         * @param owner the field owner's JVM internal name
         * @param field the field name
         * @return the serialised property name, or {@code null} when it can't be resolved
         */
        private @Nullable String resolvePropertyName(@NotNull String owner, @NotNull String field) {
            if (owner.equals(VanillaSourceClasses.BLOCK_STATE_PROPERTIES))
                return this.bspNames.get(field);

            String key = owner + '.' + field;
            if (this.propNameCache.containsKey(key)) return this.propNameCache.get(key);
            // Guard against redirect cycles by reserving the slot before recursing.
            this.propNameCache.put(key, null);

            String resolved = resolvePropertyNameUncached(owner, field);
            this.propNameCache.put(key, resolved);
            return resolved;
        }

        private @Nullable String resolvePropertyNameUncached(@NotNull String owner, @NotNull String field) {
            AbstractInsnNode value = findFieldInitValue(owner, field);
            if (value == null) return null;
            // Redirect: AGE = BlockStateProperties.AGE_3
            if (value.getOpcode() == Opcodes.GETSTATIC && value instanceof FieldInsnNode src
                && src.desc.endsWith(PROPERTY_DESC_SUFFIX))
                return resolvePropertyName(src.owner, src.name);
            // Direct create: FOO = XProperty.create("name", ...)
            if (value instanceof MethodInsnNode call && call.name.equals(CREATE)) {
                AbstractInsnNode name = AsmKit.findPreceding(call, n -> AsmKit.readStringLiteral(n) != null, op -> true);
                return name == null ? null : AsmKit.readStringLiteral(name);
            }
            return null;
        }

        /**
         * Returns the value-producing instruction assigned to a static field, searching the owner
         * class, its superclass chain, and its implemented-interface graph (static property fields
         * are commonly declared on a marker interface, e.g. {@code CaveVines.BERRIES}). Returns
         * {@code null} when no {@code PUTSTATIC <class>.<field>} is found anywhere in the graph.
         */
        private @Nullable AbstractInsnNode findFieldInitValue(@NotNull String owner, @NotNull String field) {
            FieldInsnNode put = findPutStaticNode(owner, field);
            return put == null ? null : AsmKit.previousReal(put);
        }

        /**
         * Finds the {@code PUTSTATIC <class>.<field>} instruction assigning a static field,
         * searching the owner class, its superclass chain, and its implemented-interface graph.
         * Returns {@code null} when no such assignment is found.
         */
        private @Nullable FieldInsnNode findPutStaticNode(@NotNull String owner, @NotNull String field) {
            java.util.ArrayDeque<String> queue = new java.util.ArrayDeque<>();
            Set<String> visited = new java.util.HashSet<>();
            queue.add(owner);
            while (!queue.isEmpty()) {
                String current = queue.poll();
                if (AsmKit.OBJECT_INTERNAL.equals(current) || !visited.add(current)) continue;
                ClassNode cn = this.cache.load(current);
                if (cn == null) continue;
                MethodNode clinit = AsmKit.findMethod(cn, AsmKit.CLINIT);
                if (clinit != null)
                    for (AbstractInsnNode node = clinit.instructions.getFirst(); node != null; node = node.getNext())
                        if (AsmKit.isPutStatic(node, current, field)) return (FieldInsnNode) node;
                if (cn.superName != null) queue.add(cn.superName);
                if (cn.interfaces != null) queue.addAll(cn.interfaces);
            }
            return null;
        }

        // -------------------------------------------------------------------------------------
        // Pass 2 - enum serialised names
        // -------------------------------------------------------------------------------------

        /**
         * Returns the serialised name of an enum constant ({@code Direction.NORTH -> "north"}),
         * lazily walking the enum class's {@code <clinit>} for its full constant map and caching
         * the result.
         *
         * @param enumOwner the enum class's JVM internal name
         * @param constant the enum constant field name
         * @return the serialised name, or a lowercased fallback when the scan can't resolve it
         */
        private @NotNull String enumSerializedName(@NotNull String enumOwner, @NotNull String constant) {
            Map<String, String> names = this.enumNameCache.computeIfAbsent(enumOwner, this::buildEnumNameMap);
            String serialized = names.get(constant);
            return serialized != null ? serialized : constant.toLowerCase(Locale.ROOT);
        }

        /**
         * Walks an enum class's {@code <clinit>} for the canonical {@code NEW; DUP; ldc "NAME";
         * <ordinal>; (ldc "serialized";)? ...; INVOKESPECIAL <init>; PUTSTATIC NAME} sequence,
         * mapping each constant field name to its serialised name (the second string literal, or
         * the lowercased constant name when absent).
         */
        private @NotNull Map<String, String> buildEnumNameMap(@NotNull String enumOwner) {
            // Insertion order matters: firstEnumConstant() relies on it to find ordinal 0.
            Map<String, String> map = new LinkedHashMap<>();
            ClassNode cn = this.cache.load(enumOwner);
            if (cn == null) return map;
            MethodNode clinit = AsmKit.findMethod(cn, AsmKit.CLINIT);
            if (clinit == null) return map;

            boolean collecting = false;
            List<String> strings = new ArrayList<>();
            List<String> pending = null;
            for (AbstractInsnNode node = clinit.instructions.getFirst(); node != null; node = node.getNext()) {
                if (node.getOpcode() == Opcodes.NEW && node instanceof TypeInsnNode type && type.desc.equals(enumOwner)) {
                    collecting = true;
                    strings = new ArrayList<>();
                    continue;
                }
                if (collecting) {
                    String literal = AsmKit.readStringLiteral(node);
                    if (literal != null) {
                        strings.add(literal);
                        continue;
                    }
                    if (AsmKit.isInvokeSpecial(node, enumOwner, AsmKit.INIT)) {
                        collecting = false;
                        pending = strings;
                        continue;
                    }
                }
                if (AsmKit.isPutStatic(node, enumOwner) && pending != null) {
                    String field = ((FieldInsnNode) node).name;
                    String serialized = pending.size() >= 2 ? pending.get(1)
                        : pending.isEmpty() ? field.toLowerCase(Locale.ROOT) : pending.getFirst().toLowerCase(Locale.ROOT);
                    map.put(field, serialized);
                    pending = null;
                }
            }
            return map;
        }

        // -------------------------------------------------------------------------------------
        // Pass 3 - constructor chain + registerDefaultState decode
        // -------------------------------------------------------------------------------------

        /**
         * Resolves the block class produced by a registration helper ({@code registerStair},
         * {@code registerBed}, ...) by walking the helper body for its inner block-creating
         * lambda and resolving that lambda's target class. Cached per helper name.
         */
        private @Nullable String resolveHelperClass(@NotNull ClassNode blocks, @NotNull String helperName) {
            if (helperName.equals(REGISTER_PREFIX)) return null;
            if (this.helperClassCache.containsKey(helperName)) return this.helperClassCache.get(helperName);

            String resolved = null;
            MethodNode helper = AsmKit.findMethod(blocks, helperName);
            if (helper != null) {
                for (AbstractInsnNode node = helper.instructions.getFirst(); node != null; node = node.getNext()) {
                    if (node instanceof InvokeDynamicInsnNode indy && indy.desc.endsWith(FUNCTION_RETURN_SUFFIX)) {
                        resolved = AsmKit.resolveLambdaTargetClass(indy, blocks);
                        if (resolved != null) break;
                    }
                }
            }
            this.helperClassCache.put(helperName, resolved);
            return resolved;
        }

        /** A property-field reference - the {@code GETSTATIC owner.field} site of a property. */
        private record FieldRef(@NotNull String owner, @NotNull String field) {}

        /**
         * Reconstructs a block's canonical default state, mirroring vanilla
         * {@code defaultBlockState()}: every property declared by {@code createBlockStateDefinition}
         * (across the class hierarchy) starts at its {@code any()}-default (the first possible
         * value), then explicit {@code setValue} overrides from the {@code registerDefaultState}
         * chain are applied (leaf class wins). The result is the sorted {@code property=value} key.
         *
         * @param blockClass the block class's JVM internal name
         * @return the sorted default-state key, or empty when the block declares no properties
         */
        private @NotNull String decodeDefaultState(@NotNull String blockClass) {
            Map<String, FieldRef> declared = collectDeclaredProperties(blockClass);

            // Explicit setValue overrides from every registerDefaultState in the chain; the leaf
            // class is visited first, so putIfAbsent gives it precedence over parent defaults.
            Map<String, String> explicit = new HashMap<>();
            AsmKit.walkConstructorChain(this.cache, blockClass, ctor -> {
                for (Map.Entry<String, String> pair : extractSetValues(ctor).entrySet())
                    explicit.putIfAbsent(pair.getKey(), pair.getValue());
            });

            Map<String, String> resolved = new TreeMap<>();
            for (Map.Entry<String, FieldRef> entry : declared.entrySet()) {
                String value = explicit.get(entry.getKey());
                if (value == null) value = anyDefault(entry.getValue());
                if (value != null) resolved.put(entry.getKey(), value);
            }
            // Defensive: surface any explicitly-set property the state-definition walk missed.
            for (Map.Entry<String, String> pair : explicit.entrySet())
                resolved.putIfAbsent(pair.getKey(), pair.getValue());

            StringBuilder sb = new StringBuilder();
            for (Map.Entry<String, String> pair : resolved.entrySet()) {
                if (!sb.isEmpty()) sb.append(',');
                sb.append(pair.getKey()).append('=').append(pair.getValue());
            }
            return sb.toString();
        }

        /**
         * Collects every property declared in the block's {@code createBlockStateDefinition}
         * methods up the class hierarchy. Every property-typed {@code GETSTATIC} in those methods
         * is an added property, so the name set is the block's full property set.
         *
         * @param blockClass the block class's JVM internal name
         * @return property name to its defining field reference, in declaration order
         */
        private @NotNull Map<String, FieldRef> collectDeclaredProperties(@NotNull String blockClass) {
            Map<String, FieldRef> declared = new LinkedHashMap<>();
            AsmKit.walkSuperChain(this.cache, blockClass, cn -> {
                MethodNode method = AsmKit.findMethod(cn, "createBlockStateDefinition");
                if (method == null) return;
                for (AbstractInsnNode node = method.instructions.getFirst(); node != null; node = node.getNext()) {
                    if (node.getOpcode() == Opcodes.GETSTATIC && node instanceof FieldInsnNode field
                        && field.desc.endsWith(PROPERTY_DESC_SUFFIX)) {
                        if (field.desc.charAt(0) == '[') {
                            // Static Property[] element: GETSTATIC arr ; <index> ; AALOAD.
                            AbstractInsnNode idxNode = AsmKit.nextReal(node);
                            AbstractInsnNode aaload = AsmKit.nextReal(idxNode);
                            Integer index = idxNode == null ? null : AsmKit.readIntLiteral(idxNode);
                            if (index != null && aaload != null && aaload.getOpcode() == Opcodes.AALOAD)
                                addDeclared(declared, readStaticPropertyArrayElement(field.owner, field.name, index));
                        } else {
                            addDeclared(declared, new FieldRef(field.owner, field.name));
                        }
                        continue;
                    }
                    // Property returned by a no-arg accessor, e.g. getSegmentAmountProperty().
                    if ((node.getOpcode() == Opcodes.INVOKEVIRTUAL || node.getOpcode() == Opcodes.INVOKESTATIC)
                        && node instanceof MethodInsnNode call
                        && call.desc.startsWith("()") && call.desc.endsWith(PROPERTY_DESC_SUFFIX)
                        && call.desc.charAt(2) != '[') {
                        addDeclared(declared, resolveMethodReturnedProperty(blockClass, call.name, call.desc));
                        continue;
                    }
                    // Property selected from a Map<Direction, Property> by a single-argument
                    // accessor, e.g. MultifaceBlock.getFaceProperty(Direction) reading
                    // PROPERTY_BY_DIRECTION inside the per-direction createBlockStateDefinition loop.
                    // The no-arg branch above skips it (it takes a Direction), so resolve every
                    // property the map can return - the loop adds one per supported direction.
                    if ((node.getOpcode() == Opcodes.INVOKEVIRTUAL || node.getOpcode() == Opcodes.INVOKESTATIC)
                        && node instanceof MethodInsnNode call
                        && !call.desc.startsWith("()") && call.desc.endsWith(PROPERTY_DESC_SUFFIX)
                        && !call.desc.contains(")["))
                        for (FieldRef ref : resolveDirectionPropertyMapValues(call.owner, call.name, call.desc))
                            addDeclared(declared, ref);
                    // Properties iterated from a static List and added one-by-one, e.g.
                    // ChiseledBookShelfBlock's SLOT_OCCUPIED_PROPERTIES.forEach(builder::add).
                    // A GETSTATIC <field>:Ljava/util/List; consumed by a List.forEach - resolve the
                    // list's element properties from where it's built (List.of(...) in the clinit).
                    if (node.getOpcode() == Opcodes.GETSTATIC && node instanceof FieldInsnNode listField
                        && listField.desc.equals(LIST_DESC) && isFollowedByListForEach(node))
                        for (FieldRef ref : resolvePropertyListElements(listField.owner, listField.name))
                            addDeclared(declared, ref);
                }
            });
            return declared;
        }

        /**
         * Returns {@code true} when {@code start} (a {@code GETSTATIC ...List;}) is consumed by a
         * later {@code List.forEach} in the same method - the iterate-into-the-builder shape
         * ({@code SLOT_OCCUPIED_PROPERTIES.forEach(builder::add)}), as opposed to an incidental
         * list reference.
         */
        private static boolean isFollowedByListForEach(@NotNull AbstractInsnNode start) {
            for (AbstractInsnNode node = start.getNext(); node != null; node = node.getNext())
                if (node.getOpcode() == Opcodes.INVOKEINTERFACE && node instanceof MethodInsnNode call
                    && call.owner.equals(LIST_INTERNAL) && call.name.equals(FOR_EACH))
                    return true;
            return false;
        }

        /**
         * Resolves the property element field references of a static {@code List<Property>}, e.g.
         * {@code ChiseledBookShelfBlock.SLOT_OCCUPIED_PROPERTIES = List.of(SLOT_0_OCCUPIED, ...)}.
         * Locates the list's {@code PUTSTATIC} in the owning class's {@code <clinit>}, confirms the
         * value-producing call is a {@code List.of} / {@code copyOf}, then collects every property
         * {@code GETSTATIC} feeding that build (in declaration order) - covering both the fixed-arg
         * {@code of(a, b, ...)} shape and the {@code of(new Property[]{...})} array shape.
         *
         * @param owner the list field's owner JVM internal name
         * @param field the list field name
         * @return the element property field references in declaration order, or empty when unresolved
         */
        private @NotNull List<FieldRef> resolvePropertyListElements(@NotNull String owner, @NotNull String field) {
            FieldInsnNode put = findPutStaticNode(owner, field);
            if (put == null) return List.of();
            AbstractInsnNode build = AsmKit.previousReal(put);
            if (!(build instanceof MethodInsnNode of) || of.getOpcode() != Opcodes.INVOKESTATIC
                || !of.desc.endsWith(")" + LIST_DESC))
                return List.of();

            // Walk back from the List build to the preceding statement (the prior field's PUTSTATIC,
            // or the method start), collecting every property GETSTATIC. For List.of(a, b, ...)
            // these are the consecutive arg getstatics; for List.of(new Property[]{...}) they are
            // the ANEWARRAY/AASTORE element getstatics. Pushing while walking back then reading the
            // deque head-to-tail restores declaration order.
            java.util.Deque<FieldRef> ordered = new java.util.ArrayDeque<>();
            for (AbstractInsnNode node = AsmKit.previousReal(of); node != null; node = AsmKit.previousReal(node)) {
                if (node.getOpcode() == Opcodes.PUTSTATIC) break;
                if (node.getOpcode() == Opcodes.GETSTATIC && node instanceof FieldInsnNode prop
                    && prop.desc.endsWith(PROPERTY_DESC_SUFFIX) && prop.desc.charAt(0) != '[')
                    ordered.push(new FieldRef(prop.owner, prop.name));
            }
            return new ArrayList<>(ordered);
        }

        /**
         * Resolves a property field reference to its serialised name and records it under that
         * name (first writer wins, preserving declaration order). No-ops on a {@code null} ref or
         * an unresolvable name.
         */
        private void addDeclared(@NotNull Map<String, FieldRef> declared, @Nullable FieldRef ref) {
            if (ref == null) return;
            String name = resolvePropertyName(ref.owner(), ref.field());
            if (name != null) declared.putIfAbsent(name, ref);
        }

        /**
         * Resolves the property at {@code index} of a static {@code Property[]} field by scanning
         * the owning class's {@code <clinit>} for the array build ({@code ANEWARRAY ... (DUP;
         * <i>; GETSTATIC prop; AASTORE)*}) and returning the element's field reference.
         *
         * @param owner the array field's owner JVM internal name
         * @param arrayField the array field name
         * @param index the element index
         * @return the element property's field reference, or {@code null} when unresolved
         */
        private @Nullable FieldRef readStaticPropertyArrayElement(@NotNull String owner, @NotNull String arrayField, int index) {
            FieldInsnNode put = findPutStaticNode(owner, arrayField);
            if (put == null) return null;
            AbstractInsnNode anew = AsmKit.findPreceding(put, n -> n.getOpcode() == Opcodes.ANEWARRAY, op -> true);
            if (anew == null) return null;
            for (AbstractInsnNode node = AsmKit.nextReal(anew); node != null && node != put; node = AsmKit.nextReal(node)) {
                if (node.getOpcode() != Opcodes.DUP) continue;
                AbstractInsnNode idxNode = AsmKit.nextReal(node);
                AbstractInsnNode valNode = AsmKit.nextReal(idxNode);
                AbstractInsnNode storeNode = AsmKit.nextReal(valNode);
                if (idxNode == null || valNode == null || storeNode == null) continue;
                Integer i = AsmKit.readIntLiteral(idxNode);
                if (i == null || i != index) continue;
                if (valNode.getOpcode() == Opcodes.GETSTATIC && valNode instanceof FieldInsnNode prop
                    && storeNode.getOpcode() == Opcodes.AASTORE)
                    return new FieldRef(prop.owner, prop.name);
            }
            return null;
        }

        /**
         * Resolves the property field returned by a no-arg accessor (e.g.
         * {@code getSegmentAmountProperty()}) by searching the class graph for the method body -
         * most-derived first so an override wins - and returning the first property
         * {@code GETSTATIC} it reads.
         *
         * @param startClass the most-derived block class to begin the search at
         * @param methodName the accessor method name
         * @param methodDesc the accessor method descriptor
         * @return the returned property's field reference, or {@code null} when unresolved
         */
        private @Nullable FieldRef resolveMethodReturnedProperty(@NotNull String startClass, @NotNull String methodName, @NotNull String methodDesc) {
            java.util.ArrayDeque<String> queue = new java.util.ArrayDeque<>();
            Set<String> visited = new java.util.HashSet<>();
            queue.add(startClass);
            while (!queue.isEmpty()) {
                String current = queue.poll();
                if (AsmKit.OBJECT_INTERNAL.equals(current) || !visited.add(current)) continue;
                ClassNode cn = this.cache.load(current);
                if (cn == null) continue;
                MethodNode method = AsmKit.findMethod(cn, methodName, methodDesc);
                if (method != null && method.instructions.size() > 0)
                    for (AbstractInsnNode node = method.instructions.getFirst(); node != null; node = node.getNext())
                        if (node.getOpcode() == Opcodes.GETSTATIC && node instanceof FieldInsnNode f
                            && f.desc.endsWith(PROPERTY_DESC_SUFFIX) && f.desc.charAt(0) != '[')
                            return new FieldRef(f.owner, f.name);
                if (cn.superName != null) queue.add(cn.superName);
                if (cn.interfaces != null) queue.addAll(cn.interfaces);
            }
            return null;
        }

        /**
         * Resolves every property a single-argument accessor selects from a
         * {@code Map<Direction, Property>}, e.g. {@code MultifaceBlock.getFaceProperty(Direction)}
         * reading {@code PROPERTY_BY_DIRECTION}. The per-direction {@code createBlockStateDefinition}
         * loop adds one property per supported face, so the block declares the map's full value set.
         * Finds the accessor body, follows its {@code GETSTATIC <map>:Ljava/util/Map;} (through any
         * {@code MAP = OtherClass.MAP} redirect) to the class that builds the map, and returns every
         * property field referenced in that class's {@code <clinit>}, deduplicated by serialised name.
         *
         * @param startClass the accessor's owner JVM internal name
         * @param methodName the accessor method name
         * @param methodDesc the accessor method descriptor
         * @return the map's property field references, or empty when the shape doesn't match
         */
        private @NotNull List<FieldRef> resolveDirectionPropertyMapValues(@NotNull String startClass, @NotNull String methodName, @NotNull String methodDesc) {
            FieldInsnNode mapField = findAccessorMapField(startClass, methodName, methodDesc);
            if (mapField == null) return List.of();

            // Follow MAP = OtherClass.MAP redirects to the class that actually builds the map
            // (MultifaceBlock.PROPERTY_BY_DIRECTION = PipeBlock.PROPERTY_BY_DIRECTION).
            String owner = mapField.owner;
            String field = mapField.name;
            for (int depth = 0; depth < 8; depth++) {
                AbstractInsnNode init = findFieldInitValue(owner, field);
                if (init != null && init.getOpcode() == Opcodes.GETSTATIC && init instanceof FieldInsnNode redirect
                    && redirect.desc.equals(MAP_DESC)) {
                    owner = redirect.owner;
                    field = redirect.name;
                } else {
                    break;
                }
            }

            ClassNode declaring = this.cache.load(owner);
            if (declaring == null) return List.of();
            MethodNode clinit = AsmKit.findMethod(declaring, AsmKit.CLINIT);
            if (clinit == null) return List.of();

            // Every property GETSTATIC in the map's declaring class clinit is one of the map's
            // values (both the field-init source and the put-into-map read resolve to the same
            // serialised name); dedup keeps one field reference per face property.
            Map<String, FieldRef> byName = new LinkedHashMap<>();
            for (AbstractInsnNode node = clinit.instructions.getFirst(); node != null; node = node.getNext())
                if (node.getOpcode() == Opcodes.GETSTATIC && node instanceof FieldInsnNode prop
                    && prop.desc.endsWith(PROPERTY_DESC_SUFFIX) && prop.desc.charAt(0) != '[') {
                    String name = resolvePropertyName(prop.owner, prop.name);
                    if (name != null) byName.putIfAbsent(name, new FieldRef(prop.owner, prop.name));
                }
            return new ArrayList<>(byName.values());
        }

        /**
         * Finds the {@code GETSTATIC <map>:Ljava/util/Map;} a single-argument property accessor
         * reads from, searching the class graph (most-derived first) for the method body. Returns
         * {@code null} when the accessor reads no map field.
         */
        private @Nullable FieldInsnNode findAccessorMapField(@NotNull String startClass, @NotNull String methodName, @NotNull String methodDesc) {
            java.util.ArrayDeque<String> queue = new java.util.ArrayDeque<>();
            Set<String> visited = new java.util.HashSet<>();
            queue.add(startClass);
            while (!queue.isEmpty()) {
                String current = queue.poll();
                if (AsmKit.OBJECT_INTERNAL.equals(current) || !visited.add(current)) continue;
                ClassNode cn = this.cache.load(current);
                if (cn == null) continue;
                MethodNode method = AsmKit.findMethod(cn, methodName, methodDesc);
                if (method != null && method.instructions.size() > 0)
                    for (AbstractInsnNode node = method.instructions.getFirst(); node != null; node = node.getNext())
                        if (node.getOpcode() == Opcodes.GETSTATIC && node instanceof FieldInsnNode f
                            && f.desc.equals(MAP_DESC))
                            return f;
                if (cn.superName != null) queue.add(cn.superName);
                if (cn.interfaces != null) queue.addAll(cn.interfaces);
            }
            return null;
        }

        /**
         * Decodes the explicit {@code property=value} pairs set by a constructor's
         * {@code registerDefaultState(...setValue(prop, value)...)} chain. Returns an empty map
         * when the constructor sets no default. Each {@code setValue} consumes the most recent
         * property reference and decoded value (int via {@code Integer.valueOf}, boolean via
         * {@code Boolean.valueOf}, enum via a constant {@code GETSTATIC}).
         */
        private @NotNull Map<String, String> extractSetValues(@NotNull MethodNode ctor) {
            Map<String, String> pairs = new HashMap<>();
            String pendingProp = null;
            String pendingValue = null;
            Integer lastInt = null;

            for (AbstractInsnNode node = ctor.instructions.getFirst(); node != null; node = node.getNext()) {
                Integer intLiteral = AsmKit.readIntLiteral(node);
                if (intLiteral != null) {
                    lastInt = intLiteral;
                    continue;
                }

                if (node.getOpcode() == Opcodes.GETSTATIC && node instanceof FieldInsnNode field) {
                    if (field.desc.endsWith(PROPERTY_DESC_SUFFIX))
                        pendingProp = resolvePropertyName(field.owner, field.name);
                    else
                        pendingValue = enumSerializedName(field.owner, field.name);
                    continue;
                }

                if (node instanceof MethodInsnNode call) {
                    if (call.getOpcode() == Opcodes.INVOKESTATIC && call.name.equals(VALUE_OF)) {
                        if (call.owner.equals(INTEGER_BOXED) && lastInt != null)
                            pendingValue = Integer.toString(lastInt);
                        else if (call.owner.equals(BOOLEAN_BOXED) && lastInt != null)
                            pendingValue = Boolean.toString(lastInt != 0);
                        continue;
                    }
                    if (call.getOpcode() == Opcodes.INVOKEVIRTUAL && call.name.equals(SET_VALUE)) {
                        if (pendingProp != null && pendingValue != null) pairs.put(pendingProp, pendingValue);
                        pendingProp = null;
                        pendingValue = null;
                        lastInt = null;
                        continue;
                    }
                    if (call.getOpcode() == Opcodes.INVOKEVIRTUAL && call.name.equals(REGISTER_DEFAULT_STATE))
                        break;
                }
            }
            return pairs;
        }

        // -------------------------------------------------------------------------------------
        // any()-default value resolution (first possible value of a property)
        // -------------------------------------------------------------------------------------

        /**
         * Resolves a property's {@code any()}-default - the first value of its possible-value set,
         * which is what {@code StateDefinition.any()} assigns. Locates the property's
         * {@code create(...)} call (following block-local redirects and the super-chain) and
         * decodes the default from its arguments. Cached per field reference.
         *
         * @param ref the property's defining field reference
         * @return the serialised default value, or {@code null} when it can't be resolved
         */
        private @Nullable String anyDefault(@NotNull FieldRef ref) {
            String key = ref.owner() + '.' + ref.field();
            if (this.defaultValueCache.containsKey(key)) return this.defaultValueCache.get(key);
            this.defaultValueCache.put(key, null);

            MethodInsnNode create = resolvePropertyCreateSite(ref.owner(), ref.field(), 0);
            String value = create == null ? null : defaultFromCreate(create);
            this.defaultValueCache.put(key, value);
            return value;
        }

        /**
         * Locates the {@code XProperty.create(...)} call that initializes a property field,
         * following block-local redirects ({@code FOO = BlockStateProperties.BAR}) and the
         * superclass chain (inherited static fields). Returns {@code null} when no create site is
         * reachable.
         */
        private @Nullable MethodInsnNode resolvePropertyCreateSite(@NotNull String owner, @NotNull String field, int depth) {
            if (depth > 8) return null;
            AbstractInsnNode value = findFieldInitValue(owner, field);
            if (value == null) return null;
            if (value.getOpcode() == Opcodes.GETSTATIC && value instanceof FieldInsnNode src
                && src.desc.endsWith(PROPERTY_DESC_SUFFIX))
                return resolvePropertyCreateSite(src.owner, src.name, depth + 1);
            if (value instanceof MethodInsnNode call && call.name.equals(CREATE))
                return call;
            return null;
        }

        /**
         * Decodes the {@code any()}-default value from a property {@code create(...)} call, by
         * overload: {@code IntegerProperty.create(name, min, max)} -&gt; {@code min};
         * {@code BooleanProperty.create(name)} -&gt; {@code true} (vanilla orders {@code true}
         * before {@code false}); {@code EnumProperty.create(name, class[, ...])} -&gt; the first
         * possible enum value.
         */
        private @Nullable String defaultFromCreate(@NotNull MethodInsnNode create) {
            if (create.owner.endsWith("IntegerProperty")) {
                // create(name, min, max): the deeper of the two trailing int literals is min.
                Integer min = null;
                for (AbstractInsnNode node = create.getPrevious(); node != null; node = node.getPrevious()) {
                    if (AsmKit.isPseudoNode(node)) continue;
                    if (AsmKit.readStringLiteral(node) != null) break;
                    Integer literal = AsmKit.readIntLiteral(node);
                    if (literal != null) min = literal;
                }
                return min == null ? null : Integer.toString(min);
            }
            if (create.owner.endsWith("BooleanProperty"))
                // StateDefinition.any() resolves an unset boolean to false (vanilla's
                // defaultBlockState for declared-but-unset booleans - verified against the
                // harness reference for multiface blocks' waterlogged / face properties).
                return "false";

            // EnumProperty - the class literal is the nearest preceding Type constant.
            AbstractInsnNode classNode = AsmKit.findPreceding(create, n -> AsmKit.readTypeLiteral(n) != null, op -> true);
            String enumOwner = classNode == null ? null : AsmKit.readTypeLiteral(classNode).getInternalName();
            if (enumOwner == null) return null;

            if (create.desc.endsWith("[Ljava/lang/Enum;)Lnet/minecraft/world/level/block/state/properties/EnumProperty;")) {
                // create(name, class, Enum[]): first value = the array's index-0 GETSTATIC.
                AbstractInsnNode anewarray = AsmKit.findPreceding(create,
                    n -> n.getOpcode() == Opcodes.ANEWARRAY, op -> true);
                if (anewarray != null) {
                    for (AbstractInsnNode node = anewarray; node != null && node != create; node = node.getNext())
                        if (node.getOpcode() == Opcodes.GETSTATIC && node instanceof FieldInsnNode v)
                            return enumSerializedName(v.owner, v.name);
                }
                return firstEnumConstant(enumOwner);
            }
            if (create.desc.endsWith("Ljava/util/function/Predicate;)Lnet/minecraft/world/level/block/state/properties/EnumProperty;")) {
                // create(name, class, predicate): a Direction.Plane filter resolves to the first
                // direction in that plane; any other (lambda) predicate falls back to the first
                // declared constant, which is correct for the simple "exclude one value" filters.
                AbstractInsnNode predicate = AsmKit.previousReal(create);
                if (predicate != null && predicate.getOpcode() == Opcodes.GETSTATIC && predicate instanceof FieldInsnNode plane) {
                    if (plane.name.equals("HORIZONTAL")) return "north";
                    if (plane.name.equals("VERTICAL")) return "down";
                }
                return firstEnumConstant(enumOwner);
            }
            // create(name, class): all constants, first by declaration order.
            return firstEnumConstant(enumOwner);
        }

        /**
         * Returns the serialised name of an enum class's first declared constant (ordinal 0),
         * which is the {@code any()}-default for an unfiltered {@code EnumProperty}.
         */
        private @Nullable String firstEnumConstant(@NotNull String enumOwner) {
            Map<String, String> names = this.enumNameCache.computeIfAbsent(enumOwner, this::buildEnumNameMap);
            return names.isEmpty() ? null : names.values().iterator().next();
        }

        // -------------------------------------------------------------------------------------
        // Variant-key enumeration from blockstate JSON
        // -------------------------------------------------------------------------------------

        /**
         * Reads the variant-key enumeration for a block from its
         * {@code assets/minecraft/blockstates/<id>.json}. Variants-style files emit their sorted
         * object key set; multipart-style files (and missing files) emit an empty list.
         *
         * @param shortId the block id without the {@code minecraft:} namespace
         * @return the sorted variant keys, or an empty list
         */
        private @NotNull List<String> readVariantKeys(@NotNull String shortId) {
            ZipEntry entry = this.zip.getEntry("assets/minecraft/blockstates/" + shortId + ".json");
            if (entry == null) return List.of();

            try (InputStream stream = this.zip.getInputStream(entry)) {
                String json = new String(stream.readAllBytes(), StandardCharsets.UTF_8);
                JsonObject root = this.gson.fromJson(json, JsonObject.class);
                if (root == null || !root.has("variants")) return List.of();
                Set<String> keys = new TreeSet<>(root.getAsJsonObject("variants").keySet());
                return new ArrayList<>(keys);
            } catch (IOException ex) {
                throw new ToolingException(ex, "Failed to read blockstate JSON for '%s'", shortId);
            }
        }

    }

}
