package lib.minecraft.renderer.tooling;

import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import lib.minecraft.renderer.exception.AssetPipelineException;
import lib.minecraft.renderer.geometry.Biome;
import lib.minecraft.renderer.asset.Block;
import lib.minecraft.renderer.pipeline.AssetPipelineOptions;
import lib.minecraft.renderer.pipeline.client.ClientJarDownloader;
import lib.minecraft.renderer.pipeline.client.HttpFetcher;
import lib.minecraft.renderer.pipeline.loader.BlockTintsLoader;
import lib.minecraft.renderer.tooling.asm.AsmKit;
import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentList;
import dev.simplified.collection.ConcurrentMap;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.FieldInsnNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Optional;
import java.util.zip.ZipFile;

/**
 * Entry point invoked by the {@code generateVanillaTints} Gradle task.
 * <p>
 * Downloads (or reuses the cached) MC 26.1 client jar, runs
 * {@link Parser} over its {@code BlockColors} class, and writes the resulting tint
 * table to {@code src/main/resources/renderer/block_tints.json}. The runtime pipeline reads
 * the JSON via {@link BlockTintsLoader} so the ASM walker is never on the
 * production classpath - the only people who run it are developers bumping the bundled tint
 * snapshot when a new Minecraft version ships.
 * <p>
 * The output file format mirrors the loader's expectations: a top-level {@code tints} array of
 * {@code {block, target, constant?}} objects, with constants stored as {@code 0x}-prefixed
 * uppercase hex strings (Gson cannot round-trip {@code 0x80000000}-class signed integers
 * literally).
 */
@UtilityClass
public final class ToolingBlockTints {

    /** Fixed output path for the bundled block-tint resource. */
    private static final @NotNull Path OUTPUT_PATH = Path.of("src/main/resources/renderer/block_tints.json");

    /**
     * Runs the generator.
     *
     * @param args ignored - the output path is fixed to keep the resource location stable
     * @throws IOException if writing the JSON file fails
     */
    public static void main(String @NotNull [] args) throws IOException {
        AssetPipelineOptions options = AssetPipelineOptions.defaults();
        Path jarPath;
        try {
            jarPath = ClientJarDownloader.download(options, new HttpFetcher());
        } catch (AssetPipelineException ex) {
            System.err.println("Failed to download client jar for vanilla tints generation: " + ex.getMessage());
            throw ex;
        }
        System.out.println("Parsing BlockColors from " + jarPath);

        ConcurrentMap<String, Block.Tint> tints = Parser.parse(jarPath);
        System.out.println("Parser produced " + tints.size() + " block tint entries");

        Files.createDirectories(OUTPUT_PATH.getParent());
        Files.writeString(OUTPUT_PATH, buildJson(tints, options.getVersion()));
        System.out.println("Wrote " + OUTPUT_PATH.toAbsolutePath());
    }

    /**
     * Serialises the parsed tint list into the bundled JSON format. The header comment notes
     * the source jar version so a future contributor can tell at a glance how stale the snapshot
     * is.
     */
    private static @NotNull String buildJson(@NotNull ConcurrentMap<String, Block.Tint> tints, @NotNull String mcVersion) {
        JsonObject root = new JsonObject();
        root.addProperty("//", "Generated by ToolingBlockTints. From net.minecraft.client.color.block.BlockColors$createDefault(). Run the tooling/blockTints Gradle task to refresh.");
        root.addProperty("source_version", mcVersion);

        JsonArray entries = new JsonArray();
        tints.forEach((blockId, tint) -> {
            JsonObject entry = new JsonObject();
            entry.addProperty("block", blockId);
            entry.addProperty("target", tint.target().name());
            tint.constant().ifPresent(value -> entry.addProperty("constant", String.format("0x%08X", value)));
            entries.add(entry);
        });
        root.add("tints", entries);

        return new GsonBuilder().setPrettyPrinting().create().toJson(root) + System.lineSeparator();
    }


    /**
     * An ASM bytecode walker that parses
     * {@code net.minecraft.client.color.block.BlockColors$createDefault()} from a deobfuscated
     * Minecraft client jar and translates its registration calls into {@link Block.Tint} entities.
     * <p>
     * The parser only handles deobfuscated jars - that is, MC 26.1 and later, where Mojang ships
     * source-equivalent class names. Older obfuscated jars cannot be parsed without a remapping
     * pass, which would require multiple bytecode-shape variants and per-version mapping plumbing
     * that the project explicitly does not pursue. The runtime pipeline reads
     * {@code /renderer/block_tints.json} from the classpath instead; this parser is invoked only
     * by the {@code generateVanillaTints} Gradle task to refresh that resource on a version bump.
     * <p>
     * Parsing approach: load the class through ASM's tree model, walk
     * {@code createDefault()}'s {@link InsnList} tracking three pieces of pending state:
     * <ul>
     * <li>the last {@code BlockTintSources.X()} factory call (the tint source),</li>
     * <li>any {@code ldc}/{@code bipush}/{@code iconst} integers preceding a {@code constant(int)}
     *     or {@code constant(int, int)} call (the ARGB values), and</li>
     * <li>every {@code GETSTATIC Blocks.X} field reference (the affected blocks).</li>
     * </ul>
     * When a {@code register(List, Block[])} call is hit, one {@link Block.Tint} is emitted per
     * collected block - provided the source method is one we recognise - and the running state is
     * reset. Multi-source registrations (recognisable by the 2-arg {@code List.of} overload) are
     * skipped because the atlas renderer cannot tint individual sprite layers.
     *
     * @see BlockTintsLoader
     * @see Block.Tint
     * @see Biome.TintTarget
     */
    @UtilityClass
    static class Parser {

        private static final @NotNull String BLOCK_COLORS_INTERNAL_NAME = "net/minecraft/client/color/block/BlockColors";
        private static final @NotNull String BLOCK_TINT_SOURCES_INTERNAL_NAME = "net/minecraft/client/color/block/BlockTintSources";
        private static final @NotNull String BLOCKS_INTERNAL_NAME = "net/minecraft/world/level/block/Blocks";
        private static final @NotNull String CREATE_DEFAULT_METHOD_NAME = "createDefault";
        private static final @NotNull String REGISTER_METHOD_NAME = "register";
        private static final @NotNull String LIST_INTERNAL_NAME = "java/util/List";
        private static final @NotNull String LIST_OF_SINGLE_DESCRIPTOR = "(Ljava/lang/Object;)Ljava/util/List;";

        /**
         * Maps the short name of a {@code BlockTintSources.X()} factory method to the corresponding
         * {@link Biome.TintTarget}. Sources whose tint depends on dynamic per-block state - water,
         * waterParticles, redstone, stem - are not in the map and are silently dropped because the
         * atlas renderer cannot resolve them at static-render time.
         */
        private static final @NotNull ConcurrentMap<String, Biome.TintTarget> SUPPORTED_SOURCES = buildSupportedSources();

        /** Builds the {@link #SUPPORTED_SOURCES} policy table. */
        private static @NotNull ConcurrentMap<String, Biome.TintTarget> buildSupportedSources() {
            ConcurrentMap<String, Biome.TintTarget> map = Concurrent.newMap();
            // GRASS colormap sources - the BlockTintSources helper distinguishes several grass
            // variants (grass, grassBlock with its top-face-only sampling, sugarCane's biome
            // modifier, doubleTallGrass for large_fern / tall_grass), all of which sample the grass
            // colormap at render time. For atlas rendering they collapse to the same target.
            map.put("grass", Biome.TintTarget.GRASS);
            map.put("grassBlock", Biome.TintTarget.GRASS);
            map.put("sugarCane", Biome.TintTarget.GRASS);
            map.put("doubleTallGrass", Biome.TintTarget.GRASS);
            map.put("foliage", Biome.TintTarget.FOLIAGE);
            map.put("dryFoliage", Biome.TintTarget.DRY_FOLIAGE);
            return map;
        }

        /**
         * Parses the vanilla block tint table out of {@code BlockColors.createDefault()} in the
         * supplied client jar.
         *
         * @param jarPath the deobfuscated client jar to read from (MC 26.1+)
         * @return a map of block id to tint binding
         * @throws AssetPipelineException if the jar cannot be read, the BlockColors class is not
         *     present (jar is obfuscated or from an unsupported version), or {@code createDefault}
         *     is missing
         */
        public static @NotNull ConcurrentMap<String, Block.Tint> parse(@NotNull Path jarPath) {
            try (ZipFile zip = new ZipFile(jarPath.toFile())) {
                ClassNode classNode = AsmKit.requireClass(zip, BLOCK_COLORS_INTERNAL_NAME, "BlockColors");
                MethodNode createDefault = AsmKit.findMethod(classNode, CREATE_DEFAULT_METHOD_NAME);
                if (createDefault == null)
                    throw new AssetPipelineException(
                        "BlockColors class does not expose a '%s' method - jar may be obfuscated or from an unsupported version",
                        CREATE_DEFAULT_METHOD_NAME
                    );
                return parseCreateDefault(createDefault.instructions);
            } catch (IOException ex) {
                throw new AssetPipelineException(ex, "Failed to read BlockColors class from jar '%s'", jarPath);
            }
        }

        /**
         * Walks the {@code createDefault()} instruction list and emits a {@link Block.Tint} per
         * recognised {@code (source, blocks[])} registration. See the class-level javadoc for the
         * recognition rules.
         */
        private static @NotNull ConcurrentMap<String, Block.Tint> parseCreateDefault(@NotNull InsnList instructions) {
            ConcurrentMap<String, Block.Tint> tints = Concurrent.newMap();

            @Nullable String pendingSource = null;
            int pendingConstantA = 0;
            int pendingConstantB = 0;
            int pendingConstantCount = 0;
            int pendingSourceLayers = 0;
            ConcurrentList<String> pendingBlocks = Concurrent.newList();
            AsmKit.LiteralStack intLiteralStack = new AsmKit.LiteralStack(4);

            for (AbstractInsnNode node = instructions.getFirst(); node != null; node = node.getNext()) {
                int opcode = node.getOpcode();

                // Track integer literals so we can consume them when a constant(...) factory call
                // appears. BlockTintSources.constant(int) is preceded by one int; constant(int, int)
                // by two. Only the last few literals matter because intervening bytecode (ANEWARRAY,
                // AASTORE, etc.) never pushes ints that would survive to the constant() call.
                Integer literal = AsmKit.readIntLiteral(node);
                if (literal != null) {
                    intLiteralStack.push(literal);
                    continue;
                }

                switch (node) {
                    case FieldInsnNode fieldInsn when opcode == Opcodes.GETSTATIC -> {
                        if (fieldInsn.owner.equals(BLOCKS_INTERNAL_NAME))
                            pendingBlocks.add(blockIdFromField(fieldInsn.name));
                    }
                    case MethodInsnNode methodInsn when opcode == Opcodes.INVOKESTATIC -> {
                        if (methodInsn.owner.equals(BLOCK_TINT_SOURCES_INTERNAL_NAME)) {
                            pendingSource = methodInsn.name;
                            pendingSourceLayers++;

                            if (methodInsn.name.equals("constant") && methodInsn.desc.startsWith("(I")) {
                                if (methodInsn.desc.equals("(I)Lnet/minecraft/client/color/block/BlockTintSource;")) {
                                    pendingConstantA = popIntOrZero(intLiteralStack);
                                    pendingConstantCount = 1;
                                } else if (methodInsn.desc.equals("(II)Lnet/minecraft/client/color/block/BlockTintSource;")) {
                                    pendingConstantB = popIntOrZero(intLiteralStack);
                                    pendingConstantA = popIntOrZero(intLiteralStack);
                                    pendingConstantCount = 2;
                                }
                            }
                        } else if (methodInsn.owner.equals(LIST_INTERNAL_NAME) && methodInsn.name.equals("of")
                            && !methodInsn.desc.equals(LIST_OF_SINGLE_DESCRIPTOR)) {
                            // Multi-argument List.of call means the register() block composes multiple
                            // sources (e.g. [BLANK_LAYER, grass()] for pink_petals). Skip it.
                            pendingSource = null;
                        }
                    }
                    case MethodInsnNode methodInsn when opcode == Opcodes.INVOKEVIRTUAL && methodInsn.owner.equals(BLOCK_COLORS_INTERNAL_NAME) && methodInsn.name.equals(REGISTER_METHOD_NAME) -> {

                        if (pendingSource != null && pendingSourceLayers == 1 && !pendingBlocks.isEmpty())
                            emitTints(tints, pendingSource, pendingConstantA, pendingConstantB, pendingConstantCount, pendingBlocks);

                        pendingSource = null;
                        pendingConstantA = 0;
                        pendingConstantB = 0;
                        pendingConstantCount = 0;
                        pendingSourceLayers = 0;
                        pendingBlocks.clear();
                        intLiteralStack.reset();
                    }
                    default -> { }
                }

            }

            return tints;
        }

        /**
         * Pops the most recent int off the running literal stack, returning {@code 0} when the
         * stack is empty or the top is not an int. Used to grab the {@code ldc}/{@code bipush}
         * constants that preceded a {@code BlockTintSources.constant(int)} or
         * {@code constant(int, int)} call.
         */
        private static int popIntOrZero(@NotNull AsmKit.LiteralStack stack) {
            Integer value = stack.popInt();
            return value != null ? value : 0;
        }

        /**
         * Emits one {@link Block.Tint} per block for the current pending registration, after
         * verifying the source method is one the renderer knows how to sample. Unsupported sources
         * (water, waterParticles, redstone, stem) are silently dropped.
         */
        private static void emitTints(
            @NotNull ConcurrentMap<String, Block.Tint> tints,
            @NotNull String sourceMethod,
            int constantA,
            int constantB,
            int constantCount,
            @NotNull ConcurrentList<String> blocks
        ) {
            Biome.TintTarget target;
            Optional<Integer> constant = Optional.empty();

            if (sourceMethod.equals("constant")) {
                target = Biome.TintTarget.CONSTANT;
                // BlockTintSources.constant(int, int) is the two-colour overload used for lily_pad:
                // first int is the in-world colour, second is the GUI default. Atlas rendering is
                // item-perspective, so the GUI default wins.
                int argb = constantCount == 2 ? constantB : constantA;
                constant = Optional.of(argb);
            } else {
                Biome.TintTarget mapped = SUPPORTED_SOURCES.get(sourceMethod);
                if (mapped == null) return;
                target = mapped;
            }

            Block.Tint tint = new Block.Tint(target, constant);
            for (String blockId : blocks)
                tints.put(blockId, tint);
        }

        /**
         * Derives a namespaced block id from the {@code Blocks.X} static field name.
         * Convention is straight {@code toLowerCase()}: {@code Blocks.GRASS_BLOCK} - &gt;
         * {@code minecraft:grass_block}.
         */
        private static @NotNull String blockIdFromField(@NotNull String fieldName) {
            return "minecraft:" + fieldName.toLowerCase();
        }

    }


}
