package lib.minecraft.renderer.tooling;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import lib.minecraft.renderer.exception.PipelineException;
import lib.minecraft.renderer.exception.ToolingException;
import lib.minecraft.renderer.pipeline.PipelineOptions;
import lib.minecraft.renderer.pipeline.Pipeline;
import lib.minecraft.renderer.pipeline.loader.GlintItemsLoader;
import lib.minecraft.renderer.tooling.util.AsmKit;
import lib.minecraft.renderer.tooling.util.VanillaSourceClasses;
import dev.simplified.gson.GsonSettings;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.FieldInsnNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.MethodNode;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Set;
import java.util.TreeSet;
import java.util.zip.ZipFile;

/**
 * Entry point invoked by the {@code glintItems} Gradle task.
 * <p>
 * Downloads (or reuses the cached) MC 26.1 client jar, runs {@link Parser} over its
 * {@code Items} class, and writes the resulting "always glinted" item-id set to
 * {@code src/main/resources/lib/minecraft/renderer/glint_items.json}. The runtime pipeline reads the
 * JSON via {@link GlintItemsLoader} so the ASM walker is never on the production classpath - the
 * only people who run it are developers bumping the bundled snapshot when a new Minecraft version
 * ships.
 * <p>
 * "Always glinted" items are the ones vanilla registers with the default data component
 * {@code minecraft:enchantment_glint_override = true} (enchanted_book, written_book,
 * enchanted_golden_apple, experience_bottle, nether_star, debug_stick, end_crystal): they render
 * with the enchantment foil sheen regardless of whether a specific stack carries enchantments.
 * <p>
 * The output file format mirrors {@link ToolingPotionColors}'s shape: a top-level {@code items}
 * array of namespaced id strings, sorted so the checked-in JSON diffs stay reviewable.
 */
@UtilityClass
public final class ToolingGlintItems {

    /**
     * Fixed output path for the bundled always-glinted item resource.
     */
    private static final @NotNull Path OUTPUT_PATH = Path.of("src/main/resources/lib/minecraft/renderer/glint_items.json");

    /**
     * Shared pretty-printing Gson carrying the renderer's registered type adapters.
     */
    private static final @NotNull Gson PRETTY_GSON = GsonSettings.defaults().mutate().isPrettyPrint().isHtmlEscaping(false).build().create();

    /**
     * Runs the generator.
     *
     * @param args ignored - the output path is fixed to keep the resource location stable
     * @throws IOException if writing the JSON file fails
     */
    public static void main(String @NotNull [] args) throws IOException {
        PipelineOptions options = PipelineOptions.defaults();
        Path jarPath;
        try {
            jarPath = Pipeline.downloadJarToCache(options);
        } catch (PipelineException ex) {
            System.err.println("Failed to download client jar for glint-item generation: " + ex.getMessage());
            throw ex;
        }
        System.out.println("Parsing Items from " + jarPath);

        Set<String> glintItems = Parser.parse(jarPath);
        System.out.println("Parser produced " + glintItems.size() + " always-glinted item entries");

        Files.createDirectories(OUTPUT_PATH.getParent());
        Files.writeString(OUTPUT_PATH, buildJson(glintItems, options.getVersion()));
        System.out.println("Wrote " + OUTPUT_PATH.toAbsolutePath());
    }

    /**
     * Serialises the parsed id set into the bundled JSON format. Entries are sorted by id so the
     * checked-in JSON has stable ordering across version bumps.
     */
    private static @NotNull String buildJson(@NotNull Set<String> glintItems, @NotNull String mcVersion) {
        JsonObject root = new JsonObject();
        root.addProperty("//", "Generated by ToolingGlintItems. Items whose Items registration sets DataComponents.ENCHANTMENT_GLINT_OVERRIDE=true. Run the tooling/glintItems Gradle task to refresh.");
        root.addProperty("source_version", mcVersion);

        JsonArray items = new JsonArray();
        new TreeSet<>(glintItems).forEach(items::add);
        root.add("items", items);

        return PRETTY_GSON.toJson(root) + System.lineSeparator();
    }

    /**
     * An ASM bytecode walker that parses {@code net.minecraft.world.item.Items}'s static
     * initializer and extracts the set of item ids whose {@code Item.Properties} chain sets
     * {@code DataComponents.ENCHANTMENT_GLINT_OVERRIDE} to {@code true}.
     * <p>
     * Walks the class-constructor instruction list and recognises the vanilla registration pattern:
     * <pre>
     *   ldc "item_id"                                      // item id (first arg to register*)
     *   new net/minecraft/world/item/Item$Properties       // builder
     *   ... chained builder calls ...
     *   getstatic DataComponents.ENCHANTMENT_GLINT_OVERRIDE // glint component
     *   iconst_1                                            // = true
     *   invokestatic Boolean.valueOf
     *   invokevirtual Item$Properties.component
     *   invokestatic registerItem(...)
     *   putstatic Items.FIELD:Item                          // ends one registration
     * </pre>
     * Tracks the first LDC string since the last registration (the item id) and a pending-glint
     * flag set when {@code GETSTATIC ENCHANTMENT_GLINT_OVERRIDE} is immediately followed by the
     * {@code iconst_1} (true) literal. On the terminating {@code PUTSTATIC} of an {@code Item} field
     * the {@code (id, glint)} pair is committed and the running state resets - so glint set on one
     * item never bleeds into the next.
     */
    @UtilityClass
    static class Parser {

        private static final @NotNull String ENCHANTMENT_GLINT_OVERRIDE_FIELD = "ENCHANTMENT_GLINT_OVERRIDE";
        private static final @NotNull String ITEM_FIELD_DESCRIPTOR = "L" + VanillaSourceClasses.ITEM + ";";

        /**
         * Parses the always-glinted item set out of {@code Items}'s static initializer in the
         * supplied client jar.
         *
         * @param jarPath the deobfuscated client jar to read from (MC 26.1+)
         * @return the set of namespaced item ids that carry an always-on glint override
         * @throws ToolingException if the jar cannot be read or the class is missing
         */
        public static @NotNull Set<String> parse(@NotNull Path jarPath) {
            try (ZipFile zip = new ZipFile(jarPath.toFile())) {
                var classNode = AsmKit.requireClass(zip, VanillaSourceClasses.ITEMS, "Items");
                MethodNode clinit = AsmKit.requireClinit(classNode, "Items");
                return parseClinit(clinit.instructions);
            } catch (IOException ex) {
                throw new ToolingException(ex, "Failed to read Items class from jar '%s'", jarPath);
            }
        }

        /**
         * Walks the {@code <clinit>} instruction list and collects one namespaced id per item whose
         * Properties chain sets the glint override to {@code true}. See the parser javadoc for the
         * recognition rules.
         */
        private static @NotNull Set<String> parseClinit(@NotNull InsnList instructions) {
            TreeSet<String> glintItems = new TreeSet<>();

            @Nullable String pendingItemId = null;
            boolean pendingGlint = false;

            for (AbstractInsnNode node = instructions.getFirst(); node != null; node = node.getNext()) {
                String str = AsmKit.readStringLiteral(node);
                if (str != null) {
                    // The item id is the first LDC string after the previous registration (its first
                    // register* arg); keep it stable so any later string in the builder chain is ignored.
                    if (pendingItemId == null) pendingItemId = str;
                    continue;
                }

                if (AsmKit.isGetStatic(node, VanillaSourceClasses.DATA_COMPONENTS, ENCHANTMENT_GLINT_OVERRIDE_FIELD)) {
                    // The component value is pushed straight after the getstatic; iconst_1 means true.
                    AbstractInsnNode next = AsmKit.nextReal(node);
                    Integer value = next == null ? null : AsmKit.readIntLiteral(next);
                    if (value != null && value == 1) pendingGlint = true;
                    continue;
                }

                // Each registration ends by storing the built Item into a static Item field; commit
                // the pending pair here and reset so glint never carries into the next registration.
                if (AsmKit.isPutStatic(node, VanillaSourceClasses.ITEMS)
                    && node instanceof FieldInsnNode fieldInsn
                    && fieldInsn.desc.equals(ITEM_FIELD_DESCRIPTOR)) {
                    if (pendingGlint && pendingItemId != null)
                        glintItems.add("minecraft:" + pendingItemId);
                    pendingItemId = null;
                    pendingGlint = false;
                }
            }

            return glintItems;
        }

    }

}
