package lib.minecraft.renderer.tooling;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import lib.minecraft.renderer.exception.ToolingException;
import lib.minecraft.renderer.pipeline.loader.PotionColorLoader;
import lib.minecraft.renderer.tooling.util.AsmKit;
import lib.minecraft.renderer.tooling.util.ToolingJson;
import lib.minecraft.renderer.tooling.util.ToolingPipeline;
import lib.minecraft.renderer.tooling.util.VanillaSourceClasses;
import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentMap;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;

import java.io.IOException;
import java.nio.file.Path;
import java.util.Map;
import java.util.TreeMap;
import java.util.zip.ZipFile;

/**
 * Entry point invoked by the {@code potionColors} Gradle task.
 * <p>
 * Downloads (or reuses the cached) MC 26.1 client jar, runs {@link Parser} over its
 * {@code MobEffects} class, and writes the resulting effect colour table to
 * {@code src/main/resources/lib/minecraft/renderer/potion_colors.json}. The runtime pipeline reads the JSON
 * via {@link PotionColorLoader} so the ASM walker is never on the production classpath - the
 * only people who run it are developers bumping the bundled potion colour snapshot when a new
 * Minecraft version ships.
 * <p>
 * The output file shares the general shape of the other bundled snapshots (a {@code "//"} header
 * comment plus {@code source_version}, followed by a single array of objects): here a top-level
 * {@code effects} array of {@code {effect, color}} objects, with the fully-opaque ARGB colour
 * stored as a {@code 0x}-prefixed uppercase 8-digit hex string. Entries are sorted by effect id so
 * diffs stay reviewable on version bumps.
 */
@UtilityClass
public final class ToolingPotionColors {

    /**
     * Fixed output path for the bundled potion-colour resource.
     */
    private static final @NotNull Path OUTPUT_PATH = Path.of("src/main/resources/lib/minecraft/renderer/potion_colors.json");

    /**
     * Runs the generator.
     *
     * @param args ignored - the output path is fixed to keep the resource location stable
     * @throws IOException if writing the JSON file fails
     */
    public static void main(String @NotNull [] args) throws IOException {
        ToolingPipeline.JarSource jar = ToolingPipeline.downloadJar("potion colour generation");
        Path jarPath = jar.jarPath();
        System.out.println("Parsing MobEffects from " + jarPath);

        ConcurrentMap<String, Integer> colors = Parser.parse(jarPath);
        System.out.println("Parser produced " + colors.size() + " potion effect colour entries");

        ToolingJson.writeResource(OUTPUT_PATH,
            "Generated by ToolingPotionColors. From net.minecraft.world.effect.MobEffects clinit. Run the tooling/potionColors Gradle task to refresh.",
            jar.options().getVersion(), "effects", buildEffects(colors));
    }

    /**
     * Builds the {@code effects} array: one {@code {effect, color}} object per parsed entry, sorted by
     * effect id (via {@link TreeMap}) so the checked-in JSON is stable across version bumps. Each colour
     * is forced fully opaque ({@code | 0xFF000000}) and written as a {@code 0x}-prefixed uppercase
     * 8-digit hex string, matching what {@link PotionColorLoader} expects. The {@code //} header +
     * {@code source_version} envelope is added by {@link ToolingJson#writeResource}.
     *
     * @param colors the parsed effect-id to ARGB colour map
     * @return the {@code effects} array
     */
    private static @NotNull JsonArray buildEffects(@NotNull ConcurrentMap<String, Integer> colors) {
        JsonArray entries = new JsonArray();
        // Sort deterministically so the checked-in JSON has stable ordering.
        Map<String, Integer> sorted = new TreeMap<>(colors);
        sorted.forEach((effectId, color) -> {
            JsonObject entry = new JsonObject();
            entry.addProperty("effect", effectId);
            entry.addProperty("color", String.format("0x%08X", color | 0xFF000000));
            entries.add(entry);
        });
        return entries;
    }

    /**
     * An ASM bytecode walker that parses {@code net.minecraft.world.effect.MobEffects}'s static
     * initializer and extracts one {@code effectId - &gt; argb} mapping per registered effect.
     * <p>
     * Walks the class-constructor instruction list and recognises the vanilla registration pattern:
     * <pre>
     *   ldc "effect_id"                                    // effect id
     *   new net/minecraft/world/effect/MobEffect           // (or a subclass)
     *   dup
     *   getstatic MobEffectCategory.BENEFICIAL             // category
     *   ldc 0xRRGGBB                                       // colour
     *   invokespecial &lt;effect class&gt;.&lt;init&gt;(category, int)
     *   ... optional chained builder calls ...
     *   invokestatic MobEffects.register(String, MobEffect)
     *   putstatic FIELD:Holder
     * </pre>
     * Tracks the most-recent LDC string and an int-literal stack; on {@code invokespecial} of a
     * {@code net/minecraft/world/effect/**MobEffect}{@code .<init>(Category, I)V}, the top int is
     * captured as the pending colour; on {@code invokestatic} of {@code register}, a
     * {@code (pendingId, pendingColour)} pair is emitted and state resets.
     */
    @UtilityClass
    static class Parser {

        /**
         * Descriptor of the {@code MobEffect} constructor whose trailing int argument is the ARGB
         * colour - {@code (MobEffectCategory, int)void}.
         */
        private static final @NotNull String MOB_EFFECT_INIT_DESCRIPTOR = "(Lnet/minecraft/world/effect/MobEffectCategory;I)V";

        /**
         * Name of the {@code MobEffects.register} helper whose call site terminates one effect
         * registration and emits the pending {@code (effectId, colour)} pair.
         */
        private static final @NotNull String REGISTER_METHOD_NAME = "register";

        /**
         * Parses the vanilla potion effect colour table out of {@code MobEffects}'s static
         * initializer in the supplied client jar.
         *
         * @param jarPath the deobfuscated client jar to read from (MC 26.1+)
         * @return a map of effect id to ARGB colour
         * @throws ToolingException if the jar cannot be read or the class is missing
         */
        public static @NotNull ConcurrentMap<String, Integer> parse(@NotNull Path jarPath) {
            try (ZipFile zip = new ZipFile(jarPath.toFile())) {
                ClassNode classNode = AsmKit.requireClass(zip, VanillaSourceClasses.MOB_EFFECTS, "MobEffects");
                MethodNode clinit = AsmKit.requireClinit(classNode, "MobEffects");
                return parseClinit(clinit.instructions);
            } catch (IOException ex) {
                throw new ToolingException(ex, "Failed to read MobEffects class from jar '%s'", jarPath);
            }
        }

        /**
         * Walks the {@code <clinit>} instruction list and emits one {@code (effectId, color)} pair
         * per recognised registration. See the parser javadoc for the recognition rules.
         */
        private static @NotNull ConcurrentMap<String, Integer> parseClinit(@NotNull InsnList instructions) {
            ConcurrentMap<String, Integer> colors = Concurrent.newMap();

            @Nullable String pendingEffectId = null;
            @Nullable Integer pendingColor = null;
            AsmKit.LiteralStack intLiteralStack = new AsmKit.LiteralStack(8);

            for (AbstractInsnNode node = instructions.getFirst(); node != null; node = node.getNext()) {
                Integer literal = AsmKit.readIntLiteral(node);
                if (literal != null) {
                    intLiteralStack.push(literal);
                    continue;
                }

                String str = AsmKit.readStringLiteral(node);
                if (str != null) {
                    // Only capture the first LDC string between registrations (the effect id);
                    // subsequent strings (e.g. attribute modifier ids like "effect.speed") are
                    // ignored by keeping pendingEffectId stable once set.
                    if (pendingEffectId == null) pendingEffectId = str;
                    continue;
                }

                if (AsmKit.isNewInstance(node, VanillaSourceClasses.EFFECT_PACKAGE_PREFIX)) {
                    // A new MobEffect (or subclass) is being constructed; reset the int stack so
                    // only the literals pushed between now and the invokespecial are considered
                    // for the colour.
                    intLiteralStack.reset();
                    continue;
                }

                // Prefix owner match: MobEffect has subclasses, so the exact-owner isInvoke
                // variant in AsmKit doesn't fit. Constructor signature is (MobEffectCategory,
                // int) - the int literal on top of the stack is the ARGB colour.
                if (node.getOpcode() == Opcodes.INVOKESPECIAL
                    && node instanceof MethodInsnNode methodInsn
                    && methodInsn.name.equals(AsmKit.INIT)
                    && methodInsn.owner.startsWith(VanillaSourceClasses.EFFECT_PACKAGE_PREFIX)
                    && methodInsn.desc.equals(MOB_EFFECT_INIT_DESCRIPTOR)) {
                    Integer top = intLiteralStack.popInt();
                    if (top != null) pendingColor = top;
                    continue;
                }

                if (AsmKit.isInvokeStatic(node, VanillaSourceClasses.MOB_EFFECTS, REGISTER_METHOD_NAME)) {
                    if (pendingEffectId != null && pendingColor != null) {
                        colors.put("minecraft:" + pendingEffectId, pendingColor);
                    }
                    pendingEffectId = null;
                    pendingColor = null;
                    intLiteralStack.reset();
                }
            }

            return colors;
        }

    }

}
