package lib.minecraft.renderer.tooling;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentList;
import lib.minecraft.renderer.asset.ColorMap;
import lib.minecraft.renderer.exception.PipelineException;
import lib.minecraft.renderer.exception.ToolingException;
import lib.minecraft.renderer.pipeline.Pipeline;
import lib.minecraft.renderer.pipeline.PipelineOptions;
import lib.minecraft.renderer.pipeline.loader.ColorMapLoader;
import lib.minecraft.renderer.tooling.util.ToolingJson;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Base64;
import java.util.List;
import java.util.Optional;
import javax.imageio.ImageIO;

/**
 * Entry point invoked by the {@code colorMaps} Gradle task.
 * <p>
 * Downloads (or reuses the cached) MC 26.1 client jar, extracts the vanilla assets, reads the
 * three biome colormap PNGs via {@link Parser}, and writes the base64-encoded pixel data to
 * {@code src/main/resources/lib/minecraft/renderer/color_maps.json}. The runtime pipeline reads the
 * JSON via {@link ColorMapLoader} so the PNG-decoding step only runs during development when a new
 * Minecraft version ships.
 */
@UtilityClass
public final class ToolingColorMaps {

    /**
     * Fixed output path for the bundled color-map resource.
     */
    private static final @NotNull Path OUTPUT_PATH = Path.of("src/main/resources/lib/minecraft/renderer/color_maps.json");

    /**
     * Runs the generator.
     *
     * @param args ignored - the output path is fixed to keep the resource location stable
     * @throws IOException if writing the JSON file fails
     */
    public static void main(String @NotNull [] args) throws IOException {
        PipelineOptions options = PipelineOptions.defaults();

        Path jarPath;
        try {
            jarPath = Pipeline.downloadJarToCache(options);
        } catch (PipelineException ex) {
            System.err.println("Failed to download client jar: " + ex.getMessage());
            throw ex;
        }

        Path packRoot = options.getCacheRoot().toPath().resolve("vanilla").resolve(options.getVersion());
        Pipeline.extractClientJar(jarPath, packRoot);

        ConcurrentList<ColorMap> colorMaps = Parser.parse(packRoot);
        System.out.println("Parsed " + colorMaps.size() + " colormaps");

        ToolingJson.writeResource(OUTPUT_PATH,
            "Generated by ToolingColorMaps. From biome colormaps. Run the tooling/colorMaps Gradle task to refresh.",
            options.getVersion(), "color_maps", buildColorMaps(colorMaps));
    }

    /**
     * Builds the {@code color_maps} array: one {@code {type, pixels}} object per colormap, with the
     * pixel data base64-encoded. The {@code //} header + {@code source_version} envelope is added by
     * {@link ToolingJson#writeResource}.
     *
     * @param colorMaps the parsed biome colormaps
     * @return the {@code color_maps} array
     */
    private static @NotNull JsonArray buildColorMaps(@NotNull ConcurrentList<ColorMap> colorMaps) {
        JsonArray entries = new JsonArray();
        for (ColorMap colorMap : colorMaps) {
            JsonObject entry = new JsonObject();
            entry.addProperty("type", colorMap.getType().name());
            entry.addProperty("pixels", Base64.getEncoder().encodeToString(colorMap.getPixels()));
            entries.add(entry);
        }
        return entries;
    }

    /**
     * A parser that reads the three vanilla biome colormap PNGs ({@code grass.png},
     * {@code foliage.png}, {@code dry_foliage.png}) from
     * {@code assets/minecraft/textures/colormap/} and converts them into {@link ColorMap} entities.
     * <p>
     * Each colormap is a 256x256 indexed lookup table sampled at {@code (temperature, downfall)}.
     * The parser stores the raw ARGB pixels as a packed big-endian byte array on the entity so the
     * downstream biome-tint sampling path can round-trip the bytes back to {@code int} pixels via
     * {@link ByteBuffer#asIntBuffer()}. The output is consumed by the {@code colorMaps} Gradle task,
     * which serialises the pixel data as Base64 into the bundled
     * {@code /lib/minecraft/renderer/color_maps.json} resource for runtime use by
     * {@link ColorMapLoader}.
     * <p>
     * The parser is intentionally tolerant of <b>missing</b> files: an absent colormap PNG skips
     * its entry rather than throwing, since legitimate packs may ship a partial colormap set. A
     * file that is present but <b>fails to decode</b> still aborts the run - see {@link #parseOne}.
     *
     * @see ColorMapLoader
     * @see ColorMap
     */
    @UtilityClass
    static class Parser {

        /**
         * The three vanilla colormap PNGs to look for under {@code textures/colormap/}.
         */
        private static final @NotNull List<Source> SOURCES = List.of(
            new Source("grass.png", "vanilla", ColorMap.Type.GRASS),
            new Source("foliage.png", "vanilla", ColorMap.Type.FOLIAGE),
            new Source("dry_foliage.png", "vanilla", ColorMap.Type.DRY_FOLIAGE)
        );

        /**
         * One colormap file to look for under the pack's {@code colormap/} directory.
         *
         * @param fileName the basename of the PNG (e.g. {@code "grass.png"})
         * @param packId the pack id to compose the colormap id against
         * @param type the colormap kind
         */
        private record Source(@NotNull String fileName, @NotNull String packId, @NotNull ColorMap.Type type) {}

        /**
         * Loads every supported colormap PNG under the given pack root.
         *
         * @param packRoot the extracted pack root directory
         * @return a list of loaded colormap entities, one per file that was found
         */
        public static @NotNull ConcurrentList<ColorMap> parse(@NotNull Path packRoot) {
            ConcurrentList<ColorMap> colorMaps = Concurrent.newList();
            Path colormapDir = packRoot.resolve("assets/minecraft/textures/colormap");
            if (!Files.isDirectory(colormapDir)) return colorMaps;

            for (Source source : SOURCES)
                parseOne(colormapDir, source.fileName, source.packId, source.type).ifPresent(colorMaps::add);

            return colorMaps;
        }

        /**
         * Loads a single colormap PNG into a {@link ColorMap} entity, or returns empty when the file
         * is absent. Decoding errors abort the pipeline because a corrupt colormap means downstream
         * tint sampling would silently produce wrong colors.
         * <p>
         * The ARGB pixels are read row-major and packed into a big-endian {@link ByteBuffer} (four
         * bytes per pixel) so the byte array round-trips back to {@code int} pixels at runtime. The
         * entity id is composed as {@code packId:type} (lowercased type name).
         *
         * @param colormapDir the pack's {@code textures/colormap} directory
         * @param filename the basename of the PNG to load (e.g. {@code "grass.png"})
         * @param packId the pack id to compose the colormap id against
         * @param type the colormap kind
         * @return the loaded colormap, or empty when the file is absent
         * @throws ToolingException if the file exists but cannot be read or decoded
         */
        private static @NotNull Optional<ColorMap> parseOne(
            @NotNull Path colormapDir,
            @NotNull String filename,
            @NotNull String packId,
            @NotNull ColorMap.Type type
        ) {
            Path file = colormapDir.resolve(filename);
            if (!Files.isRegularFile(file)) return Optional.empty();

            BufferedImage image;
            try {
                image = ImageIO.read(file.toFile());
            } catch (IOException ex) {
                throw new ToolingException(ex, "Failed to read colormap '%s'", file);
            }
            if (image == null)
                throw new ToolingException("Colormap '%s' could not be decoded", file);

            int width = image.getWidth();
            int height = image.getHeight();
            int[] pixels = new int[width * height];
            image.getRGB(0, 0, width, height, pixels, 0, width);

            ByteBuffer buffer = ByteBuffer.allocate(pixels.length * Integer.BYTES);
            buffer.asIntBuffer().put(pixels);

            String id = packId + ":" + type.name().toLowerCase();
            return Optional.of(new ColorMap(id, packId, type, buffer.array()));
        }

    }

}
