package lib.minecraft.renderer.tooling;

import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import lib.minecraft.renderer.engine.TextureEngine;
import lib.minecraft.renderer.exception.AssetPipelineException;
import lib.minecraft.renderer.asset.pack.ColorMap;
import lib.minecraft.renderer.pipeline.AssetPipelineOptions;
import lib.minecraft.renderer.pipeline.client.ClientJarDownloader;
import lib.minecraft.renderer.pipeline.client.ClientJarExtractor;
import lib.minecraft.renderer.pipeline.client.HttpFetcher;
import lib.minecraft.renderer.pipeline.loader.ColorMapLoader;
import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentList;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Base64;
import java.util.List;
import java.util.Optional;

/**
 * Entry point invoked by the {@code generateColorMaps} Gradle task.
 * <p>
 * Downloads (or reuses the cached) MC client jar, extracts the vanilla assets, reads the three
 * biome colormap PNGs via {@link Parser}, and writes the pixel data to
 * {@code src/main/resources/lib/minecraft/renderer/color_maps.json}. The runtime pipeline reads the JSON via
 * {@link ColorMapLoader} so the PNG reading step
 * only runs during development when a new Minecraft version ships.
 */
@UtilityClass
public final class ToolingColorMaps {

    /** Fixed output path for the bundled color-map resource. */
    private static final @NotNull Path OUTPUT_PATH = Path.of("src/main/resources/lib/minecraft/renderer/color_maps.json");

    /**
     * Runs the generator.
     *
     * @param args ignored - the output path is fixed to keep the resource location stable
     * @throws IOException if writing the JSON file fails
     */
    public static void main(String @NotNull [] args) throws IOException {
        AssetPipelineOptions options = AssetPipelineOptions.defaults();
        HttpFetcher fetcher = new HttpFetcher();

        Path jarPath;
        try {
            jarPath = ClientJarDownloader.download(options, fetcher);
        } catch (AssetPipelineException ex) {
            System.err.println("Failed to download client jar: " + ex.getMessage());
            throw ex;
        }

        Path packRoot = options.getCacheRoot().toPath().resolve("vanilla").resolve(options.getVersion());
        ClientJarExtractor.extract(jarPath, packRoot);

        ConcurrentList<ColorMap> colorMaps = Parser.parse(packRoot);
        System.out.println("Parsed " + colorMaps.size() + " colormaps");

        Files.createDirectories(OUTPUT_PATH.getParent());
        Files.writeString(OUTPUT_PATH, buildJson(colorMaps, options.getVersion()));
        System.out.println("Wrote " + OUTPUT_PATH.toAbsolutePath());
    }

    /**
     * Serialises the parsed colormaps into the bundled JSON format with base64-encoded pixel
     * data. The header comment notes the source jar version so a future contributor can tell
     * at a glance how stale the snapshot is.
     */
    private static @NotNull String buildJson(@NotNull ConcurrentList<ColorMap> colorMaps, @NotNull String mcVersion) {
        JsonObject root = new JsonObject();
        root.addProperty("//", "Generated by ToolingColorMaps. From biome colormaps. Run the tooling/colorMaps Gradle task to refresh.");
        root.addProperty("source_version", mcVersion);

        JsonArray entries = new JsonArray();
        for (ColorMap colorMap : colorMaps) {
            JsonObject entry = new JsonObject();
            entry.addProperty("type", colorMap.getType().name());
            entry.addProperty("pixels", Base64.getEncoder().encodeToString(colorMap.getPixels()));
            entries.add(entry);
        }
        root.add("color_maps", entries);

        return new GsonBuilder().setPrettyPrinting().create().toJson(root) + System.lineSeparator();
    }

    /**
     * A parser that reads the three vanilla biome colormap PNGs ({@code grass.png},
     * {@code foliage.png}, {@code dry_foliage.png}) from
     * {@code assets/minecraft/textures/colormap/} and converts them into {@link ColorMap} entities.
     * <p>
     * Each colormap is a 256x256 indexed lookup table sampled at {@code (temperature, downfall)}.
     * The parser stores the raw ARGB pixels as a packed big-endian byte array on the entity so the
     * downstream {@link TextureEngine#sampleBiomeTint} path
     * can round-trip via {@link ByteBuffer#asIntBuffer()}. The output is consumed by the
     * {@code generateColorMaps} Gradle task, which serialises the pixel data as Base64 into the
     * bundled {@code /lib/minecraft/renderer/color_maps.json} resource for runtime use by
     * {@link ColorMapLoader}.
     * <p>
     * The parser is intentionally tolerant: if a colormap file is missing the corresponding entry
     * is skipped rather than throwing, since legitimate user packs may ship a partial colormap set.
     *
     * @see ColorMapLoader
     * @see ColorMap
     */
    @UtilityClass
    static class Parser {

        /** The three vanilla colormap PNGs to look for under {@code textures/colormap/}. */
        private static final @NotNull List<Source> SOURCES = List.of(
            new Source("grass.png", "vanilla", ColorMap.Type.GRASS),
            new Source("foliage.png", "vanilla", ColorMap.Type.FOLIAGE),
            new Source("dry_foliage.png", "vanilla", ColorMap.Type.DRY_FOLIAGE)
        );

        /**
         * One colormap file to look for under the pack's {@code colormap/} directory.
         *
         * @param fileName the basename of the PNG (e.g. {@code "grass.png"})
         * @param packId the pack id to compose the colormap id against
         * @param type the colormap kind
         */
        private record Source(@NotNull String fileName, @NotNull String packId, @NotNull ColorMap.Type type) {}

        /**
         * Loads every supported colormap PNG under the given pack root.
         *
         * @param packRoot the extracted pack root directory
         * @return a list of loaded colormap entities, one per file that was found
         */
        public static @NotNull ConcurrentList<ColorMap> parse(@NotNull Path packRoot) {
            ConcurrentList<ColorMap> colorMaps = Concurrent.newList();
            Path colormapDir = packRoot.resolve("assets/minecraft/textures/colormap");
            if (!Files.isDirectory(colormapDir)) return colorMaps;

            for (Source source : SOURCES)
                parseOne(colormapDir, source.fileName, source.packId, source.type).ifPresent(colorMaps::add);

            return colorMaps;
        }

        /**
         * Loads a single colormap PNG into a {@link ColorMap} entity, or returns empty when the file
         * is absent. Decoding errors abort the pipeline because a corrupt colormap means downstream
         * tint sampling would silently produce wrong colors.
         */
        private static @NotNull Optional<ColorMap> parseOne(
            @NotNull Path colormapDir,
            @NotNull String filename,
            @NotNull String packId,
            @NotNull ColorMap.Type type
        ) {
            Path file = colormapDir.resolve(filename);
            if (!Files.isRegularFile(file)) return Optional.empty();

            BufferedImage image;
            try {
                image = ImageIO.read(file.toFile());
            } catch (IOException ex) {
                throw new AssetPipelineException(ex, "Failed to read colormap '%s'", file);
            }
            if (image == null)
                throw new AssetPipelineException("Colormap '%s' could not be decoded", file);

            int width = image.getWidth();
            int height = image.getHeight();
            int[] pixels = new int[width * height];
            image.getRGB(0, 0, width, height, pixels, 0, width);

            ByteBuffer buffer = ByteBuffer.allocate(pixels.length * Integer.BYTES);
            buffer.asIntBuffer().put(pixels);

            String id = packId + ":" + type.name().toLowerCase();
            return Optional.of(new ColorMap(id, packId, type, buffer.array()));
        }

    }

}
