package lib.minecraft.renderer.content.table;

import dev.simplified.annotations.UtilityClass;
import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentMap;
import lib.minecraft.renderer.content.read.BundledResource;
import lib.minecraft.renderer.content.read.ResourceDocument;
import lib.minecraft.renderer.exception.ContentException;
import org.jetbrains.annotations.NotNull;

import java.util.LinkedHashMap;

/**
 * The reader for the block-to-item alias map.
 *
 * <p>{@code block_items.json} carries an {@code aliases{}} object mapping each secondary block id (a
 * block that owns no item of its own - a wall banner, a wall skull / head, a filled cauldron,
 * {@code big_dripleaf_stem}) to the standing block id whose item both share, generated by
 * {@code BlockItemsFlow} from the vanilla {@code Items} registry. The runtime uses it so an
 * aliased block's inventory icon poses through the shared item's {@code display.gui} rather than the
 * default iso pose, matching the in-game inventory.
 */
@UtilityClass
public final class BlockItemsLoader {

    private static final @NotNull String RESOURCE_NAME = "block_items.json";

    /**
     * Reads the secondary-to-standing block-item alias map from {@code block_items.json}. Iteration
     * order mirrors the on-disk JSON.
     *
     * @return secondary block id to the standing block id whose item it shares; blocks that own their
     *     own item are absent
     * @throws ContentException if the resource is missing, does not bind, or has no {@code aliases} object
     */
    public static @NotNull ConcurrentMap<String, String> load() {
        ResourceDocument document = BundledResource.require(RESOURCE_NAME);
        AliasDoc doc = document.as(AliasDoc.class);
        if (doc.aliases() == null)
            throw new ContentException("Block-items resource '%s' has no 'aliases' object", RESOURCE_NAME);
        return Concurrent.adoptLinkedMap(doc.aliases()).toUnmodifiable();
    }

    /** The {@code block_items.json} payload: the secondary-to-standing block-item alias map. */
    record AliasDoc(@NotNull LinkedHashMap<String, String> aliases) {}
}
