package lib.minecraft.renderer.pipeline.loader;

import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentMap;
import lib.minecraft.renderer.exception.PipelineException;
import lib.minecraft.renderer.pipeline.load.BundledResource;
import lib.minecraft.renderer.pipeline.load.ResourceDocument;
import lib.minecraft.renderer.tooling.kernel.Diagnostics;
import org.jetbrains.annotations.NotNull;

import java.util.HashMap;
import java.util.Map;

/**
 * The reader for the block-to-item alias map.
 *
 * <p>{@code block_items.json} carries an {@code aliases{}} object mapping each secondary block id (a
 * block that owns no item of its own - a wall banner, a wall skull / head, a filled cauldron,
 * {@code big_dripleaf_stem}) to the standing block id whose item both share, generated by
 * {@code ToolingBlockItems} from the vanilla {@code Items} registry. The runtime uses it so an
 * aliased block's inventory icon poses through the shared item's {@code display.gui} rather than the
 * default iso pose, matching the in-game inventory.
 */
public final class BlockItemsLoader {

    private static final @NotNull String RESOURCE_NAME = "block_items.json";

    private BlockItemsLoader() {}

    /**
     * Reads the secondary-to-standing block-item alias map from {@code block_items.json}.
     *
     * @param diagnostics the scope envelope warnings are recorded to
     * @return secondary block id to the standing block id whose item it shares, wrapped unmodifiable;
     *     blocks that own their own item are absent
     * @throws PipelineException if the resource is missing or has no {@code aliases} object
     */
    public static @NotNull ConcurrentMap<String, String> load(@NotNull Diagnostics diagnostics) {
        ResourceDocument document = BundledResource.read(RESOURCE_NAME, BundledResource.MissingPolicy.REQUIRED, diagnostics).orElseThrow();
        AliasDoc doc = document.as(AliasDoc.class);
        if (doc.aliases() == null)
            throw new PipelineException("Block-items resource '%s' has no 'aliases' object", RESOURCE_NAME);
        return Concurrent.adoptMap(new HashMap<>(doc.aliases())).toUnmodifiable();
    }

    /** The {@code block_items.json} payload: the secondary-to-standing block-item alias map. */
    record AliasDoc(@NotNull Map<String, String> aliases) {}
}
