package lib.minecraft.renderer.visual;

import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentList;
import lib.minecraft.renderer.exception.PipelineException;
import lib.minecraft.renderer.pipeline.Pipeline;
import lib.minecraft.renderer.pipeline.PipelineOptions;
import lib.minecraft.renderer.pipeline.PipelineRendererContext;
import lib.minecraft.renderer.kit.RedstoneKit;
import lombok.experimental.UtilityClass;
import org.jetbrains.annotations.NotNull;

import javax.imageio.ImageIO;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Diagnostic task that proves the {@code ColorProperties} wiring end-to-end through the 16
 * {@code redstone.0..redstone.15} keys. Builds two pipelines - vanilla-only and vanilla plus a
 * synthetic pack whose {@code optifine/color.properties} remaps every redstone power level to a
 * deliberately-distinct HSV-spaced gradient - then renders 16 swatches per row (vanilla on top,
 * override on bottom) into {@code cache/visual/redstone-tints/swatch.png}.
 * <p>
 * If the wiring is broken, the override row equals the vanilla row and the visual mismatch is
 * immediate. The companion {@code RedstoneKitTest} pins the same path with strict pixel
 * assertions in the regular test suite.
 * <p>
 * Usage: {@code ./gradlew :asset-renderer:redstoneTints [-PrenderSize=64]}
 */
@UtilityClass
public final class TestRedstoneTints {

    /**
     * Synthetic pack id used for the temp pack directory. Sanitised because
     * {@code PackAcquirer.derivePackId} would normally do the same on a zip filename.
     */
    private static final @NotNull String SYNTHETIC_PACK_ID = "redstone_tints_visual";

    /**
     * Runs the redstone-tint comparison.
     *
     * @param args {@code args[0]} optional cell-size in pixels (defaults to 64)
     * @throws IOException if any output cannot be written
     */
    public static void main(String @NotNull [] args) throws IOException {
        int size = args.length > 0 ? Integer.parseInt(args[0]) : 64;

        Path packDir = materializeOverridePack();
        System.out.println("Synthesised override pack at " + packDir);

        System.out.println("Building vanilla-only pipeline...");
        PipelineRendererContext vanilla = buildContext(Concurrent.newList());

        System.out.println("Building vanilla + override pipeline...");
        ConcurrentList<File> userPacks = Concurrent.newList(packDir.toFile());
        PipelineRendererContext withOverrides = buildContext(userPacks);

        Path outputDir = Path.of("cache/visual/redstone-tints");
        Files.createDirectories(outputDir);

        BufferedImage swatch = composeSwatch(vanilla, withOverrides, size);
        File swatchFile = outputDir.resolve("swatch.png").toFile();
        ImageIO.write(swatch, "PNG", swatchFile);
        System.out.println("Wrote " + swatchFile.getAbsolutePath());
    }

    /**
     * Writes a temporary pack directory under {@code cache/asset-renderer/packs/<id>/} containing
     * a minimal {@code pack.mcmeta} (required by {@code PackResolver}) and
     * {@code assets/minecraft/optifine/color.properties} with all 16 {@code redstone.N} entries
     * remapped to the synthetic gradient. The pack is durable so re-runs reuse it; the renderer's
     * pack cache lives at the same path so a stale stub would also be picked up.
     */
    private static @NotNull Path materializeOverridePack() throws IOException {
        Path packDir = Path.of("cache/asset-renderer/packs").resolve(SYNTHETIC_PACK_ID);
        Path optifineDir = packDir.resolve("assets/minecraft/optifine");
        Files.createDirectories(optifineDir);

        Files.writeString(packDir.resolve("pack.mcmeta"),
            "{\"pack\":{\"pack_format\":46,\"description\":\"Synthetic redstone tint override pack\"}}");

        StringBuilder properties = new StringBuilder();
        properties.append("# Generated by TestRedstoneTints - distinct HSV gradient\n");
        for (int power = 0; power < 16; power++) {
            int argb = syntheticOverrideForPower(power);
            properties.append("redstone.").append(power).append("=0x").append(String.format("%06X", argb & 0xFFFFFF)).append("\n");
        }
        Files.writeString(optifineDir.resolve("color.properties"), properties.toString());
        return packDir;
    }

    /**
     * Builds a pipeline context with the given user packs. Logs and rethrows pipeline failures so
     * the caller sees a clear bootstrap error message.
     */
    private static @NotNull PipelineRendererContext buildContext(@NotNull ConcurrentList<File> userPacks) {
        PipelineOptions options = PipelineOptions.defaults()
            .mutate()
            .texturePacks(userPacks)
            .build();
        try {
            Pipeline.Result result = Pipeline.run(options);
            return PipelineRendererContext.of(result);
        } catch (PipelineException ex) {
            System.err.println("Pipeline bootstrap failed: " + ex.getMessage());
            throw ex;
        }
    }

    /**
     * Composites the 16-cell swatch grid: top row = vanilla per-power tints, bottom row = override
     * tints. Each cell is {@code size x size}; rows are separated by a label strip and the whole
     * image is captioned.
     */
    private static @NotNull BufferedImage composeSwatch(
        @NotNull PipelineRendererContext vanilla,
        @NotNull PipelineRendererContext withOverrides,
        int size
    ) {
        int cells = 16;
        int labelStrip = Math.max(20, size / 4);
        int titleStrip = Math.max(24, size / 3);
        int width = size * cells;
        int height = titleStrip + labelStrip + size + labelStrip + size + labelStrip;

        BufferedImage out = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = out.createGraphics();
        try {
            g.setColor(new Color(40, 40, 40));
            g.fillRect(0, 0, width, height);

            g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
            g.setColor(Color.WHITE);
            g.setFont(new Font(Font.MONOSPACED, Font.BOLD, Math.max(12, titleStrip - 8)));
            FontMetrics tm = g.getFontMetrics();
            String title = "redstone.0..15  -  vanilla (top) vs synthetic-override pack (bottom)";
            g.drawString(title, (width - tm.stringWidth(title)) / 2, (titleStrip + tm.getAscent()) / 2);

            int powerY = titleStrip;
            int vanillaCellsY = powerY + labelStrip;
            int overrideY = vanillaCellsY + size + labelStrip;

            g.setFont(new Font(Font.MONOSPACED, Font.PLAIN, Math.max(10, labelStrip - 6)));
            FontMetrics lm = g.getFontMetrics();
            for (int power = 0; power < cells; power++) {
                String label = String.valueOf(power);
                int labelX = power * size + (size - lm.stringWidth(label)) / 2;
                g.setColor(Color.LIGHT_GRAY);
                g.drawString(label, labelX, powerY + (labelStrip + lm.getAscent()) / 2 - 2);

                int vanillaArgb = RedstoneKit.resolve(vanilla, power);
                g.setColor(new Color(vanillaArgb, true));
                g.fillRect(power * size, vanillaCellsY, size, size);

                int overrideArgb = RedstoneKit.resolve(withOverrides, power);
                g.setColor(new Color(overrideArgb, true));
                g.fillRect(power * size, overrideY, size, size);
            }

            int rowLabelY = overrideY + size + (labelStrip + lm.getAscent()) / 2 - 2;
            g.setColor(Color.LIGHT_GRAY);
            String footer = "matching rows == wiring broken (pack overrides not reaching context)";
            g.drawString(footer, (width - lm.stringWidth(footer)) / 2, rowLabelY);
        } finally {
            g.dispose();
        }
        return out;
    }

    /**
     * The same HSV gradient used by {@code RedstoneKitTest.syntheticOverrideForPower} so the
     * visual and the unit test agree on the expected override values.
     */
    private static int syntheticOverrideForPower(int power) {
        float hue = power / 16f;
        int rgb = Color.HSBtoRGB(hue, 1f, 1f);
        return 0xFF000000 | (rgb & 0x00FFFFFF);
    }

}
